### ISSUE TITLE
Allow to configure kamel CLI with env vars and configuration files

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1108]
It should be possible to set values for the kamel CLI options through 

1.  **config files:**
```yaml
kamel:
  install:
    example: true
    global: true
    registry-insecure: true
```

2.  **environment variables:**
```
KAMEL_INSTALL_BASE_IMAGE=base_env
KAMEL_INSTALL_OPERATOR_IMAGE=operator_env
KAMEL_INSTALL_REGISTRY=registry_env
```

3. **cli options**
```
--operator-image=operator_cli --organization=test_cli --registry-secret=secret
```
