### ISSUE TITLE
Create a Github Action for Camel K

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1163]
Prospect feature.

We may add a github action that setups a Kubernetes environment ready for Camel K (e.g. based on KinD) and brings the kamel CLI.

Users can use it to deploy Camel K integrations and check their state.. In the future with BDD testing features.

**Comment by apupier** [comment]
for reference:
- github action for Kind https://github.com/marketplace/actions/kind-kubernetes-in-docker-action
- github action for Kubernetes https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster

nota both of them are working only on Linux (but sounds reasonable as a first iteration)

**Comment by apupier** [comment]
wondering if it should be an all-in-one action which is installing there container and then Camel K inside or if the container host should be a prerequisite

**Comment by apupier** [comment]
example to have Camel K configured on Minikube currently:

```
name: Test

on: [push]

jobs:
  test:
    name: Test Camel K
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.2.0
        with:
          minikube version: 'v1.15.1'
          kubernetes version: 'v1.20.0'
          driver: 'docker'
      - name: Install Kamel
        run: |
            minikube addons enable registry
            curl -Lo kamel.tar.gz https://github.com/apache/camel-k/releases/download/v1.2.1/camel-k-client-1.2.1-linux-64bit.tar.gz
            tar -zxvf kamel.tar.gz
            chmod +x kamel
            sudo mv kamel /usr/local/bin/
            kamel install
      - name: Test kamel
        run: kamel get
```
