### ISSUE TITLE
Knative integration takes too long to make the service ready

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#1172]
When trying to create a Knative integration I observe that the Knative service is taking too long to get to ready state and sometimes its struck in `RevisionMissing` state.  This happens in both `--dev` mode as well as in `production` mode. This is highly inconsistent as sometimes it refreshes the state of the service soon but after few runs its starts to get hung .

It is also noted it takes very long time to trigger the service deployment after we call `kamel run`, wondering something to do with Knative Serving reconcilation ? There should be a way to force the knative recocilation, so that new reivision is updated with Ready state as soon as possible.

Example integation:

```yaml
- from:
    uri: "knative:endpoint/echoer"
    steps:
      - log:
          message: "Got Message: ${body}"
      - convert-body: "java.lang.String"
      - choice:
          when:
            - simple: "${body} != null && ${body.length} > 0"
              steps:
                - set-body:
                    simple: "${body.toUpperCase()}"
                - set-header:
                    name: ContentType
                    simple: text/plain
                - log:
                    message: "${body}"
          otherwise:
            steps:
              - set-body:
                  constant: "no body received"
              - set-header:
                  name: ContentType
                  simple: text/plain
              - log:
                  message: "Otherwise::${body}"

```
