### ISSUE TITLE
Configurable maven options

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1332]
When a maven build is triggered, it shows transfer when downloading artifacts, we should make it configurable i.e. by letting user to define global maven options

```yaml
  apiVersion: camel.apache.org/v1
  kind: IntegrationPlatform
  metadata:
    labels:
      app: camel-k
    name: camel-k
  spec:
    build:
      maven:
        options:
          - "--no-transfer-progress"
          - "-V"
```
