### ISSUE TITLE
Support inline YAML DSL 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1470]
Routes can now be defined using the source block which is fine but we can also support in-lined YAML, something like:

```yaml
spec:
    sources:
      ...
    flows:
    - from:
        uri: "direct:start"
        steps:
```
