### ISSUE TITLE
Can't connect to prometheus endpoint in 1.0.0 (not running?)

### ISSUE THREAD

**Issue by dylanenabled** [apache/camel-k#1525]
I'm running an integration with 

```bash
kamel run -n "${KUBECTL_NAMESPACE}" ${FLAGS} \
  ${DEPS} \
  --trait prometheus.enabled=true \
  --trait prometheus.service-monitor=false \
  --secret=logr-air-camelk-config \
  --configmap=logr-air-consumer-config \
  --wait \
  integration.kts
```

Previously (on 1.0.0.RC2) this created a container with port 9779 open which I could then  `kubectl port-forward` to connect to and see the prometheus metrics, but now it gives 

```
E0612 21:41:49.945801   28422 portforward.go:400] an error occurred forwarding 9779 -> 9779: error forwarding port 9779 to pod 64d5e332e575c3bf4b848eef4442bf6e71bb2bd45c0d121e6985be813c0e723f, uid : exit status 1: 2020/06/12 12:11:49 socat[16134] E connect(5, AF=2 127.0.0.1:9779, 16): Connection refused
```

I'm not using prometheus operator (just the prometheus helm chart) so I disabled service monitor, that didn't matter previously though.

After looking through the container, it looks like there is no port on 9779 open, though the port definition is listed in the kubernetes pod manifest.

Any help would be appreciated.

**Comment by dylanenabled** [comment]
It looks like the prometheus jmx java agent isn't running - the pod args look like:
```
spec:
  containers:
  - args:
    - echo java -cp ./resources:/etc/camel/conf.d/_configmaps/logr-air-consumer-config:/etc/camel/conf.d/_secrets/logr-air-camelk-config:/etc/camel/resources:/etc/camel/sources/i-source-000:/etc/prometheus:dependencies/com.amazonaws.aws-java-sdk-core-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-kms-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-s3-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-ses-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-sqs-1.11.714.jar:dependencies/com.amazonaws.jmespath-java-1.11.714.jar:dependencies/com.fasterxml.jackson.core.jackson-annotations-2.10.4.jar:dependencies/com.fasterxml.jackson.core.jackson-core-2.10.4.jar:dependencies/com.fasterxml.jackson.core.jackson-databind-2.10.4.jar:dependencies/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.6.7.jar:dependencies/com.ibm.icu.icu4j-65.1.jar:dependencies/com.jayway.jsonpath.json-path-2.4.0.jar:dependencies/com.mchange.c3p0-0.9.5.5.jar:dependencies/com.mchange.mchange-commons-java-0.2.15.jar:dependencies/com.sun.activation.jakarta.activation-1.2.1.jar:dependencies/com.sun.activation.javax.activation-1.2.0.jar:dependencies/com.sun.mail.jakarta.mail-1.6.5.jar:dependencies/com.syncron.amazonaws.simba-athena-jdbc-driver-2.0.2.jar:dependencies/com.zaxxer.HikariCP-java7-2.4.13.jar:dependencies/commons-codec.commons-codec-1.11.jar:dependencies/commons-logging.commons-logging-1.2.jar:dependencies/io.dropwizard.metrics.metrics-core-4.0.5.jar:dependencies/io.dropwizard.metrics.metrics-jmx-4.0.5.jar:dependencies/io.micrometer.micrometer-core-1.5.0.jar:dependencies/io.micrometer.micrometer-registry-jmx-1.2.2.jar:dependencies/io.prometheus.jmx.jmx_prometheus_javaagent-0.3.1.jar:dependencies/javax.servlet.javax.servlet-api-3.1.0.jar:dependencies/joda-time.joda-time-2.8.1.jar:dependencies/net.minidev.accessors-smart-1.2.jar:dependencies/net.minidev.json-smart-2.3.jar:dependencies/org.apache.camel.camel-api-3.3.0.jar:dependencies/org.apache.camel.camel-attachments-3.3.0.jar:dependencies/org.apache.camel.camel-aws-s3-3.3.0.jar:dependencies/org.apache.camel.camel-aws-ses-3.3.0.jar:dependencies/org.apache.camel.camel-aws-sqs-3.3.0.jar:dependencies/org.apache.camel.camel-base-3.3.0.jar:dependencies/org.apache.camel.camel-bean-3.3.0.jar:dependencies/org.apache.camel.camel-bindy-3.3.0.jar:dependencies/org.apache.camel.camel-cloud-3.3.0.jar:dependencies/org.apache.camel.camel-cluster-3.3.0.jar:dependencies/org.apache.camel.camel-core-catalog-3.3.0.jar:dependencies/org.apache.camel.camel-core-engine-3.3.0.jar:dependencies/org.apache.camel.camel-core-languages-3.3.0.jar:dependencies/org.apache.camel.camel-cron-3.3.0.jar:dependencies/org.apache.camel.camel-csv-3.3.0.jar:dependencies/org.apache.camel.camel-direct-3.3.0.jar:dependencies/org.apache.camel.camel-endpointdsl-3.3.0.jar:dependencies/org.apache.camel.camel-file-3.3.0.jar:dependencies/org.apache.camel.camel-http-3.3.0.jar:dependencies/org.apache.camel.camel-http-base-3.3.0.jar:dependencies/org.apache.camel.camel-http-common-3.3.0.jar:dependencies/org.apache.camel.camel-jackson-3.3.0.jar:dependencies/org.apache.camel.camel-jdbc-3.3.0.jar:dependencies/org.apache.camel.camel-jsonpath-3.3.0.jar:dependencies/org.apache.camel.camel-log-3.3.0.jar:dependencies/org.apache.camel.camel-mail-3.3.0.jar:dependencies/org.apache.camel.camel-main-3.3.0.jar:dependencies/org.apache.camel.camel-management-3.3.0.jar:dependencies/org.apache.camel.camel-management-api-3.3.0.jar:dependencies/org.apache.camel.camel-micrometer-3.3.0.jar:dependencies/org.apache.camel.camel-quartz-3.3.0.jar:dependencies/org.apache.camel.camel-support-3.3.0.jar:dependencies/org.apache.camel.camel-timer-3.3.0.jar:dependencies/org.apache.camel.camel-tooling-model-3.3.0.jar:dependencies/org.apache.camel.camel-util-3.3.0.jar:dependencies/org.apache.camel.camel-util-json-3.3.0.jar:dependencies/org.apache.camel.k.camel-k-loader-kotlin-1.3.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-core-1.3.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-cron-1.3.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-main-1.3.0.jar:dependencies/org.apache.commons.commons-csv-1.6.jar:dependencies/org.apache.httpcomponents.httpclient-4.5.12.jar:dependencies/org.apache.httpcomponents.httpcore-4.4.13.jar:dependencies/org.apache.logging.log4j.log4j-api-2.13.3.jar:dependencies/org.apache.logging.log4j.log4j-core-2.13.3.jar:dependencies/org.apache.logging.log4j.log4j-slf4j-impl-2.13.3.jar:dependencies/org.hdrhistogram.HdrHistogram-2.1.12.jar:dependencies/org.jetbrains.annotations-13.0.jar:dependencies/org.jetbrains.intellij.deps.trove4j-1.0.20181211.jar:dependencies/org.jetbrains.kotlin.kotlin-compiler-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-daemon-client-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-reflect-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-script-runtime-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-script-util-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-common-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-compiler-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-compiler-impl-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-js-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-jvm-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-jvm-host-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-common-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-jdk7-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-jdk8-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-util-io-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-util-klib-1.3.72.jar:dependencies/org.jetbrains.kotlinx.kotlinx-coroutines-core-1.2.1.jar:dependencies/org.latencyutils.LatencyUtils-2.0.3.jar:dependencies/org.ow2.asm.asm-5.0.4.jar:dependencies/org.quartz-scheduler.quartz-2.3.2.jar:dependencies/org.slf4j.slf4j-api-1.7.30.jar:dependencies/org.springframework.spring-beans-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-core-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-jcl-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-jdbc-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-tx-5.2.6.RELEASE.jar:dependencies/software.amazon.ion.ion-java-1.0.2.jar
      org.apache.camel.k.main.Application && java -cp ./resources:/etc/camel/conf.d/_configmaps/logr-air-consumer-config:/etc/camel/conf.d/_secrets/logr-air-camelk-config:/etc/camel/resources:/etc/camel/sources/i-source-000:/etc/prometheus:dependencies/com.amazonaws.aws-java-sdk-core-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-kms-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-s3-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-ses-1.11.714.jar:dependencies/com.amazonaws.aws-java-sdk-sqs-1.11.714.jar:dependencies/com.amazonaws.jmespath-java-1.11.714.jar:dependencies/com.fasterxml.jackson.core.jackson-annotations-2.10.4.jar:dependencies/com.fasterxml.jackson.core.jackson-core-2.10.4.jar:dependencies/com.fasterxml.jackson.core.jackson-databind-2.10.4.jar:dependencies/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.6.7.jar:dependencies/com.ibm.icu.icu4j-65.1.jar:dependencies/com.jayway.jsonpath.json-path-2.4.0.jar:dependencies/com.mchange.c3p0-0.9.5.5.jar:dependencies/com.mchange.mchange-commons-java-0.2.15.jar:dependencies/com.sun.activation.jakarta.activation-1.2.1.jar:dependencies/com.sun.activation.javax.activation-1.2.0.jar:dependencies/com.sun.mail.jakarta.mail-1.6.5.jar:dependencies/com.syncron.amazonaws.simba-athena-jdbc-driver-2.0.2.jar:dependencies/com.zaxxer.HikariCP-java7-2.4.13.jar:dependencies/commons-codec.commons-codec-1.11.jar:dependencies/commons-logging.commons-logging-1.2.jar:dependencies/io.dropwizard.metrics.metrics-core-4.0.5.jar:dependencies/io.dropwizard.metrics.metrics-jmx-4.0.5.jar:dependencies/io.micrometer.micrometer-core-1.5.0.jar:dependencies/io.micrometer.micrometer-registry-jmx-1.2.2.jar:dependencies/io.prometheus.jmx.jmx_prometheus_javaagent-0.3.1.jar:dependencies/javax.servlet.javax.servlet-api-3.1.0.jar:dependencies/joda-time.joda-time-2.8.1.jar:dependencies/net.minidev.accessors-smart-1.2.jar:dependencies/net.minidev.json-smart-2.3.jar:dependencies/org.apache.camel.camel-api-3.3.0.jar:dependencies/org.apache.camel.camel-attachments-3.3.0.jar:dependencies/org.apache.camel.camel-aws-s3-3.3.0.jar:dependencies/org.apache.camel.camel-aws-ses-3.3.0.jar:dependencies/org.apache.camel.camel-aws-sqs-3.3.0.jar:dependencies/org.apache.camel.camel-base-3.3.0.jar:dependencies/org.apache.camel.camel-bean-3.3.0.jar:dependencies/org.apache.camel.camel-bindy-3.3.0.jar:dependencies/org.apache.camel.camel-cloud-3.3.0.jar:dependencies/org.apache.camel.camel-cluster-3.3.0.jar:dependencies/org.apache.camel.camel-core-catalog-3.3.0.jar:dependencies/org.apache.camel.camel-core-engine-3.3.0.jar:dependencies/org.apache.camel.camel-core-languages-3.3.0.jar:dependencies/org.apache.camel.camel-cron-3.3.0.jar:dependencies/org.apache.camel.camel-csv-3.3.0.jar:dependencies/org.apache.camel.camel-direct-3.3.0.jar:dependencies/org.apache.camel.camel-endpointdsl-3.3.0.jar:dependencies/org.apache.camel.camel-file-3.3.0.jar:dependencies/org.apache.camel.camel-http-3.3.0.jar:dependencies/org.apache.camel.camel-http-base-3.3.0.jar:dependencies/org.apache.camel.camel-http-common-3.3.0.jar:dependencies/org.apache.camel.camel-jackson-3.3.0.jar:dependencies/org.apache.camel.camel-jdbc-3.3.0.jar:dependencies/org.apache.camel.camel-jsonpath-3.3.0.jar:dependencies/org.apache.camel.camel-log-3.3.0.jar:dependencies/org.apache.camel.camel-mail-3.3.0.jar:dependencies/org.apache.camel.camel-main-3.3.0.jar:dependencies/org.apache.camel.camel-management-3.3.0.jar:dependencies/org.apache.camel.camel-management-api-3.3.0.jar:dependencies/org.apache.camel.camel-micrometer-3.3.0.jar:dependencies/org.apache.camel.camel-quartz-3.3.0.jar:dependencies/org.apache.camel.camel-support-3.3.0.jar:dependencies/org.apache.camel.camel-timer-3.3.0.jar:dependencies/org.apache.camel.camel-tooling-model-3.3.0.jar:dependencies/org.apache.camel.camel-util-3.3.0.jar:dependencies/org.apache.camel.camel-util-json-3.3.0.jar:dependencies/org.apache.camel.k.camel-k-loader-kotlin-1.3.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-core-1.3.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-cron-1.3.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-main-1.3.0.jar:dependencies/org.apache.commons.commons-csv-1.6.jar:dependencies/org.apache.httpcomponents.httpclient-4.5.12.jar:dependencies/org.apache.httpcomponents.httpcore-4.4.13.jar:dependencies/org.apache.logging.log4j.log4j-api-2.13.3.jar:dependencies/org.apache.logging.log4j.log4j-core-2.13.3.jar:dependencies/org.apache.logging.log4j.log4j-slf4j-impl-2.13.3.jar:dependencies/org.hdrhistogram.HdrHistogram-2.1.12.jar:dependencies/org.jetbrains.annotations-13.0.jar:dependencies/org.jetbrains.intellij.deps.trove4j-1.0.20181211.jar:dependencies/org.jetbrains.kotlin.kotlin-compiler-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-daemon-client-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-reflect-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-script-runtime-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-script-util-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-common-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-compiler-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-compiler-impl-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-js-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-jvm-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-jvm-host-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-common-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-jdk7-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-jdk8-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-util-io-1.3.72.jar:dependencies/org.jetbrains.kotlin.kotlin-util-klib-1.3.72.jar:dependencies/org.jetbrains.kotlinx.kotlinx-coroutines-core-1.2.1.jar:dependencies/org.latencyutils.LatencyUtils-2.0.3.jar:dependencies/org.ow2.asm.asm-5.0.4.jar:dependencies/org.quartz-scheduler.quartz-2.3.2.jar:dependencies/org.slf4j.slf4j-api-1.7.30.jar:dependencies/org.springframework.spring-beans-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-core-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-jcl-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-jdbc-5.2.6.RELEASE.jar:dependencies/org.springframework.spring-tx-5.2.6.RELEASE.jar:dependencies/software.amazon.ion.ion-java-1.0.2.jar
      org.apache.camel.k.main.Application
```
It's added the dependency for jmx_prometheus_javaagent but it doesn't seem to actually start it with `-javaagent`

**Comment by dylanenabled** [comment]
The old operator (1.0.0.RC2) has this as the args for the same integration pod
```
spec:
  containers:
  - args:
    - -javaagent:dependencies/io.prometheus.jmx.jmx_prometheus_javaagent-0.3.1.jar=9779:/etc/prometheus/prometheus-jmx-exporter.yaml
    - -cp
    - ./resources:/etc/camel/conf:/etc/camel/conf.d/_configmaps/logr-air-consumer-config:/etc/camel/conf.d/_secrets/logr-air-camelk-config:/etc/camel/resources:/etc/camel/sources/i-source-000:/etc/prometheus:dependencies/com.amazonaws.aws-java-sdk-core-1.11.658.jar:dependencies/com.amazonaws.aws-java-sdk-kms-1.11.658.jar:dependencies/com.amazonaws.aws-java-sdk-s3-1.11.658.jar:dependencies/com.amazonaws.aws-java-sdk-sqs-1.11.658.jar:dependencies/com.amazonaws.jmespath-java-1.11.658.jar:dependencies/com.fasterxml.jackson.core.jackson-annotations-2.10.1.jar:dependencies/com.fasterxml.jackson.core.jackson-core-2.10.1.jar:dependencies/com.fasterxml.jackson.core.jackson-databind-2.10.1.jar:dependencies/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.6.7.jar:dependencies/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.1.jar:dependencies/com.github.ben-manes.caffeine.caffeine-2.8.0.jar:dependencies/com.jayway.jsonpath.json-path-2.4.0.jar:dependencies/com.sun.activation.javax.activation-1.2.0.jar:dependencies/commons-codec.commons-codec-1.11.jar:dependencies/commons-io.commons-io-2.6.jar:dependencies/commons-logging.commons-logging-1.2.jar:dependencies/io.prometheus.jmx.jmx_prometheus_javaagent-0.3.1.jar:dependencies/jakarta.activation.jakarta.activation-api-1.2.1.jar:dependencies/jakarta.xml.bind.jakarta.xml.bind-api-2.3.2.jar:dependencies/javax.servlet.javax.servlet-api-3.1.0.jar:dependencies/joda-time.joda-time-2.8.1.jar:dependencies/net.minidev.accessors-smart-1.2.jar:dependencies/net.minidev.json-smart-2.3.jar:dependencies/net.minidev.json-smart-action-2.3.jar:dependencies/org.apache.camel.camel-api-3.0.1.jar:dependencies/org.apache.camel.camel-attachments-3.0.1.jar:dependencies/org.apache.camel.camel-aws-s3-3.0.1.jar:dependencies/org.apache.camel.camel-aws-sqs-3.0.1.jar:dependencies/org.apache.camel.camel-base-3.0.1.jar:dependencies/org.apache.camel.camel-bean-3.0.1.jar:dependencies/org.apache.camel.camel-bindy-3.0.1.jar:dependencies/org.apache.camel.camel-caffeine-lrucache-3.0.1.jar:dependencies/org.apache.camel.camel-cloud-3.0.1.jar:dependencies/org.apache.camel.camel-core-engine-3.0.1.jar:dependencies/org.apache.camel.camel-direct-3.0.1.jar:dependencies/org.apache.camel.camel-endpointdsl-3.0.1.jar:dependencies/org.apache.camel.camel-file-3.0.1.jar:dependencies/org.apache.camel.camel-http-3.0.1.jar:dependencies/org.apache.camel.camel-http-common-3.0.1.jar:dependencies/org.apache.camel.camel-jackson-3.0.1.jar:dependencies/org.apache.camel.camel-jaxp-3.0.1.jar:dependencies/org.apache.camel.camel-jsonpath-3.0.1.jar:dependencies/org.apache.camel.camel-log-3.0.1.jar:dependencies/org.apache.camel.camel-main-3.0.1.jar:dependencies/org.apache.camel.camel-management-3.0.1.jar:dependencies/org.apache.camel.camel-management-api-3.0.1.jar:dependencies/org.apache.camel.camel-support-3.0.1.jar:dependencies/org.apache.camel.camel-timer-3.0.1.jar:dependencies/org.apache.camel.camel-util-3.0.1.jar:dependencies/org.apache.camel.camel-util-json-3.0.1.jar:dependencies/org.apache.camel.k.camel-k-loader-kotlin-1.1.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-core-1.1.0.jar:dependencies/org.apache.camel.k.camel-k-runtime-main-1.1.0.jar:dependencies/org.apache.camel.spi-annotations-3.0.1.jar:dependencies/org.apache.commons.commons-lang3-3.9.jar:dependencies/org.apache.httpcomponents.httpclient-4.5.10.jar:dependencies/org.apache.httpcomponents.httpcore-4.4.12.jar:dependencies/org.apache.logging.log4j.log4j-api-2.13.0.jar:dependencies/org.apache.logging.log4j.log4j-core-2.13.0.jar:dependencies/org.apache.logging.log4j.log4j-slf4j-impl-2.13.0.jar:dependencies/org.jetbrains.annotations-13.0.jar:dependencies/org.jetbrains.intellij.deps.trove4j-1.0.20181211.jar:dependencies/org.jetbrains.kotlin.kotlin-compiler-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-daemon-client-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-reflect-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-script-runtime-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-script-util-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-common-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-compiler-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-compiler-impl-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-jvm-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-scripting-jvm-host-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-common-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-jdk7-1.3.61.jar:dependencies/org.jetbrains.kotlin.kotlin-stdlib-jdk8-1.3.61.jar:dependencies/org.jetbrains.kotlinx.kotlinx-coroutines-core-1.2.1.jar:dependencies/org.ow2.asm.asm-5.0.4.jar:dependencies/org.slf4j.slf4j-api-1.7.29.jar:dependencies/software.amazon.ion.ion-java-1.0.2.jar
    - org.apache.camel.k.main.Application
    command:
    - java
```
