### ISSUE TITLE
Drop OpenShift 3 support

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#1550]
Camel K CRDs currently uses `apiextensions.k8s.io/v1beta1`, which will be removed in a future release of Kubernetes (currently planned for 1.22): kubernetes/kubernetes#82022.

Work has been done in #1514 to migrate to `apiextensions.k8s.io/v1`. However, OpenShift 3.11 is based on Kubernetes 1.11 that does not serve `apiextensions.k8s.io/v1`. It implies it won't be possible to support both Kubernetes 1.22+ and OpenShift 3.11 generally.

OpenShift 3.11 is still used in our CI, with GitHub Actions and Travis, to run integration tests on OpenShift. Before dropping support for OpenShift 3, a solution has to be found to migrate CI to run integration tests on OpenShift 4.

[CRC](https://github.com/code-ready/crc) seems the best replacement candidate to setup OpenShift 4. Unfortunately, it relies on virtualisation, and GitHub Actions Linux hosted runners do not support nested virtualisation. Yet it is supported by the macOS runner with https://github.com/actions/virtual-environments/issues/433. After some experiments, it seems not really stable as I faced https://github.com/code-ready/crc/issues/1331. It may be due to the 7GB memory limit set for the GitHub actions runners, which may be a blocker anyway whenever we'll have to run more demanding workload. 

It is unfortunate DIND support has be removed from OpenShift, which is what's used to run vanilla K8s on our CI: https://github.com/openshift/origin/pull/23177.

For reference, the GH Actions workflow used to experiment with CRC:

```yaml
name: CRC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  crc:
    runs-on: macos-latest

    steps:
      - name: Info
        run: |
          df -h
          sysctl hw.memsize
          sw_vers

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CRC
        env:
          PULL_SECRET: ${{ secrets.PULL_SECRET }}
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.11.0/crc-macos-amd64.tar.xz -o crc-macos-amd64.tar.xz
          tar xf crc-macos-amd64.tar.xz
          rm crc-macos-amd64.tar.xz
          cd crc-macos-1.11.0-amd64/

          ./crc setup

          #./crc config set memory 8192
          ./crc config view

          echo $PULL_SECRET > pull.secret
          ./crc start -p pull.secret --log-level debug
          eval $(./crc oc-env)
```
