### ISSUE TITLE
Support for Kamelets

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1567]
Some time ago we have been discussing about introducing the concept of **Kamelet** which in essence is a way to describe a reusable route people can leverage to provide ready-to use functionalities. As example, it will be possible to use a Kamelet to create a [Knative Camel Sources](https://knative.dev/docs/eventing/samples/apache-camel-source/) but also to create a [Kafka Camel Connectors](https://camel.apache.org/camel-kafka-connector/latest/index.html).

### Definition

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: timer
  annotations:
    camel.apache.org/kamelet.icon: timer
spec:
  definition:
    title: "Timer"
    description: "Produces produces periodic events with a custom payload"
    required:
      - message
    properties:
      message:
        title: Message
        description: The message to generate
        type: string
  types:
    out:
      mediaType: application/json
      schema:
        id: text.camel.apache.org
        type: string
  flow:
    from:
      uri: timer:tick
      steps:
        - set-body:
            constant: "Hello {{message}} !!!"
        - to: "log:info"
  dependencies:
    - mvn:org.acme/product/1.0.0
```

The mechanics of materializing the **Kamelet** could be something like:
1. the operator inspects the sources and collect what **Kamelets** are required
2. the operator look-up the **Kamelets** from k8s
3. the operator collects all the dependecies required by the **Kamelets** and add them to the final list of dependecies required by the integration
4. the operator mounts the **Kamelets** as it would do for any other source but in a different location, says `/etc/camel/kamelets.d`
5. the [camel-k-runtime](https://github.com/apache/camel-k-runtime) will load and materialize the **Kamelets** at runtime 

### UX

A **Kamelets** should be consumed as any other component. using the following URI format:
```
kamelet:kameletName[/kameletId][?options]
```

As example:

```java
from("kamelet:timer/myTimer?message=Camel")
    .log("${body}")        
```

The properties required by the **Kamelets** must be resolved in the following order:

1. URI params
2. camel.kamelet.${kameletName}(${kameletId}
3. camel.kamelet.${kameletName}

Using the **Kamelet** example above, the `message` property can then be given:

1. by setting a `URI Param` named `message`
2. by setting the property `camel.kamelet.timer.myTimer.message`
2. by setting the property `camel.kamelet.timer.message`
