### ISSUE TITLE
Camel to Yaml transformation

### ISSUE THREAD

**Issue by doru1004** [apache/camel-k#1581]
I have the following Camel code running with Camel K but I would like to transform this code into Yaml.

```
GsonDataFormat gson = new GsonDataFormat(MyClass.class);
from("timer:clock")
            .setBody().header(Exchange.TIMER_COUNTER)
            .setHeader("CamelHttpMethod", constant("GET"))
            .to("http://some.address")
            .unmarshal(gson)
            .log("${body}")
```

If you can point me to an example that I may have missed or ideally some documentation that outlines the rules for Camel to Yaml transformation, I would be happy to look over them.
In the absence of that I'm afraid I cannot infer how the yaml code might look like so I would require some help to perform this transformation.

**Comment by lburgazzoli** [comment]
Haven't tested but should be something like:

```yaml
- from
    uri: "timer:clock"
  steps:
    - set-body:
        header: "CamelTimerCounter"
    - set-header:
        name: "CamelHttpMethod"
        constant: "GET"
    - to:
        uri: "http://some.address"
    - unmarshal:
        json:
          library: "Gson"
          unmarshal-type-name: MyClass
    - log:
        message: "${body}"
```
