### ISSUE TITLE
review configurations spec

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1680]
As today providing configurations is done by a list of key/value pairs but that may not be very handing for tooling and in general for comprehension:

```yaml
  configuration:
    - type: "proeprty"
      value: "key=value"
    - type: "secret"
      value: "my-secret"
```

Wonder if we should provide a better organization, something like:

```yaml
  configuration:
    - secret:
        name: twitter-directmessage
    - property:
        name: user
        value: my-user
    - property:
        name: password
        valueFrom:
          secretKeyRef:
            name: the-password
            key: password
```

which could give more freedom and would allow to use patterns commonly used in other kubernetes resources like referencing an entry in a secret or configmap
