### ISSUE TITLE
support endpoint-dsl 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1746]
We should support the Endpoint DSL when parsing sources to determine dependencies.

As example, for a route like:

```yaml
- from:
    timer:
      timerName: tick
      period: 5s
```

camel-k is unable to automatically add `camel-timer` among the dependencies.
