### ISSUE TITLE
KameletBinding to broker fails

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1778]
E.g.

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-binding
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  source:
    properties:
      authorizationToken: 'xxx'
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: telegram-source

```

Results in impossibility to create Knative SinkBinding.
