### ISSUE TITLE
Telegram Kamlet sets CloudEvent source attribute to Knative sink

### ISSUE THREAD

**Issue by lance** [apache/camel-k#1813]
Using a simple Telegram Kamlet to receive CloudEvents in a Knative Service results in events that have the CloudEvent `source` attribute set to the Knative sink for the events. 

For example, this Kamlet:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-image-bot-source
spec:
  source:
    properties:
      authorizationToken: "REDACTED"
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: telegram-source
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Broker
      name: default
```

Produces this event:

```
Context Attributes,
  specversion: 1.0
  type: org.apache.camel.event
  source: knative://endpoint/camel-event-display?apiVersion=serving.knative.dev%2Fv1&kind=Service
  id: 049ACF1CAECA405-0000000000000009
  time: 2020-11-17T21:27:46.962Z
  datacontenttype: application/json
Data,
  { ... }
```

Note that the source is pointing to the Knative event display instead of being a URI identifying the context in which the event occurred. https://github.com/cloudevents/spec/blob/v1.0/spec.md#source-1

Also helpful would be to have the `type` be more finely grained. For example, `org.apache.camel.event.kamlet.telegram.telegram-image-bot-source`.
