### ISSUE TITLE
Multiple knative revisions created when integration has multiple spec.configuration items

### ISSUE THREAD

**Issue by kaczyns** [apache/camel-k#1824]
If I have an integration that contains this:
```yaml
spec:
  configuration:
  - type: property
    value: camel.component.kafka.heartbeatIntervalMs=5000
  - type: configmap
    value: scm-config
  - type: configmap
    value: outbound-config
  - type: secret
    value: kafka-secrets
  - type: secret
    value: scm-integrations-ca-keystore
```
note that there are two configmaps and two secrets.  When using the Knative profile, the Knative `Service` that is generated contains volume mounts and volumes for each configmap and secret.  When the camel-k operator reconciles this integration multiple times, the order that the volumes and volume mounts appear in the `Service` is different.  Knative will create a new `Revision` each time the order changes.  Reconcile can happen frequently and it is not unusual to have 50-60 revisions (and therefore also pods) concurrently.  The problem is worse when there are more configmaps and secrets.
