### ISSUE TITLE
Multiple knative revisions created when integration references multiple Knative channels

### ISSUE THREAD

**Issue by kaczyns** [apache/camel-k#1826]
If I have an integration with multiple lines like this:
```
 .to("knative:channel/yyy")
```
I can end up with a Knative service that has an environment variable that looks like this:
```yaml
spec:
  template:
    spec:
      containers:
        env:
        - name: CAMEL_KNATIVE_CONFIGURATION
          value: '{"services":[{"type":"channel","name":"xxx","url":"http://xxx-kn-channel.default.svc.cluster.local","metadata":{"camel.endpoint.kind":"sink","knative.apiVersion":"messaging.knative.dev/v1","knative.kind":"Channel"}},{"type":"channel","name":"yyy","url":"http://yyy-kn-channel.default.svc.cluster.local","metadata":{"camel.endpoint.kind":"sink","knative.apiVersion":"messaging.knative.dev/v1","knative.kind":"Channel"}},{"type":"channel","name":"zzz","url":"http://zzz-kn-channel.default.svc.cluster.local","metadata":{"camel.endpoint.kind":"sink","knative.apiVersion":"messaging.knative.dev/v1","knative.kind":"Channel"}}]}'
```
Each time the camel-k operator reconciles the integration, the `CAMEL_KNATIVE_CONFIGURATION` can be re-generated, with the `services` in a different order.  Knative will create a new `Revision` each time this happens, and each new `Revision` causes a new pod to start.  If there are several different `services` the number of pods starting concurrently can get excessive.

This is similar to #1824 , but not as severe (at least in our testing).
