### ISSUE TITLE
GitHub Packages registry cannot be used as expected

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#1860]
It seems there is a problem with using GitHub Packages as the registry right now. 
https://camel.apache.org/camel-k/latest/installation/registry/github.html

Executing `kamel run` to run an integration builds a kit and uploads it to the registry successfully, but it then always fails at pulling the image from the registry during the pod creation. The root cause appears that Camel-K specifies the image with sha256 digest like `docker.pkg.github.com/tadayosi/myrepo/camel-k-kit-xxxxx@sha256:xxxxx` but GitHub Packages registry doesn't seem to support the method:
https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-docker-for-use-with-github-packages#downloading-an-image
We should probably use `IMAGE_NAME:VERSION` as the image.

**Comment by GerardoGR** [comment]
This seem to be fixed now. I managed to have this working with this configuration:
```yaml
# values.yaml
platform:
  build:
    registry:
      insecure: false
      address: "ghcr.io"
      organization: "<github_organization>" # e.g organization: apache
      secret: "<github_docker_registry_secret_name>" # e.g secret: apache_registry_secret
```
I created the secret like described in [Configuring a DockerHub Registry#Alternative Methods](https://github.com/apache/camel-k/blob/master/docs/modules/ROOT/pages/installation/registry/dockerhub.adoc)
