### ISSUE TITLE
Flaky e2e test (cron-fallback)

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1939]
We need to fix this flaky e2e test:

```
--- FAIL: TestRunCronExample (310.61s)
    --- PASS: TestRunCronExample/cron (127.61s)
    --- PASS: TestRunCronExample/cron-timer (60.37s)
    --- FAIL: TestRunCronExample/cron-fallback (91.99s)
```

It happens often, e.g. https://github.com/apache/camel-k/runs/1747588145?check_suite_focus=true, but disappears after running the CI multiple times.

**Comment by astefanutti** [comment]
Note that I've faced the issue by running the TestRunCronExample e2e test locally as well, so it does not seem environment specific.

**Comment by astefanutti** [comment]
That's a good question 😉.

I've looked at the dependencies and it seems the quartz dependencies are added correctly. It may be an issue with how Quarkus resolve classes...

**Comment by nicolaferraro** [comment]
> That's a good question .
> 
> I've looked at the dependencies and it seems the quartz dependencies are added correctly. It may be an issue with how Quarkus resolve classes...

This works:

```
kamel local run cron-fallback.groovy -d camel-quarkus:quartz -d camel-quarkus:cron
```

So I guess the camel-quarkus:cron dependency is missing for some reason.

**Comment by astefanutti** [comment]
Hum that's what I did and thought too, but IIRC if failed randomly also. Have you tried to run it multiple times?

**Comment by nicolaferraro** [comment]
> Hum that's what I did (adding the extra dependencies, not running it locally) and thought too, but IIRC if failed randomly also. Have you tried to run it multiple times?

No, it seems to work.. at least locally..

**Comment by astefanutti** [comment]
OK, sounds good. It'd better be that. I did my tests quickly as I were bringing CI back on track so I may have overlooked things or forgotten others 😀.

**Comment by nicolaferraro** [comment]
Found it! Catalog contains both:

```
    camel-k-cron:
      groupId: org.apache.camel.k
      artifactId: camel-k-cron
      schemes:
      - id: cron
        http: false
        passive: false
```

And 

```
    camel-quarkus-cron:
      groupId: org.apache.camel.quarkus
      artifactId: camel-quarkus-cron
      schemes:
      - id: cron
        http: false
        passive: false
      javaTypes:
      - org.apache.camel.component.cron.CronComponent
```

So depending on the status of some butterflies, the right component gets loaded.

I think `camel-quarkus-cron` is the right one, the other is part of the cron capability.
Opening issue in the runtime.
