### ISSUE TITLE
kamelet-binding : suport for error handling

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1941]
We should support setting-up an error handler, like:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-text-source-to-kafka
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: telegram-text-source
    properties:
      botToken: the-token-here
  sink:
    ref: 
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  error-handler: 
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: retry-handler
    properties:
      ...    
```
