### ISSUE TITLE
operator: option lo limiti CRs the operator should handle

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1943]
We should be able to restrict what CRs a camel-k operator should handle, as example, we can add a label like `camel.apache.org/operator.id` to each CR: 

```yaml
apiVersion: camel.apache.org/foo
kind: bar
metadat
  labels: 
    camel.apache.org/operator.id: "operator-1"
```

The `operator.id` should also be used to acquire the operator lock.

Note:
- We'd need to amend the kamel commands to eventually take into account such label
- We'd need to introduce a new command to move CR between operators
