### ISSUE TITLE
Ability to have sources for integrations as ConfigMaps

### ISSUE THREAD

**Issue by lancerdima** [apache/camel-k#1951]
### Problem
Currently, sources for Integration CRDs are specified through _content_ property under sources tag
spec:
  sources:
    - name: fileName.java
       content: |
         ** source / bean definition **  

### Suggestion
Add ability to provide sources (especially sources with custom beans) as ConfigMaps. That should promote some modularity and reuse of sources between integrations.

**Comment by lburgazzoli** [comment]
If you set `contentRef: nameOfTheConfigMap`, then the content is taken from the named config map

**Comment by lancerdima** [comment]
Thanks for the hint @lburgazzoli, I've figured out the setup that works.
For future reference, the yaml should look like this.
```
spec:
  flows:
    - from:
        ...
        steps:
          - to: ...
  sources:
    - contentRef: configmapname
      contentKey: MySourceFile.java
      name: MySourceFile.java
```
The corresponding config map is:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapname
data:
  content: |
    **my source code**
```

The only confusion I have is that `contentKey` seems does not have any effect, and I am required to use `content` property in configmap, instead of e.g. `MySourceFile.java`.
If that is expected, issue can be closed.
