### ISSUE TITLE
kamelet-binding: support for processing steps

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2043]
We should provide a way to manipulate exchanges generated by the source before they are processed by the sink, something like:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: steps-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: "Camel"
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: prefix-action
    properties:
      prefix: "Apache"
  sink:
    uri: log:info
```
