### ISSUE TITLE
Dependency autoloading is not working correctly with YAML format

### ISSUE THREAD

**Issue by bouskaJ** [apache/camel-k#2098]
I have the following integration
```
- route:
    id: "yaml"
    from: 
      uri: "cron:tab"
      parameters:
        schedule: "*+*+*+*+?"
    steps:
      - set-header:
          name: "m"
          constant: "string!"
      - set-body:
          simple: "Magic${header.m}"
      - to: 
          uri: "log:info"
          parameters:
            show-all: "false"
``` 
and I am getting 

```
[1] 2021-03-05 07:36:05,734 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.FailedToCreateRouteException: Failed to create route yaml at: >>> To[log:info?show-all=false] <<< in route: Route(yaml)[From[cron:tab?schedule=*+*+*+*+?] -> [SetHeader[... because of No endpoint could be found for: log://info?show-all=false, please check your classpath contains the needed Camel component jar.
```
from the integration log. The `camel-log` dependency is not loaded to the integration classpath.

if you write it in the classic `- from` form (source code follows), dependencies are picked, so I guess it's a problem with the `- route` format.
```
- from: 
    uri: "cron:tab"
    parameters:
      schedule: "*+*+*+*+?"
    steps:
    - set-header:
        name: "m"
        constant: "string!"
    - set-body:
        simple: "Magic${header.m}"
    - to: 
        uri: "log:info"
        parameters:
          show-all: "false"
```
