### ISSUE TITLE
Kamelet using Java DSL

### ISSUE THREAD

**Issue by arthurdm** [apache/camel-k#2117]
The [Kamelet page](https://camel.apache.org/camel-k/latest/kamelets/kamelets.html) outlines various examples with YAML DSL, but all of the integrations I have been writing as using the Java DSL. 

The page says:
> Each Kamelet contains a YAML-based Camel DSL that provides the actual implementation of the connector

So is there a way to write a Kamelet that uses the Java DSL?

**Comment by nicolaferraro** [comment]
The route template part (i.e. the part that can use the property placeholders) in each Kamelet is a YAML flow, but a Kamelet can also hand-off processing to routes written in any of the other supported languages. E.g.

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: java
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  sources:
  - content: |
      // camel-k: language=java

      import org.apache.camel.builder.RouteBuilder;

      public class Source extends RouteBuilder {
        @Override
        public void configure() throws Exception {

            from("direct:java")
              .setBody().exchangeProperty("prop1")
              .log("Prop is ${body}");

        }
      }
    name: Source.java
  definition:
    title: "Example of Kamelet with Java"
    description: "Passes data to Java"
    properties:
      prop1:
        title: Property 1
        description: A property
        type: string
        default: "The value"
  flow:
    # The template is always YAML, but it can pass work to Java
    from:
      uri: timer:tick
      steps:
        - set-property:
            name: "prop1"
            constant: "{{prop1}}"
        - to: "direct:java"
        - to: "kamelet:sink"

```
