### ISSUE TITLE
Allow to configure traits using annotations

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2165]
Configuring traits may be a little bit complex for tooling in particular when configuring a `KameletBinding` where as example, to configure the service binding, one has to rescue the `integration` spec, like:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: my-binding
spec:
  integration:
    traits:
      service-binding:
        configuration:
          serviceBindings:
          - postgres.org:v1alpha1:PostgreSQL
```      

It would much more practical to have options to use annotations that re well known and we can use the json schema for the traits to let tools know what options are available for each trait so you can re-write the example above as:     

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: my-binding
  annotations:
    trait.camel.apache.org/service-binding.bindings=postgres.org:v1alpha1:PostgreSQL
```

/cc @nicolaferraro @astefanutti what do you think ?
