### ISSUE TITLE
Multiple ReplicaSet Race Condition

### ISSUE THREAD

**Issue by mjallday** [apache/camel-k#2188]
We're trying to spin up a camel-k integration and there's some sort of race condition creating replicasets as it's starting. Here's how we're doing this. 

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: processor-mj
  labels:
    tenant: tnt2
  namespace: camel-k
spec:
  serviceAccountName: camel-k
  dependencies: []
  configuration:
    - type: env
      value: AWS_REGION=us-west-2
    - type: env
      value: AWS_REGION2=us-west-2
    - type: env
      value: AWS_REGION3=us-west-2
    - type: env
      value: AWS_REGION4=us-west-2
    - type: env
      value: AWS_REGION5=us-west-2
    - type: env
      value: AWS_REGION6=us-west-2
    - type: env
      value: AWS_REGION7=us-west-2
    - type: env
      value: AWS_REGION8=us-west-2
  replicas: 1
  traits:
    deployment:
      configuration:
        enabled: true
    tracing:
      configuration:
        enabled: true
        endpoint: http://observability.local:14268/api/traces
        service-name: big-file-tnt2
    knative:
      configuration:
        enabled: false
    knative-service:
      configuration:
        enabled: false
        minScale: 1
        maxScale: 10
        class: kpa.autoscaling.knative.dev
    knative-eventing:
      configuration:
        enabled: false
  sources:
    - content: |
        
        beans {
        }

      name: process.groovy
status: { }
```

which we're applying with this command `kubectl -n camel-k apply -f config.yaml`

when this happens I see the integration created successfully

```
kubectl -n camel-k get it/processor-mj
NAME           PHASE     KIT                        REPLICAS
processor-mj   Running   kit-c1iph3cfsqtehrtd8eqg   0
```

and the deployment looks like this

```
kubectl -n camel-k describe deployment/processor-mj
Name:                   processor-mj
Namespace:              camel-k
CreationTimestamp:      Fri, 02 Apr 2021 15:04:05 +1300
Labels:                 camel.apache.org/generation=2
                        camel.apache.org/integration=processor-mj
Annotations:            deployment.kubernetes.io/revision: 53
Selector:               camel.apache.org/integration=processor-mj
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           camel.apache.org/integration=processor-mj
  Service Account:  camel-k
...
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  processor-mj-6c66666f47 (1/1 replicas created)
NewReplicaSet:   <none>
Events:
  Type    Reason             Age                  From                   Message
  ----    ------             ----                 ----                   -------
  Normal  ScalingReplicaSet  8m8s                 deployment-controller  Scaled up replica set processor-mj-74b4ffbc7c to 1
  Normal  ScalingReplicaSet  8m5s (x2 over 8m6s)  deployment-controller  Scaled up replica set processor-mj-7f9758bb7f to 1
  Normal  ScalingReplicaSet  8m5s (x2 over 8m6s)  deployment-controller  Scaled down replica set processor-mj-7f9758bb7f to 0
  Normal  ScalingReplicaSet  8m4s (x2 over 8m8s)  deployment-controller  Scaled up replica set processor-mj-85cf4dfb45 to 1
  Normal  ScalingReplicaSet  8m4s (x2 over 8m6s)  deployment-controller  Scaled down replica set processor-mj-85cf4dfb45 to 0
  Normal  ScalingReplicaSet  8m3s (x2 over 8m3s)  deployment-controller  (combined from similar events): Scaled down replica set processor-mj-784db95457 to 0
  Normal  ScalingReplicaSet  8m2s (x3 over 8m5s)  deployment-controller  Scaled up replica set processor-mj-6c66666f47 to 1
  Normal  ScalingReplicaSet  8m2s (x3 over 8m5s)  deployment-controller  Scaled down replica set processor-mj-6c66666f47 to 0
  Normal  ScalingReplicaSet  8m2s                 deployment-controller  Scaled up replica set processor-mj-784db95457 to 1
  Normal  ScalingReplicaSet  8m1s (x3 over 8m6s)  deployment-controller  Scaled up replica set processor-mj-7469ff45c7 to 1
  Normal  ScalingReplicaSet  8m1s (x3 over 8m5s)  deployment-controller  Scaled down replica set processor-mj-7469ff45c7 to 0
  Normal  ScalingReplicaSet  8m1s                 deployment-controller  Scaled down replica set processor-mj-784db95457 to 0
```

and then there's a ton of replica sets created

```
processor-mj-6c66666f47                 1         1         1       10m
processor-mj-7469ff45c7                 0         0         0       10m
processor-mj-74b4ffbc7c                 0         0         0       10m
processor-mj-784db95457                 0         0         0       10m
processor-mj-79f7b567c9                 0         0         0       10m
processor-mj-7f9758bb7f                 0         0         0       10m
processor-mj-85cf4dfb45                 0         0         0       10m
processor-mj-85ddb99755                 0         0         0       10m
```

Is this expected behavior? The integration file doesn't appear to let us control how scaling, I'm looking for it to create a single replicaset with a single pod or if i scale it to maintain a single replicaset with multiple pods but it seems to spam replicasets for a while before setting down. 

If i look at the replicaset i see a bunch of scaling events but i'm unsure why

`kubectl -n camel-k describe rs/processor-mj-7f9758bb7f`
```
Name:           processor-mj-7f9758bb7f
Namespace:      camel-k
Selector:       camel.apache.org/integration=processor-mj,pod-template-hash=7f9758bb7f
Labels:         camel.apache.org/integration=processor-mj
                pod-template-hash=7f9758bb7f
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 42
                deployment.kubernetes.io/revision-history: 6,9,25,30,36,40
Controlled By:  Deployment/processor-mj
Replicas:       0 current / 0 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           camel.apache.org/integration=processor-mj
                    pod-template-hash=7f9758bb7f
  Service Account:  camel-k
...
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  13m   replicaset-controller  Created pod: processor-mj-7f9758bb7f-d62vz
  Normal  SuccessfulDelete  13m   replicaset-controller  Deleted pod: processor-mj-7f9758bb7f-d62vz
  Normal  SuccessfulCreate  13m   replicaset-controller  Created pod: processor-mj-7f9758bb7f-cgqdw
  Normal  SuccessfulDelete  13m   replicaset-controller  Deleted pod: processor-mj-7f9758bb7f-cgqdw
  Normal  SuccessfulCreate  13m   replicaset-controller  Created pod: processor-mj-7f9758bb7f-vckpf
  Normal  SuccessfulDelete  13m   replicaset-controller  Deleted pod: processor-mj-7f9758bb7f-vckpf
  Normal  SuccessfulCreate  13m   replicaset-controller  Created pod: processor-mj-7f9758bb7f-cqsrc
  Normal  SuccessfulDelete  13m   replicaset-controller  Deleted pod: processor-mj-7f9758bb7f-cqsrc
  Normal  SuccessfulCreate  13m   replicaset-controller  Created pod: processor-mj-7f9758bb7f-9zttb
  Normal  SuccessfulDelete  13m   replicaset-controller  Deleted pod: processor-mj-7f9758bb7f-9zttb
  Normal  SuccessfulCreate  13m   replicaset-controller  Created pod: processor-mj-7f9758bb7f-7ssl6
  Normal  SuccessfulDelete  13m   replicaset-controller  Deleted pod: processor-mj-7f9758bb7f-7ssl6
  Normal  SuccessfulCreate  13m   replicaset-controller  Created pod: processor-mj-7f9758bb7f-8m779
  Normal  SuccessfulDelete  13m   replicaset-controller  Deleted pod: processor-mj-7f9758bb7f-8m779
```

any hints on how we can stop this behavior?

**Comment by mjallday** [comment]
this is camel-k:1.3.1

**Comment by mjallday** [comment]
The behavior goes away when we remove the configuration block which contains

```yaml
  configuration:
    - type: env
      value: AWS_REGION=us-west-2
```

for the integration object. it creates one replicaset for each configuration entry. 

is there a better way to pass environment variables?
