### ISSUE TITLE
Scaling integrations removes Kamelet ConfigMaps

### ISSUE THREAD

**Issue by barmyard** [apache/camel-k#2218]
I want to pause and start Integrations by scaling the replicas to 0 and 1. When scaling integrations using `kubectl scale`, Kamelet ConfigMaps are removed. This breaks the integration.

`timed-logger.yaml` Integration:
```yaml
- from:
    uri: "timer:tick?period=15s"
    steps:
      - to: "kamelet:logger?message=hello"
```

`logger` Kamelet:
```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: logger
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "Logger"
    description: |-
      Logger
    required:
      - message
    properties:
      message:
        title: Message
        description: Message
        type: string
  flow:
    from:
      uri: "kamelet:source"
      steps:
        - log: "{{message}}"
```

Steps to reproduce:
1. `kamel run timed-logger.yaml`.

ConfigMaps 
```
timed-logger-kamelet-logger-flow 
timed-logger-source-000
timed-logger-application-properties
```
2.  `kubectl scale it timed-logger --replicas 0`  

ConfigMaps:
```
timed-logger-source-000
timed-logger-application-properties  
```
(`timed-logger-kamelet-logger-flow ` is deleted)
Scaling the integration to 2 results in the same behavior, the Kamelet ConfigMap is removed.

3.  `kubectl scale it timed-logger --replicas 1`
ConfigMaps:
```
timed-logger-source-000
timed-logger-application-properties  
```
Log of the `camel-k-operator`:
```
{"level":"info","ts":1618387208.49495,"logger":"camel-k.trait","msg":"Apply trait: init"}
{"level":"info","ts":1618387208.4978032,"logger":"camel-k.trait","msg":"Apply trait: camel"}
{"level":"error","ts":1618387208.5083137,"logger":"controller","msg":"Reconciler error","controller":"integration-controller","name":"timed-logger","namespace":"default","error":"error during trait customization: ConfigMap \"timed-logger-kamelet-logger-flow\" not found",
```

EDIT: as requested, the `application.properties` of the integration:
camel.k.sources[0].language=yaml
camel.k.sources[1].location=file:/etc/camel/sources/i-source-001/logger.yaml
camel.k.sources[1].name=logger
camel.k.sources[1].property-names[0]=message
camel.k.sources[1].type=template
camel.k.sources[1].language=yaml
camel.k.sources[0].location=file:/etc/camel/sources/i-source-000/camel-k-embedded-flow.yaml
camel.k.sources[0].name=camel-k-embedded-flow
```

```
