### ISSUE TITLE
No possibility to disable compression while executing `kamel run`

### ISSUE THREAD

**Issue by NickEm** [apache/camel-k#2227]
Hi team,
We would like to generate our camel integrations using `kamel` utility but we see no way of disabling compression of the resources. No matter what you are running:
```
kamel -n camel-k run Route.java --resource key-file.p12 -o yaml
```
```
kamel -n camel-k run Route.java --compression=false --resource key-file.p12 -o yaml
```
As output you always get:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  namespace: camel-k
spec:
  resources:
  - compression: true
    content:  ....
    name: key-file.p12
    type: data
```

Environment:
* camel-k-1.3.2
* Mac OS Big Sur
