### ISSUE TITLE
Traits to configure the container image and location fo the sources

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2232]
We should support traits to configure what container image an integration should use to run integrations as well as where as where sources are located.

As example, it would be nice to be able to define a `KameletBinding` like:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: my-binding
  annotations:
    trait.camel.apache.org/integration.image: "acme/image:1.0"
    trait.camel.apache.org/integration.sources-mode: "embedded"
```

Where:
- the `KameletBinding` should be executed using the the container image defined by the `trait.camel.apache.org/integration.image` annotation (no build should be performed)
- the annotation `trait.camel.apache.org/integration.sources-mode: "embedded"` instruct the operator that any source are embedded in the container image on a specific location, the operator still need to configure them for the runtime to be able to read but does not need to look them up in k8s.

Relates to: https://github.com/apache/camel-k/issues/2165

**Comment by lburgazzoli** [comment]
Thinking a little bit about this:

- We may not need to add an `integration.sources-mode` but we could probably add an option to set the location of the source on to the source definition, like:

```yaml
spec:
    sources:
    - location: "{{env.CAMEL_K_SOURCES}}/routes.yaml"
```

- for what concern the container images, as we have a `pod` trait now so we may add an additional option there, like:

```
kamel run -t pod.integration-image=foo/bar:1.0.0
```

- for what concern the `kamelets` we may add an option to the related trait to list embedded kamelets that the operator should not attempt to look up from k8s

```
kamel run -t kamelets.embedded=foo,bar,baz
```
