### ISSUE TITLE
kamelets: support for kamelet local beans

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2271]
[Route Template local beans ](https://issues.apache.org/jira/browse/CAMEL-16394) is approaching and we need to define how we can leverage such functionality in camel-k and in the kamelets definition.

The current layout for kamelets is:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: telegram-text-source e"
spec:
  ...
  flow: 
    from:
      uri: direct:start
      steps:
         ...
```

I'd propose to replaces `flow` with `template` so it would looks like:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: telegram-text-source e"
spec:
  ...
  template: 
    beans:
      - name: myBean
        type: com.acme.MyBean
        properties:
         foo: "bar"
    from:
      uri: direct:start
      steps:
        - process: "myBean"
```

NOTE:
- we should keep `flow` for backward compatibility but to create template local `beans` one has to use `template` keyword.
- the new `template` keyword can be provided by the Camel YAML DSL so we can reduce the custom code we have to maintain for camel-k.

The code generated by the camel-k operator should then be:

```yaml
- template: 
    beans:
      - name: myBean
        type: com.acme.MyBean
        properties:
         foo: "bar"
    from:
      uri: direct:start
      steps:
        - process: "myBean"
```
