### ISSUE TITLE
kamelet binding: make it possible to use normalized name 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2296]
As we have a normalized way do reference k8s resources, it should be possible to use it to reference a source/sink/step, i.e.:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-text-source-to-channel
spec:
  source: 
    ref: "camel.apache.org/v1alpha1:Kamelet:telegram-text-source"
    properties:
      botToken: the-token-here
  sink: 
    ref: "messaging.knative.dev/v1:InMemoryChannel:messages"
```
