### ISSUE TITLE
kamelets: add condition to report when an integration is stuck waiting for them 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2331]
I have an integration like:

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
   name: test
spec:
  flows:
  - from:
      steps:
      - to: kamelet:log-sink/sink
      uri: kamelet:timer-source/source
  profile: Knative
status:
  conditions:
  - firstTruthyTime: "2021-05-26T15:17:07Z"
    lastTransitionTime: "2021-05-26T15:17:07Z"
    lastUpdateTime: "2021-05-26T15:17:07Z"
    message: openshift-operators/camel-k
    reason: IntegrationPlatformAvailable
    status: "True"
    type: IntegrationPlatformAvailable
  dependencies:
  - mvn:org.apache.camel.k:camel-k-runtime
  digest: vyzjts6ASueTqZGTCWALa2NPh4bJkZJuqw2peqtLaTzU
  phase: Initialization
  platform: camel-k
  profile: Knative
  runtimeProvider: quarkus
  runtimeVersion: 1.7.0
```

The integration stuck in `Initialization` phase because the required kamelets are not found but it would be nice if such information would be reported among the conditions

```yaml
status:
  conditions:
  - message: "kamelet log-sink not found"
    reason: KameletNotFound
    status: "False"
    type: RequiredResourceAvailable
  - message: "kamelet timer-source not found"
    reason: KameletNotFound
    status: "False"
    type: RequiredResourceAvailable
```
