### ISSUE TITLE
Can't set multiline properties in Kamelet bindings

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#2361]
One example is: https://github.com/apache/camel-kamelets/pull/330/files#diff-c81f389241ecccbb03f18791698351f85f8f668f909a55b7291552aafd6b3a9bR23

Where I wanted to provide a cleaner way to provide a schema, like:

```yaml
# ...
schema: |-
  {
    "type": "record",
    "namespace": "com.example",
    ...
  }
```

But apparently when the operator maps KameletBinding property values to the application.properties file it does not encode newline characters (and other special chars).
