### ISSUE TITLE
kamelet binding: use the Kamelet EIP for steps

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2370]
Assuming we have a Kamelet Binding, as today we compose the yaml definition as:

```yaml
- from:
    uri: kamelet:from
    steps:
    - to: "kamelet:action-1"
    - to: "kamelet:action-2"
    - to: "kamelet:to"
```

because actions may be complex, we should use something like:

```yaml
- from:
    uri: kamelet:from
    steps:
    - kamelet:
        name: action-1
    - kamelet:
        name: action-2
    - kamelet:
        name: to
```
