### ISSUE TITLE
Kamelets: configuration does not seem to cascade to the integration

### ISSUE THREAD

**Issue by orpiske** [apache/camel-k#2396]
I have a kamelet binding defined as below. It includes a section for configuring a property on the integration but it does not seem to cascade to the integration: 

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: jms-source-binding
spec:
  integration:
    configuration:
      - type: property
        value: "quarkus.log.level=DEBUG"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: jms-source
    properties:
      destinationName: person
      brokerURL: "tcp://redacted:port"
  sink:
    uri: "log:info"
```

Alternatively I tried to use: 

```
configuration:
      - type: trait
        value: "logging.level=DEBUG"
``` 

However, it also does not cascade.

**Comment by orpiske** [comment]
The expectation, here, would be the code to display the debug level messages ... but it does not seem to be the case.

**Comment by johnpoth** [comment]
Wanted to do the same thing, as an alternative you can do:
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: jms-source-binding
spec:
  integration:
    traits:
      logging:
        configuration:
          level: DEBUG
```

thanks !
