### ISSUE TITLE
Parameters in YAML DSL are not recognized

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#2441]
And this makes traits such as cron and knative to not work as expected, because the operator skips them.

So, e.g. this works:

```
- from:
    uri: "cron:tab?schedule=*+*+*+*+?"
# ...
```

But this doesn't:

```
- from:
    uri: "cron:tab"
    parameters:
      schedule: "* * * * ?"
# ...
```

Even if they are equivalent at runtime level, they are not at operator side.
