### ISSUE TITLE
If the pod is in CrashLoopBackOff, the phase is reported as Running

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2445]
I have the following scenarion:

```
➜ k tree klb cd208ccf823b044089c48669c1ec1d6e4
NAMESPACE  NAME                                                                    READY  REASON              AGE 
default    KameletBinding/cd208ccf823b044089c48669c1ec1d6e4                        True                       143m
default    └─Integration/cd208ccf823b044089c48669c1ec1d6e4                         False  ReplicaSetNotReady  143m
default      ├─ConfigMap/cd208ccf823b044089c48669c1ec1d6e4-application-properties  -                          143m
default      ├─ConfigMap/cd208ccf823b044089c48669c1ec1d6e4-source-000              -                          143m
default      ├─Deployment/cd208ccf823b044089c48669c1ec1d6e4                        -                          143m
default      │ └─ReplicaSet/cd208ccf823b044089c48669c1ec1d6e4-585565bdf5           -                          143m
default      │   └─Pod/cd208ccf823b044089c48669c1ec1d6e4-585565bdf5-nptc7          False  ContainersNotReady  143m
default      └─IntegrationKit/kit-cd208ccf823b044089c48669c1ec1d6e4                -                          143m
```

so the POD is not ready for an internal error but the phase of the integration is still reported as `Running` and the kamelet binding as `Ready`:

```
➜ k get klb cd208ccf823b044089c48669c1ec1d6e4
NAME                                PHASE
cd208ccf823b044089c48669c1ec1d6e4   Ready
➜ k get it cd208ccf823b044089c48669c1ec1d6e4
NAME                                PHASE     KIT   REPLICAS
cd208ccf823b044089c48669c1ec1d6e4   Running         1
➜ k get pods | grep cd208ccf823b044089c48669c1ec1d6e4
cd208ccf823b044089c48669c1ec1d6e4-585565bdf5-nptc7   0/1     CrashLoopBackOff   32         141m
```

I wonder if we can ave a better way to report that the pod is not running.
By looking at the integration resource only, one may mistakenly think the integration is running but it is not.

**Comment by lburgazzoli** [comment]
Additional info:

The _Integration_ has a condition where type=ready and status=false

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: cd208ccf823b044089c48669c1ec1d6e4
status:
  conditions:
  - lastTransitionTime: "2021-06-24T20:49:04Z"
    lastUpdateTime: "2021-06-24T20:49:04Z"
    reason: ReplicaSetNotReady
    status: "False"
    type: Ready
  phase: Running
```

But the parent _KameletBinding_, does not reflect such status:

````yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: cd208ccf823b044089c48669c1ec1d6e4
spec:
status:
  conditions:
  - lastTransitionTime: "2021-06-24T18:07:56Z"
    lastUpdateTime: "2021-06-24T18:07:56Z"
    status: "True"
    type: Ready
  phase: Ready
```
