### ISSUE TITLE
Oddity in channel name

### ISSUE THREAD

**Issue by pilhuhn** [apache/camel-k#2468]
I have this route definition https://gist.github.com/pilhuhn/97cf0bfaec2d3d5a78ccaa13ee31581f and when doing `kamel run` I get the following error:
I am pulling in the dependency via jitpack

`[1] 2021-06-30 07:06:24,289 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: Unable to find a resource definition for channel/sink/return-channel`

Notice the `sink` part, that I did not put in.

When I try the following

```
- from:
    uri: "timer:clock?period=3000"
    steps:
      - set-body:
          constant: "Hello World from Camel K"
      - to:
          uri: "knative:channel/return-channel"
      - log:
          message: "Send message"
```

and deploy it, I do not get the error, even if the to/uri is the same
