### ISSUE TITLE
ImagePullBackOff when node failed

### ISSUE THREAD

**Issue by stepan111** [apache/camel-k#2485]
Hello,

First of all thanks for great project !

I am running camel-k integration on GKE cluster with preemptible nodes.(nodes recreated daily) 

Currently I have to delete and apply integration  each time k8s migrate pod to other node because of `ImagePullBackOff` error:
```
$ k get po -o wide
NAME                                READY   STATUS             RESTARTS   AGE    IP              NODE                                                  NOMINATED NODE   READINESS GATES
camel-k-operator-6f848d7b5c-kgrrp   0/2     Shutdown           0          30h    <none>          gke-sandbox-blue-sandbox-blue-default-f0ed42c1-3p5d   <none>           <none>
camel-k-operator-6f848d7b5c-wjd9n   2/2     Running            2          9h     10.100.18.144   gke-sandbox-blue-sandbox-blue-default-ee794f56-16s7   <none>           <none>
gmail-5d5b644958-hx9gm              1/2     ImagePullBackOff   0          5m1s   10.100.20.131   gke-sandbox-blue-sandbox-blue-default-f0ed42c1-3p5d   <none>           <none>
gmail-5d5b644958-sb2xt              0/2     Shutdown           0          25h    <none>          gke-sandbox-blue-sandbox-blue-default-ee794f56-16s7   <none>           <none>

```
I've added next triats to integration:
```
traits:                                                                                                                               
    pull-secret:                                                                                                                        
      configuration:                                                                                                                    
        auto: false                                                                                                                     
        enabled: true                                                                                                                   
        secretName: registry
```
But it don't take affect on deployment made for this integration.

```
$ k get deploy/integration | grep imagePullSecret
$ 

```
Operator version:
```
$ k get deploy/camel-k-operator -o jsonpath={.spec.template.spec.containers..image}        
docker.io/apache/camel-k:1.4.0
```
