### ISSUE TITLE
Integration / KameletBinding: include information about the running pods/deployments

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2504]
When inspecting a POD, information about individual containers are reported, like:

```yaml
  containerStatuses:
  - containerID: cri-o://15fa60d7f2b0f3a4a7e1a01266598756878ced119ae83d0426156bd27433eb36
    image: ...
    imageID: ...
    lastState: {}
    name: integration
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-14T08:12:22Z"
```

We should optional report similar information in an Integration and KameletBinding.

```yaml
  instances:
    - resource: 
        apiVersion: v1
        kind: Pod
        name: MyPod
      state:
        running:   
          startedAt: "2021-07-14T08:12:22Z"
      conditions:
        - ...
```

A new trait may be introduced to control such behavior, like

```
    reporting.instances = true|false
    reporting.instances-conditions = true|false
```
