### ISSUE TITLE
kamelet binding : camel controller fail reconcile the kafka sink resource.

### ISSUE THREAD

**Issue by fredcoq** [apache/camel-k#2528]
**What is observed:**

Strimzi Kafka cluster and Camel controller are installed and healthy.
KafkaTopic: my-topic is created an healthy.
The KameletBinding minio-resource is submitted to the cluster.

The minio-source-binding is created but stay in pending state.

- Kubernetes ressource satus 
```Events:
  Type     Reason        Age                   From                                Message
  ----     ------        ----                  ----                                -------
  Warning  KameletError  6m50s (x20 over 45m)  camel-k-kamelet-binding-controller  Cannot reconcile KameletBinding minio-source-binding: could not determine sink URI: the server could not find the requested resource (get kafkas.kafka.strimzi.io my-cluster)
```

- camel-controler pod log:
```{"level":"error","ts":1627235132.8817902,"logger":"controller-runtime.manager.controller.kamelet-binding-controller","msg":"Reconciler error","name":"minio-source-binding","namespace":"kafka","error":"could not determine sink URI: the server could not find the requested resource (get kafkas.kafka.strimzi.io my-cluster)","errorVerbose":"the server could not find the requested resource (get kafkas.kafka.strimzi.io my-cluster)\ncould not determine sink URI ....```

**To reproduce :**

Software & releases
* Minikube Kubernetes 1.20.2
* Private docker  local registry.
* Kafka 2.8.0 kafka:my-cluster installed with strimzi operator in namespace kafka (plain text and no authentication)
* Camel-k operator 1.5.0 installed with helm in namespace kafka.

**What is expected:**
Have the minio-source-binding resource created and in healthy state.

As I was suspecting some authorizations issueI, I  modified the camel controler RBAC  to a cluster role without any improvments.

-------------------

**Additional set-up infoamtions.**

Camel-k installation configuration
```
helm install \
  --namespace kafka \
  --set platform.build.registry.address=192.168.1.40:45000 \
  --set platform.build.registry.insecure=true \
  --set platform.profile=kubernetes \
  --set plateform.cluster=kubernetes \
  --generate-name \
  camel-k/camel-k
```
KameletBinding  spec.
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: minio-source-binding
  namespace: kafka
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: minio-source
    properties:
      accessKey: -----------
      bucketName: test
      endpoint: "http://minio2.kafka:9000"
      secretKey: ----------
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
```
KafkaTopic spec.
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```
