### ISSUE TITLE
trsit logging.json: "false" does not have effect if the integration includes quarkus-logging-json

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2539]
I have an integration configured to use a pre-built container image and where I have configure the logging trait to disabled json logging:

```yaml
annotations:
    trait.camel.apache.org/container.image: com.acme/foo:1.0
    trait.camel.apache.org/jvm.enabled: "false"
    trait.camel.apache.org/logging.json: "false"
```

As the container image contains quarkus-logging-json, the trait `logging.json: "false"` does not have effect since the related env variable [is set](https://github.com/apache/camel-k/blob/main/pkg/trait/logging.go#L88) only if the value is `true` .

We should always set `QUARKUS_LOG_CONSOLE_JSON` and we should add `quarkus-logging-json` among the transitive dependencies of camel-k-runtiome
