### ISSUE TITLE
controller: panic on nil annotation

### ISSUE THREAD

**Issue by Abirdcfly** [apache/camel-k#2556]
````yaml
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  annotations:
    meta.helm.sh/release-name: camel-k
    meta.helm.sh/release-namespace: camel-k
  generation: 1
  labels:
    app: camel-k
    app.kubernetes.io/instance: camel-k
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: camel-k
    app.kubernetes.io/version: 1.5.0
    helm.sh/chart: camel-k-0.7.0
  name: camel-k
  namespace: camel-k
spec:
  build:
    baseImage: 192.168.1.111/faas/adoptopenjdk/openjdk11:slim
    buildStrategy: pod
    kanikoBuildCache: true
    publishStrategy: Kaniko
    registry:
      address: 192.168.1.111/faas
      secret: user-1-registrysecret
  cluster: ""
  configuration:
  - type: repository
    value: http://192.168.2.120:7777/repository/tenxcloud-group@id=apache@name=nexus@mirrorOf=central
status:
  build:
    baseImage: 192.168.1.111/faas/adoptopenjdk/openjdk11:slim
    buildStrategy: pod
    kanikoBuildCache: true
    maven:
      localRepository: /tmp/artifacts/m2
      settings:
        configMapKeyRef:
          key: settings.xml
          name: camel-k-maven-settings
    persistentVolumeClaim: camel-k
    publishStrategy: Kaniko
    registry:
      address: 192.168.1.111/faas
      secret: user-1-registrysecret
    runtimeVersion: 1.8.0
    timeout: 5m0s
  cluster: Kubernetes
  configuration:
  - type: repository
    value: http://192.168.2.120:7777/repository/tenxcloud-group@id=apache@name=nexus@mirrorOf=central
  kamelet:
    repositories:
    - uri: none
  phase: Ready
  version: 1.5.0
````

the controller panic log
````
{"level":"error","ts":1628487670.2920237,"logger":"cmd","msg":"Observed a panic: \"assignment to entry in nil map\" (assignment to entry in nil map)\ngoroutine 759 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic(0x213dbe0, 0x27bb530)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x89\npanic(0x213dbe0, 0x27bb530)\n\truntime/panic.go:969 +0x1b9\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).addTimeoutAnnotation.func1(0xc001483000)\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:227 +0x94\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).patchPod(0xc001157350, 0x2840720, 0xc001156d80, 0xc001482000, 0xc0012ab6e0, 0x6110bf00, 0xc0012ab700)\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:242 +0x4a\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).addTimeoutAnnotation(0xc001157350, 0x2840720, 0xc001156d80, 0xc001482000, 0xc03c4ddd91643162, 0x5a028030b, 0x3833240, 0x0, 0x1)\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:226 +0xf0\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).Handle(0xc001157350, 0x2840720, 0xc001156d80, 0xc000a54e00, 0xc0012aba68, 0x1, 0x1)\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:100 +0x4c5\ngithub.com/apache/camel-k/pkg/controller/build.(*reconcileBuild).Reconcile(0xc000758680, 0x2840720, 0xc001156d80, 0xc0010c6789, 0x7, 0xc0010a1560, 0x18, 0xc0007cc3c0, 0xc0007cc3c0, 0x27ef8a0, ...)\n\tgithub.com/apache/camel-k/pkg/controller/build/build_controller.go:224 +0xa2a\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile(0xc0007586c0, 0x2840720, 0xc001156d80, 0xc0010c6789, 0x7, 0xc0010a1560, 0x18, 0xc001156d80, 0x40a43f, 0xc00003a000, ...)\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71 +0xd9\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008a4460, 0x2840660, 0xc000a4e8c0, 0x21efca0, 0xc00037d320)\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x317\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008a4460, 0x2840660, 0xc000a4e8c0, 0xc0007a9600)\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x2840660, 0xc000a4e8c0)\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007a9750)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012abf50, 0x27edea0, 0xc00114c750, 0xc000a4e801, 0xc0007d54a0)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007a9750, 0x3b9aca00, 0x0, 0x1, 0xc0007d54a0)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x2840660, 0xc000a4e8c0, 0xc000b2f890, 0x3b9aca00, 0x0, 0x1)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x2840660, 0xc000a4e8c0, 0xc000b2f890, 0x3b9aca00)\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x45e\n","stacktrace":"k8s.io/klog/v2.(*loggingT).output\n\tk8s.io/klog/v2@v2.8.0/klog.go:914\nk8s.io/klog/v2.(*loggingT).printf\n\tk8s.io/klog/v2@v2.8.0/klog.go:751\nk8s.io/klog/v2.Errorf\n\tk8s.io/klog/v2@v2.8.0/klog.go:1463\nk8s.io/apimachinery/pkg/util/runtime.logPanic\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:78\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash\n\tk8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48\nruntime.gopanic\n\truntime/panic.go:969\nruntime.mapassign_faststr\n\truntime/map_faststr.go:204\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).addTimeoutAnnotation.func1\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:227\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).patchPod\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:242\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).addTimeoutAnnotation\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:226\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_pod.go:100\ngithub.com/apache/camel-k/pkg/controller/build.(*reconcileBuild).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/build/build_controller.go:224\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 759 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x213dbe0, 0x27bb530)
        runtime/panic.go:969 +0x1b9
github.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).addTimeoutAnnotation.func1(0xc001483000)
        github.com/apache/camel-k/pkg/controller/build/monitor_pod.go:227 +0x94
github.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).patchPod(0xc001157350, 0x2840720, 0xc001156d80, 0xc001482000, 0xc0012ab6e0, 0x6110bf00, 0xc0012ab700)
        github.com/apache/camel-k/pkg/controller/build/monitor_pod.go:242 +0x4a
github.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).addTimeoutAnnotation(0xc001157350, 0x2840720, 0xc001156d80, 0xc001482000, 0xc03c4ddd91643162, 0x5a028030b, 0x3833240, 0x0, 0x1)
        github.com/apache/camel-k/pkg/controller/build/monitor_pod.go:226 +0xf0
github.com/apache/camel-k/pkg/controller/build.(*monitorPodAction).Handle(0xc001157350, 0x2840720, 0xc001156d80, 0xc000a54e00, 0xc0012aba68, 0x1, 0x1)
        github.com/apache/camel-k/pkg/controller/build/monitor_pod.go:100 +0x4c5
github.com/apache/camel-k/pkg/controller/build.(*reconcileBuild).Reconcile(0xc000758680, 0x2840720, 0xc001156d80, 0xc0010c6789, 0x7, 0xc0010a1560, 0x18, 0xc0007cc3c0, 0xc0007cc3c0, 0x27ef8a0, ...)
        github.com/apache/camel-k/pkg/controller/build/build_controller.go:224 +0xa2a
github.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile(0xc0007586c0, 0x2840720, 0xc001156d80, 0xc0010c6789, 0x7, 0xc0010a1560, 0x18, 0xc001156d80, 0x40a43f, 0xc00003a000, ...)
        github.com/apache/camel-k/pkg/util/monitoring/controller.go:71 +0xd9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008a4460, 0x2840660, 0xc000a4e8c0, 0x21efca0, 0xc00037d320)
        sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008a4460, 0x2840660, 0xc000a4e8c0, 0xc0007a9600)
        sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x2840660, 0xc000a4e8c0)
        sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007a9750)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012abf50, 0x27edea0, 0xc00114c750, 0xc000a4e801, 0xc0007d54a0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007a9750, 0x3b9aca00, 0x0, 0x1, 0xc0007d54a0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x2840660, 0xc000a4e8c0, 0xc000b2f890, 0x3b9aca00, 0x0, 0x1)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x2840660, 0xc000a4e8c0, 0xc000b2f890, 0x3b9aca00)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x45e
````
I will add a bugfix later.
