### ISSUE TITLE
Kamelet: default KameletBindings configuration settings

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#2558]
When we use a `Kamelet`, we may be in the situation to apply certain configuration to the `KameletBinding` in order to properly use it. For instance, when we use the [`predicate-filter-action`](https://github.com/apache/camel-kamelets/blob/main/predicate-filter-action.kamelet.yaml) we need to apply some build time configuration such as:
```
    spec:
        integration:
         traits:
           builder:
             configuration:
               properties:
                 - "quarkus.arc.unremovable-types=com.fasterxml.jackson.databind.ObjectMapper"
```
I am wondering if we should include some mechanism to let all KameletBindings using a Kamelet to inherit some configuration (ie, traits) needed by the Kamelet.
