### ISSUE TITLE
Kamel bind produces incomplete yaml files with -o yaml

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-k#2565]
When running `kamel bind ... -o yaml` the result is missing the `apiVersion` and `kind` lines.

Example: 

```sh
kamel bind timer-source kafka-sink -p source.message="hola mundo" -p sink.topic="timer1" -p sink.brokers="uno" -p sink.username="dos" -p sink.password="tres" -o yaml
```

produces the following output:

```yaml
metadata:
  creationTimestamp: null
  name: timer-source-to-kafka-sink
  namespace: user1
spec:
  errorHandler: null
  sink:
    properties:
      brokers: uno
      password: tres
      topic: timer1
      username: dos
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: kafka-sink
      namespace: user1
  source:
    properties:
      message: hola mundo
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
      namespace: user1
status: {}
```
