### ISSUE TITLE
Kamelet add support for tolerations

### ISSUE THREAD

**Issue by art-pepper** [apache/camel-k#2602]
Hi, I am using camel-k 1.5.0 and knative v0.24.0 and I created a kamelet that gets messages from rabbitmq and sends them to a knative service, I would like to configure everything on the kamelet level because it creates the integration which creates the deployment.
I am able to configure a nodeSelector but it is not possible to configure a toleration. Please add support in the kamelet for adding a toleration or let me know about how it is possible on the kamelet/kameletbinding level ( not on the integration/deployment level)
Thank you in advance, appreciate your support on this

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: rabbitmq-message-source-binding
  namespace: default
spec:
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: my-service
      namespace: default
  source:
    properties:
      address: rabbitmq://myrmqexample.com
      header: ce-type
      header-value: my.header
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: rabbitmq-message-source
  integration:
    template:
      spec:
        nodeSelector:
          myApps: "true"
        containers:
          - name: integration

---

apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  labels:
    camel.apache.org/kamelet.type: source
  name: rabbitmq-message-source
  namespace: default
spec:
  definition:
    description: Receive messages from a RabbitMQ Source and set header
    properties:
      address:
        description: The RabbitMQ address with needed parameters
        title: Address
        type: string
      header:
        description: The header for the rabbitmq message
        title: Header Name
        type: string
      header-value:
        description: The header value for the rabbitmq message
        title: Header Value
        type: string
    required:
      - address
      - header
      - header-value
    title: RabbitMQ Message Source
    type: object
  dependencies:
    - camel:rabbitmq
    - camel:kamelet
  flow:
    from:
      steps:
        - set-header:
            constant: '{{header-value}}'
            name: '{{header}}'
        - log:
            message: 'Forwarding to knative service: ${body}'
        - to: kamelet:sink
      uri: '{{address}}'
```
