### ISSUE TITLE
Complete Integration PodSpec template

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#2620]
With the Kamelets adoption, we see the users need to configure some aspects of the created integrations, as in #2602.

For things like service account name, node selector, tolerations, affinity, resources, etc., using the integration `PodSpec` template field seems like a natural choice, e.g.:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
spec:
  integration:
    template:
      spec:
        nodeSelector:
          ...
        serviceAccountName: ...
```

Currently, only a subset of the k8s `PodSpec` struct is exposed in the integration `template` field. It would be useful to enrich it, at least with the `ServiceAccountName` and `Tolerations` field.
