### ISSUE TITLE
kamelet binding: scaling to 0 and the to 1 not working when a container image is provided

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2638]
Given a KameletBinding where the container image is given:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  annotations:
    trait.camel.apache.org/container.image: quay.io/acme/foo:1
    trait.camel.apache.org/jvm.enabled: "false"
    trait.camel.apache.org/kamelets.enabled: "false"
  name: klb-test
spec:
  integration:
    configuration:
    - type: secret
      value: klb-test-config
  replicas: 1
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
```

then doing:

```
kubectl scale klb/klb-test --replcias=0
kubectl scale klb/klb-test --replcias=1
```

would lead the operator to fail with:

```json
{
  "level": "error",
  "ts": 1631716704.5480886,
  "logger": "controller-runtime.manager.controller.integration-controller",
  "msg": "Reconciler error",
  "name": "klb-test",
  "namespace": "default",
  "error": "IntegrationKit.camel.apache.org \"kit-klb-test\" not found",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"
}
```

It seems like the integration kit is deleted when the integration is scaled.
