### ISSUE TITLE
Kamelet with MQTT Broker Mosquitto

### ISSUE THREAD

**Issue by agwermann** [apache/camel-k#2690]
Hi,

I am doing some tests with camel-k, Knative and the MQTT broker Mosquito. According to the camel-k documentation, it is possible to create a mqtt-source that will subscribe to a MQTT topic and forward the messages as Cloud Events to the serverless broker. However, I am facing some issues to do that, and I am not able to identify the problem.

My testbed is composed by:
1. Knative cluster running on [kind](https://kind.sigs.k8s.io/docs/user/quick-start).
2. Knative broker using [RabbitMQ](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md).
3. Knative broker trigger and sink processes (bind to RabbitMQ broker).
4. Mosquito MQTT broker deployed to Knative cluster and exposed to outside world.
5. IoT Sensors sending MQTT messages to Kubernetes cluster on exposed port (1883).

I am able to publish and subscribe o the MQTT broker from outside the cluster, but it looks the below KameletBinding is not working, since the event is not received by the Rabbitmq trigger/sink. I am able to receive in the Rabbitmq event sink cloud events generated by a PingSource process as per steps described [here](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md).

As far as I understood, [CamelSource was deprecated](https://github.com/nicolaferraro/knative-camel-source-examples/blob/master/04-mqtt.yaml). So far I was not able to use KameletBinding + KNative broker + Cloud Events header filters in the broker pattern as per described in the [link](https://github.com/nicolaferraro/knative-camel-source-examples/blob/master/04-mqtt.yaml#L16).

**Questions:**
1. Can someone please share a workable example or indicate what is being done wrong in my scenario?
2. Is it possible to use Knative/camel-k to publish back to mosquitto broker (e.g. mqtt sink). Example: Serverless Broker -> MQTT Mosquitto broker.

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: mqtt-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mqtt-source
    properties:
      brokerUrl: "tcp://mosquitto:1883"
      topic: "mytopic"
  sink:
    ref:
      kind: Broker
      apiVersion: messaging.knative.dev/v1
      name: default
```

**Resources:**
- https://github.com/apache/camel-kamelets/blob/main/mqtt-source.kamelet.yaml
- https://github.com/nicolaferraro/knative-camel-source-examples/blob/master/04-mqtt.yaml (deprecated)
- https://camel.apache.org/camel-kamelets/latest/mqtt-source.html

**Comment by agwermann** [comment]
@nicolaferraro, thanks for your quick response. The proposed solution did not work. Perhaps I am missing some step from my side? Please refer to the below steps.

Is there a way I can debug the event messages in kamel?

**Setup Knative and Serverless Broker:**
```bash
kind create cluster --name edge-cluster --config kind-edge-cluster-config.yaml

# Configure Knative Serving
kubectl apply -f https://github.com/knative/serving/releases/download/v0.26.0/serving-crds.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/v0.26.0/serving-core.yaml
kubectl get pods --namespace knative-serving

# Configure Knative Istio Service Mesh
kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.26.0/istio.yaml
kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.26.0/net-istio.yaml
kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.26.0/net-istio.yaml
kubectl --namespace istio-system get service istio-ingressgateway
kubectl get pods --namespace knative-serving

# Configure Knative Eventing
kubectl apply -f https://github.com/knative/eventing/releases/download/v0.26.0/eventing-crds.yaml
kubectl apply -f https://github.com/knative/eventing/releases/download/v0.26.0/eventing-core.yaml
kubectl get pods --namespace knative-eventing

# Configure RabbitMQ Serverless Broker
# https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md
kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/download/v1.9.0/cluster-operator.yml
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.4/cert-manager.yaml
kubectl apply -f https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.2.0/messaging-topology-operator-with-certmanager.yaml
kubectl apply -f https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.2.0/messaging-topology-operator-with-certmanager.yaml
kubectl apply -f https://github.com/knative-sandbox/eventing-rabbitmq/releases/download/v0.26.0/rabbitmq-broker.yaml

kubectl apply -f - << EOF
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rokn
  namespace: default
spec:
  replicas: 1
EOF

kubectl apply -f - << EOF
  apiVersion: eventing.knative.dev/v1
  kind: Broker
  metadata:
    name: default
    annotations:
      eventing.knative.dev/broker.class: RabbitMQBroker
  spec:
    config:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: rokn
EOF

kubectl get brokers
NAME      URL                                                       AGE   READY   REASON
default   http://default-broker-ingress.default.svc.cluster.local   5m   True    
```

Configure Kamelets and MQTT Broker:
```bash
# Configure Kamelets
kubectl create namespace camel-k
kamel install -n camel-k --registry-insecure true --registry localhost:32000/v1
kubectl get all -n camel-k

# Install mosquitto broker
kubectl create namespace mqtt
kubectl apply -f broker/mosquitto/mosquitto.yaml --namespace mqtt
kubectl get pods,deployments,services -n mqtt
kubectl logs -l app=gateway-bridge -f --all-containers

kubectl port-forward --address 0.0.0.0 deployment.apps/mosquitto 1883:1883 -n mqtt
```

Configure Broker Source, Trigger and Event Subscriber: https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/README.md#create-a-knative-trigger
I am able to use RabbitMQ Source, Trigger and Subscriber above.

```bash
kubectl logs subscriber-00001-deployment-59c878495d-fj5gw -c user-container
☁️  cloudevents.Event
Context Attributes,
  specversion: 1.0
  type: dev.knative.sources.ping
  source: /apis/v1/namespaces/default/pingsources/ping-source
  id: fb4ffd54-c67d-4646-b7ab-e539288b0611
  time: 2021-10-15T02:32:00.203178609Z
Data,
  {"message":"Hello world!"}
```

And finally apply the KameletBinding. I added the same type used by the Trigger `dev.knative.sources.ping`.

```yaml
kubectl apply -f - << EOF
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: mqtt-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mqtt-source
    properties:
      brokerUrl: "tcp://mosquitto:1883"
      topic: "mytopic"
  sink:
    ref:
      kind: Broker
      apiVersion: messaging.knative.dev/v1
      name: default
    properties:
      -- configured same type of rabbitmq event sink, so the same trigger is invoked.
      type: dev.knative.sources.ping
EOF
```

```
Name:         mqtt-source-binding
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  camel.apache.org/v1alpha1
Kind:         KameletBinding
Metadata:
  Creation Timestamp:  2021-10-15T01:36:50Z
  Generation:          3
  Managed Fields:
    API Version:  camel.apache.org/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:sink:
          .:
          f:properties:
            .:
            f:type:
          f:ref:
            .:
            f:apiVersion:
            f:kind:
            f:name:
        f:source:
          .:
          f:properties:
            .:
            f:brokerUrl:
            f:topic:
          f:ref:
            .:
            f:apiVersion:
            f:kind:
            f:name:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-10-15T01:36:50Z
  Resource Version:  82419
  UID:               efbee6f5-20c7-4ba5-9f12-ce7d56eb17fb
Spec:
  Sink:
    Properties:
      Type:  dev.knative.sources.ping
    Ref:
      API Version:  messaging.knative.dev/v1
      Kind:         Broker
      Name:         default
  Source:
    Properties:
      Broker URL:  tcp://mosquitto:1883
      Topic:       mytopic
    Ref:
      API Version:  camel.apache.org/v1alpha1
      Kind:         Kamelet
      Name:         mqtt-source
Events:             <none>
```

**Comment by agwermann** [comment]
@nicolaferraro, I also tried to add the sink service instead of the Broker, but still the same issue.
```
kubectl apply -f - << EOF
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: mqtt-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mqtt-source
    properties:
      brokerUrl: mosquitto:1883
      topic: mytopic
  sink:
    ref:
      kind: Service
      apiVersion: serving.knative.dev/v1
      name: subscriber
EOF
```
