### ISSUE TITLE
ErrorHandler for stopping a route when an error occurs

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#2724]
I was trying to implement the "stop route" behavior when encountering an error in a KameletBinding and it looks I can use a `controlbus` to implement it.

Something like:

```yaml
kind: KameletBinding
spec:
  source:
    # ...
  sink:
    # ...
  errorHandler:
    dead-letter-channel:
      endpoint:
        uri: "controlbus:route?routeId=${routeId}&action=stop"
```

Even if the concept of `dead-letter-channel` is a bit stretched here, that should do the work.
The only problem is that error handlers in Camel do not use dynamic dispatch and so the `${routeId}` placeholder is not resolved. Everything works when providing the right route ID.

Since bindings have a single main route, I wonder if we can simply call it e.g. `binding` in order to use a URI like `controlbus:route?routeId=binding&action=stop`.

@davsclaus you're the master, do you see another way?

cc: @squakez
