### ISSUE TITLE
Dry run kamel run

### ISSUE THREAD

**Issue by scodeman** [apache/camel-k#2769]
Is it possible to perform a dry-run with kamel in order to retrieve the Kubernetes manifest that would be representative of an integration (written in other languages like Java DSL, etc...) ?

The need behind that is to be able to package an integration as one of the resources within independent helm chart.
The workflow foreseen:
1. **kamel local build xxxx.java** to generate and manage the tagging/versioning and release of integration images
2. retrieve corresponding Integration CR manifest
3. have helm chart reuse manifest with corresponding image within integration template
```yaml
traits:
  container:
      configuration:
        enabled: true
        image: <locally_built_image>
```
