### ISSUE TITLE
Error: unknown flag: --trait on local build

### ISSUE THREAD

**Issue by scodeman** [apache/camel-k#2776]
As per #2769 I am trying to build a local integration image and use it in for my integration manifest.
I have the following IntegrationFile.java  simple java DSL example with modelines:
```java
// camel-k: language=java
// camel-k: trait=container.enabled=true
// camel-k: trait=container.image=localhost:5000/camelk_test:latest

import org.apache.camel.builder.RouteBuilder;

public class IntegrationFile extends RouteBuilder {
  @Override
  public void configure() throws Exception {

      // Write your routes here, for example:
      from("timer:java?period=1000")
        .routeId("java")
        .setBody()
          .simple("Hello Camel K from ${routeId}")
        .to("log:info");

  }
}
```
But it fails to local build ```kamel local build IntegrationFile.java``` with the following error reported
```
Modeline options have been loaded from source files
Full command: kamel local build IntegrationFile.java --trait=container.enabled=true --trait=container.image=localhost:5000/camelk_test:latest 
Error: unknown flag: --trait
```

**Comment by scodeman** [comment]
Note that the dry-run (cf:#2769) ``` kamel run IntegrationFile.java -o yaml```  call works as expected providing me the following output
```
Modeline options have been loaded from source files
Full command: kamel run IntegrationFile.java -o yaml --trait=container.image=localhost:5000/integration-base-image:latest 
```
```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  creationTimestamp: null
  name: integration-file
  namespace: default
spec:
  sources:
  - content: |
      // camel-k: language=java
      // camel-k: trait=container.image=localhost:5000/integration-base-image:latest

      import org.apache.camel.builder.RouteBuilder;

      public class IntegrationFile extends RouteBuilder {
        @Override
        public void configure() throws Exception {

            // Write your routes here, for example:
            from("timer:java?period=1000")
              .routeId("java")
              .setBody()
                .simple("Hello Camel K from ${routeId}")
              .to("log:info");

        }
      }
    name: IntegrationFile.java
  traits:
    container:
      configuration:
        image: localhost:5000/integration-base-image:latest
status: {}
```
