### ISSUE TITLE
Be able to configure PodMonitor via prometheus trait

### ISSUE THREAD

**Issue by betonetotbo** [apache/camel-k#2812]
Currently the only thing is possible to configure at the prometheus trait is the labels, as we can see here: https://camel.apache.org/camel-k/1.7.x/traits/prometheus.html

Would be a nice feature , if we would be able to configure prometheus `PodMonitor` specs (https://github.com/prometheus-operator/prometheus-operator/blob/release-0.39/Documentation/api.md#podmetricsendpoint).

For example: set a specific interval for the metrics endpoint scrape, in my case the default scrape interval in prometheus is 60s, but I need that my camel-k integrations to be scrape each 15 seconds. 

A suggestion for use in command line: 

`kamel run Integration.java --trait prometheus.pod-monitor.spec.pod-metrics-endpoints.interval=15s`

So this would be a nice pattern to customize any parameter in the PodMonitor definition.

**Comment by astefanutti** [comment]
I wonder in that case whether creating a single bespoke `PodMonitor` matching all the integrations, would meet your need, e.g.: 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: camel-k-integrations
  labels:
    # To match the Prometheus PodMonitor selector
spec:
  podTargetLabels:
    - camel.apache.org/integration
  selector:
    matchExpressions:
      - key: camel.apache.org/integration
        operator: Exists
  podMetricsEndpoints:
    - port: metrics
      path: /q/metrics
      interval: 15s
```

And you could configuration the _prometheus_ trait globally on the IntegrationPlatform, e.g.:

```yaml
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
spec:
  traits:
    - prometheus:
      configuration:
        enabled: true
        podMonitor: false
```
