### ISSUE TITLE
`out` attribute in Kamelet type CRD is in documentation example but not in yaml schema

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#2818]
from https://camel.apache.org/camel-k/1.7.x/kamelets/kamelets-dev.html#_creating_a_simple_kamelet
```
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: twitter-search-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Timer"
    description: "Produces periodic events with a custom payload"
    required:
      - message
    properties:
      period:
        title: Period
        description: The time interval between two events
        type: integer
        default: 1000
      message:
        title: Message
        description: The message to generate
        type: string
  types:
    out:
      mediaType: text/plain
  flow:
    from:
      uri: timer:tick
      parameters:
        period: "{{period}}"
      steps:
        - set-body:
            constant: "{{message}}"
        - to: "kamelet:sink"

```

in spec -> types, there is an `out` tag but there is no `out` tag defined in crd yaml schema

https://github.com/apache/camel-k/blob/48422c08bc20295d09cb31694adc177726806d6b/helm/camel-k/crds/crd-kamelet.yaml#L271-L426
