### ISSUE TITLE
JVM trait option to add a trusted root cert on startup

### ISSUE THREAD

**Issue by cwtrex** [apache/camel-k#2820]
Some of the kamelets utilize SSL but offer no way to add a trusted cert in the properties (example: elasticsearch index sink).

Need a way to trust a private CA's root certificate for non-maven purposes.

**Comment by squakez** [comment]
Maybe you can declare the expected certificate as a path parameter in a Kamelet and then provide the certificate as a binary file via `kamel run --resource [file|secret|configmap]` option.

**Comment by ephemeris-lappis** [comment]
Is this issue still open ?

Are you going to add this feature in 2.9.0 ?

```
 traits:
    jvm:
      configuration:
        trust-certificates-secrets:
          - a-secret
          - another-secret
```
