### ISSUE TITLE
Scaling integration pod and the replicas are not able to receive traffic via UDP port

### ISSUE THREAD

**Issue by haifzhan** [apache/camel-k#2847]
Hi Apache Camel team:

Situation:
1. I have an integration pod is listening on UDP 8444 and forward it to 30006, and it is configured in `my-integration-service.yaml`
2. I am trying to scale the integration followed the document [CAMEL K INTEGRATION SCALING
](https://camel.apache.org/camel-k/1.7.x/scaling/integration.html)

For instance I have 2 pods running after scale and only the first pod is capable of receiving incoming events.

I see a similar question under Issues [scaling out camel-k integrations are not working correctly #1806](https://github.com/apache/camel-k/issues/1806). The service was enabled as a node port. As far as I know, the service trait only works for TCP not UDP.

Please help.

my-integration-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: my-integration
spec:
  type: NodePort
  selector:
    camel.apache.org/integration: my-integration
  ports:
    - protocol: UDP
      port: 8444
      targetPort: 8444
      nodePort: 30006
```
