### ISSUE TITLE
Directly reference secrets in KameletBinding

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#2875]
I thought there was an issue for this, but apparently not.
When creating a KameletBinding you put all properties in plaintext, including secret ones.
There are ways to save data in secrets but they involve using a specific format of the underlying runtime (.properties file in the secret with Camel notation `camel.kamelet.<name>.<id>.<key>=<val>`), which is not ideal for a high level construct like the KameletBinding.

There should be something like:

```yaml
source:
  # ...
  properties:
    queue: myqueue
    accessKey:
      secretRef:
        name: mysecret
        key: access-key
```

The problems with that is that the `spec` -> `properties` are no longer expected to be compliant with the JSON-schema definition in the Kamelet. So we may decide to change that definition as well, or provide a `propertyRef` section. There are multiple solutions, but we need one before it goes to `v1`.
