### ISSUE TITLE
Intermittent problem with integration remaining at phase "Building Kit"

### ISSUE THREAD

**Issue by phantomjinx** [apache/camel-k#2905]
During the upgrade e2e tests, the [cli_update.go](https://github.com/apache/camel-k/blob/main/e2e/upgrade/cli_upgrade_test.go#L108), is executed and intermittently fails with a [timeout](https://github.com/openshift-integration/camel-k-testing-ocp4/runs/4897338823?check_suite_focus=true#step:8:1143).

Looking at the dump, the integration is never allocated an integration-kit:
```
dump.go:68: Found 1 integrations:
    dump.go:75: ---
        apiV***sion: camel.apache.org/v1
        kind: Integration
        metadata:
          creationTimestamp: "2022-01-21T14:54:16Z"
          gen***ation: 1
          name: yaml
          namespace: test-44c8a780-d0f1-4af2-9b91-90968db2d580
          ...
        status:
          conditions:
          ...
            name: camel-k-embedded-flow.yaml
          integrationKit: {}
          lastInitTimestamp: "2022-01-21T14:57:09Z"
          ....
```           
Looking at the test project, this is confirmed:
```
[: … camel-k] er+ ± oc get integration
NAME   PHASE          KIT   REPLICAS
yaml   Building Kit         
```
However, it seems that the integration has in fact been rebuilt and its pod up and running:
```
NAME                                       READY   STATUS      RESTARTS   AGE
camel-k-kit-c7lciccu56b68f4crnog-1-build   0/1     Completed   0          42m
camel-k-kit-c7lcjhcouqe7lfl24jp0-1-build   0/1     Completed   0          39m
camel-k-operator-54d54fd489-lx4rv          1/1     Running     0          40m
yaml-757d8796f9-kdvvh                      1/1     Running     0          40m
```
Is it possible that the operator has somehow missed or skipped updating the phase of the integration?

Difficult to pin-down since any single retest shows a successful upgrade of both the operator and integrations.
