### ISSUE TITLE
Configure Maven: Artifact Repository is not recognized

### ISSUE THREAD

**Issue by k0pper** [apache/camel-k#2966]
I followed the instructions on https://camel.apache.org/camel-k/1.8.x/configuration/maven.html to configure Camel-K and which repository to use. My goal is that the Integrations download their dependencies from gitlab's package registry, and if not found it looks it up on Maven Central. How is this possible?

I created an this settings.xml:
https://gist.github.com/k0pper/3176c5750cb63e5b7160b26c887d2bda

and created a configmap from it:
```
kubectl create configmap maven-settings --from-file=settings.xml
```

Then, I referenced the created configmap in the integrationplatform.yaml in the cluster.

```
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  labels:
    app: camel-k
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: camel-k
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: camel-k-0.9.0
  name: camel-k
  namespace: camel-k
spec:
  build:
    maven:
      settings:
        configMapKeyRef:
          key: settings.xml
          name: maven-settings
```

Now, **The Problem**: The Logs of the Operator trying to deploy an integration doesn't even mention the **gitlab-maven** repository. When resolving the dependencies, it logs:
```
 {"level":"info","ts":1643637038.4897394,"logger":"camel-k.maven.build","msg":"Downloading from central: https://repo.maven.apache.org/maven2/org/apache/camel/quarkus/camel-quarkus-timer/2.6.0/camel-quarkus-timer-2.6.0.pom"}
```
 
Shouldn't it be at least "Downloading from centralllll", because that is the ID for the Central Repository in the settings.xml?

What is happening?

Alex
