### ISSUE TITLE
Errored status Kamelet cannot be reconciled to Ready status

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#2988]
If we have any error in the Kamelet spec definition, ie
```
status:
  conditions:
  - lastTransitionTime: "2022-02-07T16:58:44Z"
    lastUpdateTime: "2022-02-07T16:58:44Z"
    message: Kamelet can only specify one of "flow" or "template"
    reason: InvalidTemplate
    status: "False"
    type: Ready
  phase: Error
```
we are not able to fix, even changing the Kamelet spec. It seems that the reconciliation maintain the error condition.
