### ISSUE TITLE
If a KameletBinding is invalid, the related status is not updated to report an error

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3010]
Assuming a KameletBinding lacks sourece/sink, as example:

```yaml
piVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: c82iernvdc4irh6evn20
  namespace: default
spec:
  integration:
    configuration:
    - type: secret
      value: c82iernvdc4irh6evn20
    profile: OpenShift
  steps: []
```

The operator will fail with something like:

```json
{
  "level":"error",
  "ts":1644832192.1764352,
  "logger":"controller.kamelet-binding-controller",
  "msg":"Reconciler error",
  "name":"c82iernvdc4irh6evn20",
  "namespace":"cos",
  "error":"could not determine source URI: no ref or URI specified in endpoint",
  "errorVerbose":"no ref or URI specified in endpoint"
}
```

But the error is not reported in the KameletBinding's status
