### ISSUE TITLE
Camel-K Java native support - native run of a java route fails

### ISSUE THREAD

**Issue by catshout** [apache/camel-k#3023]
I've a fresh installed Camel-K 1.8.0 Operator. My sample route `hello.java` like

```
from('timer:tick?period=3000')
  .setBody().constant('Hello world from Camel K')
  .to('log:info')
```

and tried to execute the following command

`kamel run -t quarkus.package-type=native hello.java`

With this I'm getting the error (excerpt from resource yaml

```
  status:
    conditions:
    - firstTruthyTime: "2022-02-18T07:43:59Z"
      lastTransitionTime: "2022-02-18T07:43:59Z"
      lastUpdateTime: "2022-02-18T07:43:59Z"
      message: integration/camel-k
      reason: IntegrationPlatformAvailable
      status: "True"
      type: IntegrationPlatformAvailable
    - lastTransitionTime: "2022-02-18T07:44:00Z"
      lastUpdateTime: "2022-02-18T07:44:00Z"
      message: native compilation for language "java" is not supported
      reason: UnsupportedLanguage
      status: "False"
      type: IntegrationKitAvailable
    - lastTransitionTime: "2022-02-18T07:44:00Z"
      lastUpdateTime: "2022-02-18T07:44:00Z"
      message: no host or service defined
      reason: IngressNotAvailable
      status: "False"
```

What am I missing here?
