### ISSUE TITLE
IntegrationKit creation based on YAML file fails

### ISSUE THREAD

**Issue by catshout** [apache/camel-k#3033]
I did create an IntegrationKit with the following command

```kamel kit create test-kit -n integration-dev -d mvn:org.apache.camel.k:camel-k-runtime -d camel-timer -d mvn:org.apache.camel.quarkus:camel-quarkus-java-joor-dsl
```

The build was flagged as `ready` some time later and I could reference it for Integration creation. (Idea behind is to have a named set of IntegrationKits that can be re-used for Integrations of the same type.

At next I tried the same with kubectl and a YAML file `integrationkit.yaml`

```
kubectl apply -f integrationkit.yaml
```

```
apiVersion: camel.apache.org/v1
kind: IntegrationKit
metadata:
  labels:
    camel.apache.org/kit.type: user
  name: test-kit
  namespace: integration-dev
spec:
  dependencies:
    - mvn:org.apache.camel.k:camel-k-runtime
    - mvn:org.apache.camel.quarkus:camel-quarkus-java-joor-dsl
    - camel-log
    - camel-timer
```

The build finally fails with an error

```
kubectl logs -f integrationkits.camel.apache.org/test-kit
error: no kind "IntegrationKit" is registered for version "camel.apache.org/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

Any idea what's missing here?
