### ISSUE TITLE
kamel run with reference to an existing Integration Kit in another namespace

### ISSUE THREAD

**Issue by catshout** [apache/camel-k#3059]
I'm going to run an Integration with a reference to an existing Integration Kit.

```
kamel run -t prometheus.enabled=true -k basic Hello.java -n integration-dev
```

When I'm using the `-o yaml > Hello.yaml` option I'm getting

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  creationTimestamp: null
  name: hello
  namespace: integration-dev
spec:
  integrationKit:
    name: basic
    namespace: integration-dev
  sources:
  - content: "// camel-k: language=java\n\npackage de.casag.hello.route;\n\nimport
      org.apache.camel.builder.RouteBuilder;\n\npublic class Hello extends RouteBuilder{\n\n\tpublic
      void configure() throws Exception {\n\n\t\tfrom(\"timer:enforedeinvoices?period=3600000&delay=0\")\n\t\t\t\t.log(\"Hello
      World!\")\n\t\t;\n\n\t}\n}\n\n"
    name: Hello.java
  traits:
    prometheus:
      configuration:
        enabled: true
status: {}
```

The Integration should be deployed in the namespace `integration-dev`. The Integration Kit being referenced is located in the namespace `camel-k`.

I can change this in the YAML file like

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  creationTimestamp: null
  name: hello
  namespace: integration-dev
spec:
  integrationKit:
    name: basic
    namespace: camel-k
  sources:
  - content: "// camel-k: language=java\n\npackage de.casag.hello.route;\n\nimport
      org.apache.camel.builder.RouteBuilder;\n\npublic class Hello extends RouteBuilder{\n\n\tpublic
      void configure() throws Exception {\n\n\t\tfrom(\"timer:enforedeinvoices?period=3600000&delay=0\")\n\t\t\t\t.log(\"Hello
      World!\")\n\t\t;\n\n\t}\n}\n\n"
    name: Hello.java
  traits:
    prometheus:
      configuration:
        enabled: true
status: {}
```

and deploy afterwards with

```
kubectl apply -f Hello.yaml
```

The Integration works event with the reference to an Integration Kit in another namespace.

Is there a way to address the different namespace in the `kamel run -k <IntegrationKit>` CLI part?

Best
Gerald
