### ISSUE TITLE
kamelet: allow to add additional attributes to in/out

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3090]
As today, a kamelet has the option to define the types it supports but that is limited to the following information:

```go
type EventTypeSpec struct {
	// media type as expected for HTTP media types (ie, application/json)
	MediaType string `json:"mediaType,omitempty"`
	// the expected schema for the event
	Schema *JSONSchemaProps `json:"schema,omitempty"`
}
```

Given that a kamelet may be more complex and the tooling using them may need more information it would be nice to have the option to add additional metadata, as example, in some case it may be useful to add an information about what is the Java class the output of a camel is build upon:

```yaml
spec:
  out:
    mediaType: "accplication/json"
    annotations:
        contentClass: com.acme.Foo
```

This may be useful for tools as they may compute the scheme of the payload.
