### ISSUE TITLE
integration readiness condition is not reported to kamelet binding

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3091]
In the scenario below, an integration that is created out of a kamelet binding is not ready because of an issue when starting a pod

```
 NAME                                                             READY  REASON      
------------------------------------------------------------------------------------------------ 
 KameletBinding/foo-c8fkegvtfa9sdsrjjslg                        True                          
 └─Integration/foo-c8fkegvtfa9sdsrjjslg                         False  DeploymentProgressing  
   ├─ConfigMap/foo-c8fkegvtfa9sdsrjjslg-application-properties  -                             
   ├─ConfigMap/foo-c8fkegvtfa9sdsrjjslg-source-000              -                             
   ├─Deployment/foo-c8fkegvtfa9sdsrjjslg                        -                             
   │ └─ReplicaSet/foo-c8fkegvtfa9sdsrjjslg-d45754b98            -                             
   │   ├─Pod/foo-c8fkegvtfa9sdsrjjslg-d45754b98-kz9jj           False  ContainersNotReady     
   └─IntegrationKit/kit-foo-c8fkegvtfa9sdsrjjslg                -                
 ```

The integration has the following condition:

```yaml
  - firstTruthyTime: "2022-03-03T21:38:37Z"
    lastTransitionTime: "2022-03-03T23:13:29Z"
    lastUpdateTime: "2022-03-03T23:13:29Z"
    message: 0/1 ready replicas
    reason: DeploymentProgressing
    status: "False"
    type: Ready
```

However the kamelet binding is reported as ready:

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-03-03T21:38:16Z"
    lastUpdateTime: "2022-03-03T21:38:16Z"
    status: "True"
    type: Ready
  phase: Ready
```

In such case the binding should be marked as failed ot at least it should have a condition reporting that is not ready.
