### ISSUE TITLE
Improve the logging of quarkus build failures

### ISSUE THREAD

**Issue by phantomjinx** [apache/camel-k#3149]
When an integration kit fails to be built, it is often the case that the only error message obtainable is in the status of the integration kit:
```
status:
  ...
  failure:
    reason: 'failure while building project: exit status 1'
    recovery:
      attempt: 5
      attemptMax: 5
      attemptTime: "2022-03-29T08:59:15Z"
    time: "2022-03-29T08:56:58Z"
  phase: Error
  platform: camel-k
```

No other error messaging appears evident, either in the integration, the kit or the operator. Would be beneficial to try and capture the [output](https://github.com/apache/camel-k/blob/main/pkg/builder/quarkus.go#L193) of the quarkus operation and log this in the operator so that the nature of the quarkus errror is more obvious.
