### ISSUE TITLE
Integration upgraded automatically after operator upgrade

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3294]
Just tested with the following scenario:

1. Use an operator version (ie, 1.8)
2. Run a sample Integration
3. Upgrade the operator version (ie, 1.9)

The Integration on point 2 is rebuilt automatically (is that correct behavior?) And, even if that would be correct, the resulting Integration has still the previous operator version parameters, ie:
```
  status:
...
    phase: Running
    platform: camel-k
    profile: Kubernetes
    replicas: 1
    runtimeProvider: quarkus
    runtimeVersion: 1.12.0
    selector: camel.apache.org/integration=sample
    version: 1.8.2
```
