### ISSUE TITLE
Simple KameletBinding created with Errors

### ISSUE THREAD

**Issue by tmihalac** [apache/camel-k#3299]
In Camel-k 1.8.2/1.9.2 on Openshift when I try to create a simple KameletBinding it is created unsuccessfully and keeps respawning pods with errors, this looks some kind of a race condition (it is inconsistently happening - sometimes it happens all the time and sometimes it doesnt happen at all)
The Kamelet I am using as the source is a clone of the [Webhook Source Kamelet](https://camel.apache.org/camel-kamelets/next/webhook-source.html)

The KameletBinding:
```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: auto-remediation-platform
  annotations:
    trait.camel.apache.org/logging.level: DEBUG
    trait.camel.apache.org/logging.color: "false"
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: auto-remediation-entrypoint
  sink:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: default
```

The Kamelet:
```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: auto-remediation-entrypoint
  annotations:
    camel.apache.org/kamelet.group: "Webhook"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Webhook Source"
    description: |-
      Test
    type: object
    properties:
      subpath:
        title: Subpath
        description: |
          The subpath where the webhook is registered
        type: string
        default: "webhook"
  dependencies:
    - "camel:platform-http"
    - "camel:kamelet"
  template:
    from:
      uri: "platform-http:///{{subpath}}"
      steps:
        - to: "kamelet:sink"
```

**Steps to reproduce:**
1. Create a new project**(Important)**
2. Install serverless-operator.v1.22.0
3. Install Camel K operator 1.8.2
4. Create knative default broker
5. Create the Kamelet
6. Create the KameletBinding

Attached Screenshots & error log

[auto-remediation-platform-00001-deployment-65c7f5646d-vqqhx-integration.log](https://github.com/apache/camel-k/files/8760927/auto-remediation-platform-00001-deployment-65c7f5646d-vqqhx-integration.log)

![image](https://user-images.githubusercontent.com/84387487/169985712-975dface-c8cd-4bae-8efb-a171024b53a9.png)

![image](https://user-images.githubusercontent.com/84387487/169986626-49d20f2f-1321-47ff-8f5a-b2716fcee4d8.png)

![image](https://user-images.githubusercontent.com/84387487/169986772-30242642-f455-4ef1-b602-524bbab843fc.png)
