### ISSUE TITLE
RBAC missing permissions for channels and inmemorychannels in messaging.knative.dev

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3390]
The Camel K operator has lost the permission to get/list and manage channels/inmemorychannels in messaging.knative.dev group. This causes the knative trait to raise permission errors when binding a Kamelet to channels/inmemorychannels for instance.

To reproduce add a KameletBinding that makes use of a Knative channel.

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: message-event-sink
spec:
  source:
    ref:
      kind: Channel
      apiVersion: messaging.knative.dev/v1
      name: messages
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
```

This will result in errors in Camel K operator logs and the KameletBinding is stuck in "Creating" phase.

```
{"level":"error","ts":1655995698.9808981,"logger":"controller.integration-controller","msg":"Reconciler error","reconciler group":"camel.apache.org","reconciler kind":"Integration","name":"prize-event-sink","namespace":"yaks-demo","error":"error during trait customization: unexpected error while executing handler for channel prize-channel: cannot determine address of channel prize-channel: channels.messaging.knative.dev \"prize-channel\" is forbidden: User \"system:serviceaccount:openshift-operators:camel-k-operator\" cannot get resource \"channels\" in API group \"messaging.knative.dev\" in the namespace \"yaks-demo\"","errorVerbose":"channels.messaging.knative.dev \"prize-channel\" is forbidden: User \"system:serviceaccount:openshift-operators:camel-k-operator\" cannot get resource \"channels\" in API group \"messaging.knative.dev\" in the namespace \"yaks-demo\"\ncannot determine address of channel prize-channel\ngithub.com/apache/camel-k/pkg/trait.(*knativeTrait).withServiceDo.func1\n\tgithub.com/apach...
```
