### ISSUE TITLE
kamel run --output yaml does not include resources

### ISSUE THREAD

**Issue by sidharthramesh** [apache/camel-k#3396]
## Steps to reproduce
I'm trying to get the output of an Integration in YAML to be applied later via GitOps using ArgoCD.
My Java file with modeline looks like this:
```java
// camel-k: name=hl7-sink language=java resource=file:composition.jslt resource=file:patient.jslt property=file:application.properties dependency=mvn:org.apache.camel.quarkus:camel-quarkus-hl7 dependency=mvn:org.apache.camel.quarkus:camel-quarkus-base64

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.camel.AggregationStrategy;
import org.apache.camel.Exchange;
import org.apache.camel.builder.RouteBuilder;
import ca.uhn.hl7v2.model.Message;
import ca.uhn.hl7v2.util.Terser;

public class Sink extends RouteBuilder {
  AggregationStrategy combinedData = (oldExchange, newExchange) -> {
    if (oldExchange != null) {
      HashMap<String, String> oldData = oldE...
...
```

Running `kamel run Sink.java -o yaml` produces YAML:
```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  annotations:
    networking.knative.dev/disable-auto-tls: "true"
  creationTimestamp: null
  name: hl7-sink
  namespace: default
spec:
  dependencies:
  - mvn:org.apache.camel.quarkus:camel-quarkus-hl7
  - mvn:org.apache.camel.quarkus:camel-quarkus-base64
  sources:
  - content: |
      // camel-k: name=hl7-sink language=java resource=file:composition.jslt resource=file:patient.jslt property=file:application.properties dependency=mvn:org.apache.camel.quarkus:camel-quarkus-hl7 dependency=mvn:org.apache.camel.quarkus:camel-quarkus-base64 annotation=networking.knative.dev/disable-auto-tls=true trait=owner.target-annotations=networking.knative.dev/disable-auto-tls

      import java.util.ArrayList;
      import java.util.HashMap;
      import java.util.List;
      import java.util.Map;
...
...
...
traits:
    camel:
      configuration:
        properties:
        - fhirUrl = example.com
        - openehrUrl = example.com
        - templateId = string
        - blobUpload = example.com
    mount:
      configuration:
        resources:
        - configmap:cm-05e3ce58d0d145de025ad919cf0b763216b88cf5/composition.jslt@/etc/camel/resources/composition.jslt
        - configmap:cm-2298cb03631fddcc33ab4d3832953f3e535d37b2/patient.jslt@/etc/camel/resources/patient.jslt
    owner:
      configuration:
        targetAnnotations:
        - networking.knative.dev/disable-auto-tls
```

The resources `composition.jslt` and `patient.jslt` are applied to the Kubernetes cluster as configmaps, and their reference is present here. But they are not included in the YAML output.

## Expected
The YAML file should include the resources, configmaps, and secrets generated from files along with the the integration CRD.
