### ISSUE TITLE
Missing option to enable prometheus monitoring when installing Camel-K using Helm

### ISSUE THREAD

**Issue by bjethwan** [apache/camel-k#3429]
Documentation here talks about enabling camel-k operator monitoring using kamel cmd util BUT it's missing information about enabling the same using camel-k helm chart. 
https://camel.apache.org/camel-k/1.9.x/observability/monitoring/operator.html

**Comment by bjethwan** [comment]
Is it possible to install camel-k using Helm but enable prometheus monitoring using "kamel" cli?

**Comment by bjethwan** [comment]
I guess the option is missing altogether in camel-k helm chart

helm show values camel-k/camel-k
```
# Default values for camel-k.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

operator:
  image: docker.io/apache/camel-k:1.9.2

platform:
  build:
    registry: {}
  cluster: ""
```
