### ISSUE TITLE
ERROR: could not find any knative type in namespace default, last error was: the server could not find the requested resource

### ISSUE THREAD

**Issue by bjethwan** [apache/camel-k#3430]
Why is timer to aws-s3 kamelet based routing looking for knative?

I installed camel-k operator, and I see that "aws-s3-streaming-upload-sink" is ready.
```
% k get kamelet | grep s3
aws-s3-sink                            Ready
aws-s3-source                          Ready
aws-s3-streaming-upload-sink           Ready
```

When I created a kamelet binding, although the route/integration works fine and files are written in my S3 bucket but I get errors in camel-k operator
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: aws-s3-streaming-upload-sink-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: hello world
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-s3-streaming-upload-sink
    properties:
      bucketNameOrArn: arn:aws:s3:::kameletdemo
      keyName: timer-source
      region: ap-south-1
      accessKey: <<>>
      secretKey: <<>>
      batchMessageNumber: 5
```

I got error in camel-k operator logs 
```
{"level":"info","ts":1657477260.4902384,"logger":"camel-k","msg":"could not find any knative type in namespace default, last error was: the server could not find the requested resource"}
{"level":"info","ts":1657477265.491685,"logger":"camel-k.controller.kameletbinding","msg":"Reconciling KameletBinding","request-namespace":"default","request-name":"aws-s3-streaming-upload-sink-binding"}
{"level":"info","ts":1657477265.4919102,"logger":"camel-k.controller.kameletbinding","msg":"Invoking action monitor","request-namespace":"default","request-name":"aws-s3-streaming-upload-sink-binding","api-version":"camel.apache.org/v1alpha1","kind":"KameletBinding","ns":"default","name":"aws-s3-streaming-upload-sink-binding"}
```

I am not using knative as source or target in above kamelet binding. Then why it doesn't work?
