### ISSUE TITLE
[E2E] Add tests for enabling traits at IntegrationPlatform

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3476]
As a follow-up to #3205, there's no test coverage that verifies Integration runs when traits are enabled at IntegrationPlatform like this:
```yaml
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  labels:
    app: camel-k
  name: camel-k
spec:
  traits:
    addons:
      tracing:
        enabled: true
    jolokia:
      enabled: true
```
Unlike when enabled at Integration, these tests can make sure the traits don't crash during kit building as when they are enabled at IntegrationPlatform they are also forced to be enabled during kit building while an integration is still absent.
