### ISSUE TITLE
camel-k ignores changes to traits configured using annotations

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3479]
Assuming that you have a binding like the one below were annotations are used to configure traits:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer2log
  annotations:
    trait.camel.apache.org/container.image: acme/bad:1
    trait.camel.apache.org/jvm.enabled: "false"
    trait.camel.apache.org/kamelets.enabled: "false"
spec:
  integration:
    configuration:
      - type: configmap
        value: timer2log-config
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
    properties:
      message: "foo"
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink
```      

In this specific case as example, the container image that must be used to run the Integration is set set using the  `trait.camel.apache.org/container.image: acme/bad:1` annotation. 
If you update the resource and you change only the container image, then the reconcile loop is not triggered because the kamelet binding controller [take into account only the phase or the generation ](https://github.com/apache/camel-k/blob/b004a5a250fa0a816acd6a57c0378c17c6935b58/pkg/controller/kameletbinding/kamelet_binding_controller.go#L93-L94)(which does not change when only the matadata is amended ).

Since annotation can be used to configure traits,, they should be taken into account.
