### ISSUE TITLE
Trait owner.target-annotations is not propagated to K8S Services

### ISSUE THREAD

**Issue by ruromero** [apache/camel-k#3494]
When using the Owner Trait to propagate annotations to the owned resources, such annotations are not propagated to the Kubernetes Services.

```
# camel-k: language=yaml
# camel-k: trait=owner.enabled=true
# camel-k: trait=owner.target-annotations=[example]
```

The deployment shows the annotation but the service doesn't.

Is this the expected behaviour?

**Comment by ruromero** [comment]
fyi @squakez

**Comment by squakez** [comment]
It seems the `Service` is annotated correctly. I've just tested with an example as:
```
import org.apache.camel.builder.RouteBuilder;

public class PlatformHttpServer extends RouteBuilder {
  @Override
  public void configure() throws Exception {
    from("platform-http:/hello?httpMethodRestrict=GET").setBody(simple("Hello ${header.name}"));
  }
}
...
$ kamel run PlatformHttpServer.java --annotation test=my-test -t owner.target-annotations=test --dev
...
$ k get svc platform-http-server -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    test: my-test
  creationTimestamp: "2022-07-27T13:28:29Z"
  labels:
    camel.apache.org/generation: "1"
    camel.apache.org/integration: platform-http-server
    camel.apache.org/service.type: user
...
```

**Comment by ruromero** [comment]
@squakez it seems I didn't define the integration resource properly. Yes it is working, sorry for the false alarm :sweat_smile:

**Comment by ruromero** [comment]
Here is an example of the CRD definition, for reference

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: auth-hello-world
  annotations:
    test: my-test
    other: other-test
spec:
...
  traits:
    owner:
      configuration:
        enabled: true
        targetAnnotations:
        - test
        - other
```
