### ISSUE TITLE
Passing namespace info for CXF Endpoint in Camel-K YAML DSL

### ISSUE THREAD

**Issue by jcordes73** [apache/camel-k#3503]
I'm trying to create an integration with a CXF Endpoint using Payload mode and the Camel-K YAML DSL and therefore need to provide namespaced service- and portname. In the Camel 2 Spring DSL this was possible because it was namespaceaware. How can this be achieved?

Right now I'm getting the following error when running the example attached (using the jbang camel extension):

camel run test.yaml --logging-level=debug
...
2022-08-01 14:19:14.775 DEBUG 35553 --- [           main] .apache.camel.main.MainLifecycleStrategy : CamelContext: CamelJBang is stopping, triggering shutdown of the JVM.
org.apache.cxf.service.factory.ServiceConstructionException: Could not find definition for service tns:ndfdXML.
	at org.apache.cxf.wsdl11.WSDLServiceFactory.create(WSDLServiceFactory.java:157)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL(ReflectionServiceFactoryBean.java:407)
	at org.apache.camel.component.cxf.jaxws.WSDLServiceFactoryBean.buildServiceFromWSDL(WSDLServiceFactoryBean.java:107)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:527)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
	at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)
	at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
	at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
	at org.apache.camel.component.cxf.jaxws.CxfConsumer.createServer(CxfConsumer.java:75)
	at org.apache.camel.component.cxf.jaxws.CxfConsumer.doStart(CxfConsumer.java:106)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3665)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:401)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:319)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:213)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:147)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3364)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:3033)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2988)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2649)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
	at org.apache.camel.main.KameletMain.doStart(KameletMain.java:236)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.dsl.jbang.core.commands.Run.run(Run.java:560)
	at org.apache.camel.dsl.jbang.core.commands.Run.call(Run.java:199)
	at org.apache.camel.dsl.jbang.core.commands.Run.call(Run.java:72)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.apache.camel.dsl.jbang.core.commands.CamelJBangMain.run(CamelJBangMain.java:51)
	at main.CamelJBang.main(CamelJBang.java:37)

test.yaml:

apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test.yaml
spec:
  flows:
    - beans:
        - name: weatherEndpoint
          type: org.apache.camel.component.cxf.jaxws.CxfEndpoint
    - route:
        from:
          uri: cxf:bean:weatherEndpoint
          parameters:
            dataFormat: PAYLOAD
            wsdlURL: "https://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php?wsdl"
            portName: s:ndfdXMLPort
            address: "https://graphical.weather.gov:443/xml/SOAP_server/ndfdXMLserver.php"
            serviceName: s:ndfdXML
          steps:
            - log:
                message: "Test"

application.properties:

camel.jbang.project-id=test
camel.jbang.project-name=test
camel.jbang.project-description=test
camel.jbang.gav=org.camel.karavan.demo:test:1.0.0
camel.jbang.runtime=quarkus
camel.jbang.quarkusVersion=2.10.0.Final
camel.jbang.dependencies=mvn:org.apache.camel:camel-cxf-soap:3.18.0

**Comment by davsclaus** [comment]
What namespace do you want to use for `s` ?

**Comment by davsclaus** [comment]
You can try with putting the namespace directly, such as
```
          parameters:
            dataFormat: PAYLOAD
            wsdlURL: "https://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php?wsdl"
            portName: "{https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl}ndfdXMLPort"
            address: "https://graphical.weather.gov:443/xml/SOAP_server/ndfdXMLserver.php"
            serviceName: "{https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl}ndfdXML"
```

**Comment by davsclaus** [comment]
Okay can start it up a bit more, now I have a http vs https error on cxf-jetty

```
camel.jbang.dependencies=camel:cxf-soap,camel:cxf-transport,mvn:org.apache.cxf:cxf-rt-transports-http-jetty:3.5.3
```

**Comment by davsclaus** [comment]
This one works
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test.yaml
spec:
  flows:
    - beans:
      - name: weatherEndpoint
        type: org.apache.camel.component.cxf.jaxws.CxfEndpoint
    - route:
        from:
          uri: cxf:bean:weatherEndpoint
          parameters:
            dataFormat: PAYLOAD
            wsdlURL: "https://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php?wsdl"
            portName: "{https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl}ndfdXMLPort"
            address: "http://localhost:8080/weather"
###            address: "https://graphical.weather.gov:443/xml/SOAP_server/ndfdXMLserver.php"
            serviceName: "{https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl}ndfdXML"
          steps:
            - log:
                message: "Test"
```

And then 
```
camel.jbang.project-id=test
camel.jbang.project-name=test
camel.jbang.project-description=test
camel.jbang.gav=org.camel.karavan.demo:test:1.0.0
camel.jbang.runtime=quarkus
camel.jbang.quarkusVersion=2.11.1.Final
camel.jbang.dependencies=camel:cxf-soap,camel:cxf-transport,mvn:org.apache.cxf:cxf-rt-transports-http-jetty:3.5.3
```
