### ISSUE TITLE
Can't run KameletBinding with the native mode

### ISSUE THREAD

**Issue by bouskaJ** [apache/camel-k#3671]
I am creating the following KameletBinding
```

apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  annotations:
    trait.camel.apache.org/quarkus.package-type: native
  name: test
spec:
  sink:
    properties: {}
    uri: log:info?showStreams=true
  source:
    properties:
      message: "test"
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
```
The KameletBinding gets stuck on the `Creating` phase.
The underlying integration gets stuck on the ` Building Kit ` phase
