### ISSUE TITLE
Improve the user feedback when the integration kit fails

### ISSUE THREAD

**Issue by dmarrazzo** [apache/camel-k#3779]
Hi all, this is a follow up of the issue #3775 
In that issue the Integration Kit was failing with the following error message

```yaml
  failure:
    reason: 'failure while building project: exit status 1'
    recovery:
      attempt: 5
      attemptMax: 5
```

Investigating the issue, we reached the conclusion that the root cause was the presence of two conflicting dependencies:

```
  - camel:micrometer
  - mvn:org.apache.camel.quarkus:camel-quarkus-microprofile-metrics
```

The **goal of the current issue** is to improve the user experience when a similar problem make the integration kit fail.
In fact, from a user perspective the error was too generic and there was no way to retrieve the build process error.

Thank you
