### ISSUE TITLE
Expose runtime details in `kamel version -a -v`

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3836]
It would be nice to expose certain runtime details directly in the `kamel` cli. Right now we are able to get the runtime version. From there, we could dig into the related `CamelCatalog` and extract metadata, ie:
```
kubectl get camelcatalog camel-catalog-1.14.0 -o yaml
...
    metadata:
      camel-quarkus.version: 2.11.0
      camel.version: 3.18.0
      quarkus.version: 2.11.3.Final
    provider: quarkus
    version: 1.14.0
```
In particual, the Camel version could be an intersting information to extract in order to be able to test locally with Camel JBang.
