### ISSUE TITLE
Failure when mounting condifgmap and secrets with the same name

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3980]
If you try to configure camel-k to mount resources with the same name, as example:

```yaml
metadata:
    annotations:
        trait.camel.apache.org/mount.configs: [ "configmap:foo", "secret:foo" ]
```

Then the operator would fail as the generated deployment would become invalid (two volumes with the same name) and the integration would be stuck forever. In such case, the integration should enter the error phase and the failure must be reported to the readiness condition at some point.
