### ISSUE TITLE
Camel K does not automatically add dependency JacksonXML

### ISSUE THREAD

**Issue by astelmashenko** [apache/camel-k#4027]
Here is a route:
```yaml
- route:
    from:
      uri: rest:post:/
      steps:
        - to:
            uri: log:info
        - unmarshal:
            jackson-xml:
              unmarshalType: java.util.Map
        - marshal:
            json:
              library: Jackson
        - setHeader:
            name: ce-source
            expression:
              constant:
                expression: camel-integration
        - setHeader:
            name: ce-type
            expression:
              constant:
                expression: camel.integration.event
        - setHeader:
            name: ce-id
            expression:
              simple:
                expression: ${date:now}
        - to:
            uri: log:info
            parameters:
              showAll: false
              showHeaders: true
              showBody: true
```

It fails to load with error:
```
Unmarshal[org.apache.camel.model.dataformat.JacksonXMLDataFormat@3f4f5330] <<< in route: Route(route1)[From[rest:post:/] -> [To[http://transform-orde/... because of Data format 'jacksonXml' could not be created. Ensure that the data format is valid and the associated Camel component is present on the classpath
```

On JacksonXML page there is dependency section https://camel.apache.org/components/3.18.x/dataformats/jacksonXml-dataformat.html#_dependencies it says that we have to add it to use it. 

Few questions:
- is it a bug?
- if it is by design, then how can we pre-configure default route-dependencies? we use operator, and we allow customer provide only yaml files and do not allow do `kamel run`

Camelk versions tested: 1.9.0 and 1.11.1
