### ISSUE TITLE
Kamelets are tried to unmarshal with old Flow

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4117]
```
$ kamel bind timer-source log-sink -p source.message=hello -n default -p source.period=1000 -p sink.showHeaders=true -o yaml > /tmp/klb.yaml
squake:~/workspace/camel-k [feat/native_as_pod]$ kamel run /tmp/klb.yaml 
Error: json: cannot unmarshal object into Go value of type []v1.Flow
```

**Comment by squakez** [comment]
Not a bug, we cannot run a binding via `kamel run`

**Comment by nf3lix** [comment]
Hi @squakez 
I'm facing the same issue when trying to run an Integration. 

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: sample-route-1
spec:
  flows:
    - route:
        id: route-a1ba
        from:
          uri: kamelet:timer-source
          id: from-8fbf
          parameters:
            message: hello world
            period: 5000
          steps:
            - log:
                message: ${body}
                id: log-d8d4
```
When running `kamel run sample-route-1.yaml` I get the same error ("Error: json: cannot unmarshal object into Go value of type []v1.Flow"). Applying this integration with `kubectl apply -f sample-route-1.yaml` works fine.
Is anyone able to reproduce that behavior?

**Comment by nf3lix** [comment]
Okay, thanks for the clarification. What I don't get then is how to apply traits to Integrations. In most cases this should be possible by providing the corresponding properties in the spec file (as stated here: https://camel.apache.org/camel-k/1.12.x/traits/traits.html). However, I see no possibility to do so for the pod trait, as it is applied by passing a pod template file in the Kamel CLI run-command.
Example: `kamel run integration.groovy --pod-template template.yaml` (see [pod trait documentation](https://camel.apache.org/camel-k/1.12.x/traits/pod.html)). Is it possible to apply pod template file using kubectl? 

Please let me know if I should open a new issue on that.
Thank you for your support so far.

**Comment by squakez** [comment]
The `pod-template` is a special case of a trait. It is really resolved into the Integration `spec.template.spec`. For example, `$ kamel run /tmp/Test.java --pod-template pod.yaml -o yaml` will turn into:

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  annotations:
    camel.apache.org/operator.id: camel-k
  creationTimestamp: null
  name: test
spec:
  sources:
  - content: |
      // camel-k: language=java

      import org.apache.camel.builder.RouteBuilder;

      public class Test extends RouteBuilder {
        @Override
        public void configure() throws Exception {

            // Write your routes here, for example:
            from("timer:java?period=1000")
              .routeId("java")
              .setBody()
                .simple("Hello Camel K from ${routeId}")
              .to("log:info");

        }
      }
    name: Test.java
  template:
    spec:
      containers:
      - env:
        - name: TEST_VARIABLE
          value: hello from the template
        name: integration
        resources: {}
        volumeMounts:
        - mountPath: /var/log
          name: var-logs
      - command:
        - /bin/sh
        - -c
        - while true; do echo $(date -u) 'Content from the sidecar container' > /var/log/file.txt;
          sleep 1;done
        image: busybox
        name: sidecar
        resources: {}
        volumeMounts:
        - mountPath: /var/log
          name: var-logs
      securityContext: {}
      volumes:
      - emptyDir: {}
        name: var-logs
  traits: {}
status: {}
```
You can use `kamel run -o yaml` to verify how most of CLI will resolve into an Integration.
