### ISSUE TITLE
Kamel cli reset/uninstall --all does not clean the camelcatalog

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#4160]
Using the client kamel to remove the operator with the commands `kamel reset` then `kamel uninstall --all` does not remove the camel catalog CR.
It contains a status referencing the builder container availability:
```yaml
status:
  conditions:
  - lastTransitionTime: "2023-03-24T08:17:03Z"
    lastUpdateTime: "2023-03-24T08:17:03Z"
    message: Container image successfully built
    reason: Builder Image
    status: "True"
    type: Ready
  image: 10.109.132.152/default/camel-k-runtime-quarkus-builder:3.20.1-snapshot
  observedGeneration: 1
  phase: Ready
```

When installing new code with `kamel install` on the same kubernetes cluster, the camel catalog CR still exists. The effect is that the builder container is not rebuild by the camel-k operator.

I suggest we remove the camel catalog in the `kamel uninstall --all`. Anything that is against that modification in the new builder design @squakez ?
