### ISSUE TITLE
KameletBinding keep in READY phase even when Camel Pod is not ready

### ISSUE THREAD

**Issue by vaibhavjainwiz** [apache/camel-k#4185]
**Steps to reproduces isssue** :
- Create a `KameletBinding` which reads from Kafka and write to the log.
- Camel `Pod` successfully started and move to `READY` state. 
- `KameletBinding` also move to `READY` phase.
- Kafka connection has been lost in between.
- Camel `Pod` moves to `Not-Ready` state.
- `KameletBinding` keeps in `READY` Phase.

**Expected behaviour** :
`KameletBinding` should move to `FAILED` phase.

**Actual behaviour** :
`KameletBinding` keeps in `READY` Phase.

`KameletBinding` status with successful Kafka conection :
https://gist.github.com/vaibhavjainwiz/2c3dfcbf953855a6dc1c9960531604ba

Camel `Pod` status with successful Kafka conection :
https://gist.github.com/vaibhavjainwiz/0ba14de12a5e7099ae19c1a40cdf00e0

`KameletBinding` status after lost Kafka connection :
https://gist.github.com/vaibhavjainwiz/9032387123afdb56a8ea93914fbdffc5

Camel `Pod` status after lost Kafka connection :
https://gist.github.com/vaibhavjainwiz/15e0769125d150b87baaab0b80b74670

**Comment by vaibhavjainwiz** [comment]
++ @lburgazzoli

**Comment by lburgazzoli** [comment]
I'm not sure if that's actually an error as the phase is ready but there is a condition that highlight the readiness of the KameletBinding/Integration which is inline with what can be observed on pod where phase is `Running` but the `Ready` condition is `False`:

```yaml
status:
  conditions:
    - lastTransitionTime: '2023-03-29T06:50:02Z'
      lastUpdateTime: '2023-03-29T06:50:02Z'
      message: >-
        [Pod mctr-cghts3u8qbfgb8abbbhg-6c77476996-n7kq5 runtime is not ready:
        map[bootstrap.servers:abc.com:443
        check.kind:READINESS client.id:consumer-cghts3u8qbfgb8abbbhg-1
        group.id:cghts3u8qbfgb8abbbhg route.id:cghts3u8qbfgb8abbbhg-source
        topic:abc_topic]]
      reason: RuntimeNotReady
      status: 'False'
      type: Ready
  observedGeneration: 1
  phase: Ready
  replicas: 1
 ```


I think the question is about the semantic we expect from to the phase so I wonder if instead of ready we should use `Running` as for pods but in general I won't rely on the phase field only in order to determine the status of an integration.
