### ISSUE TITLE
Kamel cli fails with wait flag when updating existing Failed integration

### ISSUE THREAD

**Issue by astelmashenko** [apache/camel-k#4201]
Steps to reproduce:

1. Create integration with error, e.g. 
```
- route:
    from:
      uri: timer://tick
      steps:
        - to:
            uri: log:info
      parameters:
        period: 3000
        repeatCount: {{param.count}}
```
2.  Run it `kamel --name test-api-int run integraion.yaml --config file:/my.properties --wait`
3. Observe it failed to deploy
4. Fix integration
```
- route:
    from:
      uri: timer://tick
      steps:
        - to:
            uri: log:info
      parameters:
        period: 3000
        repeatCount: "{{param.count}}"
```
5. Run it with wait flag `kamel --name test-api-int run integraion.yaml --config file:/my.properties --wait`

**Actual behavior**: Observe it failed again
```
Integration "test-api-int" updated
Progress: integration "test-api-int" in phase Error
Error: integration "test-api-int" deployment failed
```
 while it is actually running in k8s in Running phase

**Expected behavior**: kamel run with `--wait` updates integration and completes with no errors
