### ISSUE TITLE
kamelet binding: misleading error condition upon initialization error

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#4229]
According to my understanding, [in case of a failure creating an integration from a kamelet binding](https://github.com/apache/camel-k/blob/d5b9466248fdcc2eedf6489cec978c6b527869ff/pkg/controller/kameletbinding/initialize.go#L52), a condition like the following one will be created:

```yaml
- type: "IntegrationError"
  staus: "False"
  reason: "Couldn't create an Integration custom resource"
  message: "..."
```

This seems to be a little counterintuitive as type is about an error but the status is false, does this mean that this is not an error ? Also it would be better to let the reason to be machine-readable, UpperCamelCase text indicating the reason for the condition's last transition.

Maybe should be better to use the `Ready` condition or as an alternative to have an `IntegrationCreated` one ? 

```yaml
- type: "Ready"
  staus: "False"
  reason: "IntegrationError"
  message: "..."
```

or 

```yaml
- type: "IntegrationCreated"
  staus: "False"
  reason: "Error"
  message: "..."
```

In general conditions must always be present, if not it is assumed to be in an unknown state.
