### ISSUE TITLE
Integration builder can't pull the builder image from the insecure registry

### ISSUE THREAD

**Issue by bouskaJ** [apache/camel-k#4236]
I am working with the local Kind cluster and insecure registry.
My IntegrationPlatform contains
```
 registry:
        address: kind-registry:5000
        insecure: true
```
the operator is able to build and push the builder image to the registry
```
kubectl logs camel-k-operator-588484997d-bbl6f -n global | grep builder                 
{"level":"info","ts":1680783542.057215,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/06 12:19:02 Pushing image kind-registry:5000/camel-k-runtime-quarkus-builder:3.20.1-snapshot (insecure=true)..."}
```

Then I try to run the integration. The Build CR is generated with correct configuration (including the `insecure` tag).
```
kubectl get Build -n test -o yaml

- spectrum:
        baseImage: docker.io/eclipse-temurin:11
        image: kind-registry:5000/test/camel-k-kit-cgnbtkmpn0ns73dn95j0:39242
        name: spectrum
        registry:
          address: kind-registry:5000
          insecure: true
    timeout: 5m0s
    toolImage: kind-registry:5000/camel-k-runtime-quarkus-builder:3.20.1-snapshot
```
but the builder pod fails with
```
kubectl get pods -n test
NAME                                       READY   STATUS                  RESTARTS   AGE
camel-k-kit-cgnbtkmpn0ns73dn95j0-builder   0/1     Init:ImagePullBackOff   0          35m

kubectl get pod camel-k-kit-cgnbtkmpn0ns73dn95j0-builder -o yaml -n test

      state:
        waiting:
          message: 'rpc error: code = Unknown desc = failed to pull and unpack image
            "kind-registry:5000/camel-k-runtime-quarkus-builder:3.20.1-snapshot":
            failed to resolve reference "kind-registry:5000/camel-k-runtime-quarkus-builder:3.20.1-snapshot":
            failed to do request: Head "https://kind-registry:5000/v2/camel-k-runtime-quarkus-builder/manifests/3.20.1-snapshot":
            http: server gave HTTP response to HTTPS client'
          reason: ErrImagePull
    phase: Pending
    podIP: 10.244.0.40
```
