### ISSUE TITLE
Camel-k does not terminate previous pods after updating of integration

### ISSUE THREAD

**Issue by astelmashenko** [apache/camel-k#4333]
I run camel integration using kamel cli, it runs successfully. Then I change property file and run integration again and kamel does not update istead it runs another integration pod.

k8s version: 1.24
kamel: 1.12
knative: 1.3

Steps to reproduce:

integration.yaml:
```
- route:
    from:
      uri: timer://tick
      steps:
        - to:
            uri: "log:info-{{param.count}}"
      parameters:
        period: 3000
        repeatCount: "{{param.count}}"
```
and `lab.properties`:
```
param.count=2
```

1. Then run integration: 
```
kamel run \
  --trait health.enabled=true \
  --trait knative-service.min-scale=1 \
  --trait knative-service.max-scale=3 \
  --trait knative-service.enabled=true \
  --trait knative-service.autoscaling-class=hpa.autoscaling.knative.dev \
  --trait knative-service.autoscaling-metric=cpu \
  --trait knative-service.autoscaling-target=70 \
  --config file:/path/to/dir/lab.properties \
  integration.yaml \
  --name my-test \
  --namespace myns
```
2. Update `lab.properties`:
```
param.count=5
```
3. And run integration again with the same command
4. Observe two pods are running
```
my-test-00001-deployment-6fff48cbbd-cxwxf
my-test-00002-deployment-3af48c..
```
5. `kamel get -n myns` shows only one integration
