### ISSUE TITLE
Binding from a Strimzi CR is not properly decoded

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#4336]
I've created the following `KameletBinding` using a pre-built container image that should bridge Kafka and Slack.

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-to-slack
  annotations:
    "trait.camel.apache.org/container.image": "quay.io/rhoas/cos-connector-slack:main-65c1e78930846874d2c0414db67bcc60302e9943"
    "trait.camel.apache.org/kamelets.enabled": "false"
    "trait.camel.apache.org/jvm.enabled": "false"
    "trait.camel.apache.org/mount.configs": "[ \"secret:slack\" ]"
spec:
  source:
    ref:
      kind: Kafka
      apiVersion: kafka.strimzi.io/v1beta2
      name: rhoc-cluster
    properties:
      topic: datagen-out
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: slack-sink
    properties:
      channel: "#demo"
      webhookUrl: "foo/bar"
 ```
 
 However in the resulting integration code, the Kafka ref is translated to Knative
 
 ```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-slack-source-000
data:
  content: |
    - route:
        from:
          steps:
          - to: kamelet:cos-slack-sink/sink
          uri: knative:endpoint/rhoc-cluster?apiVersion=kafka.strimzi.io%2Fv1beta2&kind=Kafka&topic=datagen-out
        id: binding
```

I would expect this binding to decode the Kafka ref to a kafka endpoint/kamelet in the generated code
