### ISSUE TITLE
Add support for Strimzi Kafka in KameletBinding/Pipe

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#4337]
With https://github.com/apache/camel-k/issues/1686, support for Strimzi's KafkaTopic has been added, however it would be nice to have support for Strimzi's Kafka CRD also, something like:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: twitter-stream-binding
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: twitter-stream
    properties:
      keyword: Camel K
      secret: ...
  sink:
    ref:
      apiVersion: kafka.strimzi.io/v1beta1
      kind: Kafka
      name: my-cluster
    properties:
      topic: "my-topic"
 ```
 
 This way a user could override the topic, i.e. in a step to perform some sort of CBR among topics
