### ISSUE TITLE
Support for Istio sidecar injection for Kamelets data plane

### ISSUE THREAD

**Issue by pierDipi** [apache/camel-k#4347]
I have a use case where I want to use Istio to enforce mTLS communication between Kamelets and other workloads (Knative components, etc) in an OpenShift cluster and I've not found a way to add istio injection annotations to a given Kamelet data plane (ie `sidecar.istio.io/inject: true`).

In Istio, there is an option to inject sidecars into every pod in a given namespace (see https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy), however:
- [that's not supported by OpenShift Service Mesh](https://docs.openshift.com/container-platform/4.11/service_mesh/v2x/ossm-vs-community.html#ossm-automatic-injection_ossm-vs-istio)
- namespace-level injection is sometimes not desirable since that impacts other workloads of a given namespace

Therefore I need a way to add the `sidecar.istio.io/inject: true` to a given Kamelet Source and Sink data plane.

Is there any existing way to achieve this?

**Comment by lburgazzoli** [comment]
It should be possible to add annotation with something like that:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-text-source-to-channel
  annotations:
      # istio
      sidecar.istio.io/inject: true
      # instruct camel-k to propagate the annotation to children
      trait.camel.apache.org/owner.target-annotations: '[ "sidecar.istio.io/inject" ]'
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: telegram-text-source
    properties:
      botToken: the-token-here
  sink: 
    ref:
      kind: InMemoryChannel
      apiVersion: messaging.knative.dev/v1
      name: messages
```

However, camel-k would leverage i.e. knative sink binding to get the actual endpoint to invoke so, this would only work if the injected url is "sidecar" aware.

We could also think to add some native support for istio/service-mesh in camel-k
