### ISSUE TITLE
pod-template with knative in rest integration

### ISSUE THREAD

**Issue by milank78git** [apache/camel-k#4484]
Hi,

I have integration example with rest and used pod-template. 

```
> `apiVersion: camel.apache.org/v1
> kind: Integration
> metadata:
>   annotations:
>     camel.apache.org/operator.id: camel-k
>   creationTimestamp: null
>   name: rest
>   namespace: default
> spec:
>   serviceAccountName: camel-k-sa
>   sources:
>   - content: "/**\r\n * \r\n *    curl http://XXX/hello\r\n *\r\n * \r\n */\r\n\r\n//
>       camel-k: language=java trait=logging.enabled=true\r\nimport org.apache.camel.CamelContext;\r\nimport
>       org.apache.camel.Exchange;\r\nimport org.apache.camel.Processor;\r\n\r\npublic
>       class RestDSL extends org.apache.camel.builder.RouteBuilder {\r\n    @Override\r\n
>       \   public void configure() throws Exception {\r\n        rest()\r\n            .get(\"/hello\")\r\n
>       \               .to(\"direct:hello\");\r\n\r\n        from(\"direct:hello\")\r\n
>       \           .setHeader(Exchange.CONTENT_TYPE, constant(\"text/plain\"))\r\n
>       \           .log(\"Hello World 2\")\r\n            .log(String.valueOf(simple(\"headers:${headers}\")))\r\n
>       \           .process(new Processor(){\r\n                @Override\r\n                public
>       void process(Exchange exchange) throws Exception {\r\n                    CamelContext
>       ctx = exchange.getContext();\r\n                    System.out.println(\"can
>       be breakpoint on this line :\" + ctx.getName());\r\n                }\r\n            })\r\n
>       \           .transform().simple(\"Hello World\");\r\n    }\r\n}"
>     name: rest.groovy
>   template:
>     spec:
>       containers:
>       - env:
>         - name: TEST_VARIABLE
>           value: hello from the template
>         name: integration
>         resources: {}
>         volumeMounts:
>         - mountPath: /var/log
>           name: var-logs
>       - command:
>         - /bin/sh
>         - -c
>         - while true; do echo $(date -u) 'Content from the sidecar container' > /var/log/file.txt;
>           sleep 1;done
>         image: busybox
>         name: sidecar
>         resources: {}
>         volumeMounts:
>         - mountPath: /var/log
>           name: var-logs
>       securityContext: {}
>       volumes:
>       - emptyDir: {}
>         name: var-logs
>   traits:
>     logging:
>       enabled: true`
```

Integration still Deploying in camel-operator logs is:

```
{"level":"error","ts":1686654509.7504678,"msg":"Reconciler error","controller":"integration-controller","controllerGroup":"camel.apache.org","controllerKind":"Integration","Integration":{"name":"rest","namespace":"default"},"namespace":"default","name":"rest","reconcileID":"a1d576bd-97b3-4d2f-9f87-c06872c9dfe8","error":"error executing post actions: error during apply resource: default/rest: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].emptyDir, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret\nmissing field(s): spec.template.spec.containers[*].ports\nmountPath \"/var/log\" is a reserved path: spec.template.spec.containers[0].volumeMounts[0].mountPath, spec.template.spec.containers[1].volumeMounts[0].mountPath","errorVerbose":"error during apply resource: default/rest: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].emptyDir, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret\nmissing field(s): spec.template.spec.containers[*].ports\nmountPath \"/var/log\" is a reserved path: spec.template.spec.containers[0].volumeMounts[0].mountPath, spec.template.spec.containers[1].volumeMounts[0].mountPath\nerror executing post actions\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:66\ngithub.com/apache/camel-k/pkg/controller/integration.(*monitorAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integration/monitor.go:114\ngithub.com/apache/camel-k/pkg/controller/integration.(*reconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integration/integration_controller.go:361\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:70\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234\nruntime.goexit\n\truntime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
{"level":"debug","ts":1686654509.7507555,"logger":"events","msg":"Cannot reconcile Integration rest: error executing post actions: error during apply resource: default/rest: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].emptyDir, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret\nmissing field(s): spec.template.spec.containers[*].ports\nmountPath \"/var/log\" is a reserved path: spec.template.spec.containers[0].volumeMounts[0].mountPath, spec.template.spec.containers[1].volumeMounts[0].mountPath","type":"Warning","object":{"kind":"Integration","namespace":"default","name":"rest","uid":"13187085-8a66-4b66-8741-9cb7e2f180e9","apiVersion":"camel.apache.org/v1","resourceVersion":"36158776"},"reason":"IntegrationError"}
{"level":"debug","ts":1686654509.751191,"logger":"events","msg":"C**annot reconcile Integration rest: error executing post actions: error during apply resource: default/rest: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].emptyDir, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret\nmissing field(s): spec.template.spec.containers[*].ports\nmountPath \"/var/log\" is a reserved path: spec.template.spec.containers[0].volumeMounts[0].mountPath, spec.template.spec.containers[1].volumeMounts[0].mountPath","type":"Warning","object":{"kind":"Integration","namespace":"default","name":"rest","uid":"13187085-8a66-4b66-8741-9cb7e2f180e9","apiVersion":"camel.apache.org/v1","resourceVersion":"36158776"},"reason":"IntegrationError"}
{"level":"info","ts":1686654509.7566524,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"default","request-name":"rest"}**
```

If I try your example   https://camel.apache.org/camel-k/1.12.x/traits/pod.html  , the container will start.

**Comment by squakez** [comment]
It seems the problem is in the usage of some reserved path:
```
validation failed: expected exactly one, got neither: spec.template.spec.volumes[0].configMap, spec.template.spec.volumes[0].emptyDir, spec.template.spec.volumes[0].projected, spec.template.spec.volumes[0].secret\nmissing field(s): spec.template.spec.containers[*].ports\nmountPath \"/var/log\" is a reserved path
```

**Comment by milank78git** [comment]
@squakez 
Thanks your answer .
I'm sorry, but I don't understand at all. If I use this integration, it will lead to deployment. 

```
> from('file:///var/log')
>  .convertBodyTo(String.class)
>  .setBody().simple('${body}:  {{TEST_VARIABLE}} ')
>  .log('${body}')
> 
```

However, if I add a route for the REST, it will result in the mentioned error. If I only want REST, the same applies

```
> 
> import org.apache.camel.CamelContext;
> import org.apache.camel.Exchange;
> import org.apache.camel.Processor;
> 
> public class RestDSL extends org.apache.camel.builder.RouteBuilder {
>     @Override
>     public void configure() throws Exception {
>         from("file:///var/log")
>             .convertBodyTo(String.class)
>             .setBody().simple("${body}: {{TEST_VARIABLE}} ")
>             .log("${body}");
> 
>         rest()
>             .get("/hello")
>             .to("direct:hello");
> 
>         from("direct:hello")
>             .setHeader(Exchange.CONTENT_TYPE, constant("text/plain"))
>             .log("Hello World 2")
>             .log(String.valueOf(simple("headers:${headers}")))
>             .process(new Processor(){
>                 @Override
>                 public void process(Exchange exchange) throws Exception {
>                     CamelContext ctx = exchange.getContext();
>                     System.out.println("can be breakpoint on this line :" + ctx.getName());
>                 }
>             })
>             .transform().simple("Hello World");
>     }
> }
> 
```
pod-template is the same

```
> template.yaml
> containers:
>   - name: integration
>     env:
>       - name: TEST_VARIABLE
>         value: "hello from the template"
>     volumeMounts:
>       - name: var-logs
>         mountPath: /var/log
>   - name: sidecar
>     image: busybox
>     command: [ "/bin/sh" , "-c", "while true; do echo $(date -u) 'Content from the sidecar container' > /var/log/file.txt; sleep 1;done" ]
>     volumeMounts:
>       - name: var-logs
>         mountPath: /var/log
> volumes:
>   - name: var-logs
>     emptyDir: { }
```

Why does adding or change REST integration result in a path error?

**Comment by milank78git** [comment]
@squakez Could you take a look at this, please?
I trying two integrations :
First is basic route
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  annotations:
    camel.apache.org/operator.id: camel-k
  creationTimestamp: null
  name: example
  namespace: default
spec:
  serviceAccountName: microservice
  sources:
  - content: "\r\n// camel-k: language=java\r\n\r\nimport org.apache.camel.builder.RouteBuilder;\r\n\r\npublic
      class Basic extends RouteBuilder {\r\n  @Override\r\n  public void configure()
      throws Exception {\r\n\r\n      from(\"timer:java?period=1000\")\r\n        .setHeader(\"example\")\r\n
      \         .constant(\"Java\")\r\n        .setBody()\r\n          .simple(\"Hello
      World! Camel K route written in ${header.example}.\")\r\n        .to(\"log:info\");\r\n
      \     \r\n  }\r\n}"
    name: example.groovy
  template:
    spec:
      containers:
      - env:
        - name: TEST_VARIABLE
          value: hello from the template
        name: integration
        resources: {}
      initContainers:
      - command:
        - /bin/sh
        - -c
        - 'echo $(date -u) ''Content from the sidecar container'' '
        image: busybox:1.28
        name: sidecar
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 25Mi
      securityContext: {}
  traits:
    container:
      limitCPU: 1000m
      limitMemory: 1Gi
      requestCPU: 1000m
      requestMemory: 1Gi
status: {}

```

This integration is OK Integration running and InitContainer is Completed Integration pod is running, but if create integration with rest-integration  with same iniContainer return error 

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  annotations:
    camel.apache.org/operator.id: camel-k
  creationTimestamp: null
  name: rest
  namespace: default
spec:
  serviceAccountName: microservice
  sources:
  - content: "import org.apache.camel.CamelContext;\r\nimport org.apache.camel.Exchange;\r\nimport
      org.apache.camel.Processor;\r\n\r\npublic class RestDSL extends org.apache.camel.builder.RouteBuilder
      {\r\n    @Override\r\n    public void configure() throws Exception {\r\n        from(\"file:///var/log\")\r\n
      \           .convertBodyTo(String.class)\r\n            .setBody().simple(\"${body}:
      {{TEST_VARIABLE}}\")\r\n            .log(\"${body}\");\r\n\r\n        rest()\r\n
      \           .get(\"/hello\")\r\n            .to(\"direct:hello\");\r\n\r\n        from(\"direct:hello\")\r\n
      \           .setHeader(Exchange.CONTENT_TYPE, constant(\"text/plain\"))\r\n
      \           .log(\"Hello World 2\")\r\n            .log(String.valueOf(simple(\"headers:${headers}\")))\r\n
      \           .process(new Processor() {\r\n                @Override\r\n                public
      void process(Exchange exchange) throws Exception {\r\n                    CamelContext
      ctx = exchange.getContext();\r\n                    System.out.println(\"can
      be breakpoint on this line :\" + ctx.getName());\r\n                }\r\n            })\r\n
      \           .transform().simple(\"Hello World\");\r\n    }\r\n}\r\n"
    name: rest.groovy
  template:
    spec:
      containers:
      - env:
        - name: TEST_VARIABLE
          value: hello from the template
        name: integration
        resources: {}
      initContainers:
      - command:
        - /bin/sh
        - -c
        - 'echo $(date -u) ''Content from the sidecar container'' '
        image: busybox:1.28
        name: sidecar
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 25Mi
      securityContext: {}
  traits:
    container:
      limitCPU: 1000m
      limitMemory: 1Gi
      requestCPU: 1000m
      requestMemory: 1Gi
status: {}
```


{"level":"error","ts":1686915920.7107453,"msg":"Reconciler error","controller":"integration-controller","controllerGroup":"camel.apache.org","controllerKind":"Integration","Integration":{"name":"rest","namespace":"default"},"namespace":"default","name":"rest","reconcileID":"22347223-9787-4e99-8373-816798a37d00","error":"error executing post actions: error during apply resource: default/rest: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: must not set the field(s): spec.template.spec.initContainers\npod spec support for init-containers is off, but found 1 init containers: ","errorVerbose":"error during apply resource: default/rest: admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: must not set the field(s): spec.template.spec.initContainers\npod spec support for init-containers is off, but found 1 init containers: \nerror executing post actions\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:66\ngithub.com/apache/camel-k/pkg/controller/integration.(*monitorAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integration/monitor.go:114\ngithub.com/apache/camel-k/pkg/controller/integration.(*reconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integration/integration_controller.go:361\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:70\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234\nruntime.goexit\n\truntime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}

I try change initContainer in podTemplate but error 
**admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: missing field(s): spec.template.spec.containers[*].ports"**

I added ports to the template

```
containers:
  - name: integration
    env:
      - name: TEST_VARIABLE
        value: "hello from the template"
    ports:
      - containerPort: 8080
        protocol: TCP
  - name: sidecar
    image: busybox:1.28
    command: [ "/bin/sh" , "-c", "echo $(date -u) 'Content from the sidecar container' " ]
    resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 25Mi
```

Container is running. 
Why must definition for container ports and why not used initContainer when used Rest-Integration in knative ? 
And Can you please add support for downwardapi

**Comment by claudio4j** [comment]
@milank78git you have knative installed and available in camel-k-operator namespace, in this case camel-k-operator creates a knative service deployment, for this reason there must be some knatve service webhook validation in place to actually validate the container yaml snippet. I am not familiar with knative, but this is definitely some knative validation going on.

If you want to disable knative service you can use the knative service trait to disable it: `-t knative-service.enabled=false`

I changed the pod template yaml to pass the validation webhook

```
containers:
  - name: integration
    env:
      - name: TEST_VARIABLE
        value: "hello from the template"
    volumeMounts:
      - name: var-logs
        mountPath: /var/tmp
    ports:
    - containerPort: 12458
      protocol: TCP
  - name: sidecar
    image: busybox
    command: [ "/bin/sh" , "-c", "while true; do echo $(date -u) 'Content from the sidecar container' > /var/tmp/file.txt; sleep 1;done" ]
    volumeMounts:
      - name: var-logs
        mountPath: /var/tmp
volumes:
  - name: var-logs
    emptyDir:
      sizeLimit: 10Mi
```
