### ISSUE TITLE
Let Camel framework manage Kamelets

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4618]
Kamelets resolution is still done in the old fashioned way:
```
[1] 2023-07-27 07:24:31,641 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='camel-k-embedded-flow', language='yaml', type='source', location='file:/etc/camel/sources/camel-k-embedded-flow.yaml', }
[1] 2023-07-27 07:24:31,678 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='log-sink', language='yaml', type='source', location='file:/etc/camel/sources/log-sink.yaml', }
[1] 2023-07-27 07:24:31,683 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='timer-source', language='yaml', type='source', location='file:/etc/camel/sources/timer-source.yaml', }
```
The runtime takes care to do the work which supposedly has to be done by the framework. This was fine in the early days of Kamelets, but since now Kamelets are a Camel thing, we need to let it manage them accordingly.

**Comment by lburgazzoli** [comment]
can you add more detail about then issue here ? 
like what happen today under the hoods and what we expect to happen ?

**Comment by squakez** [comment]
Sure. Right now, the operator is not deploying a Kamelet, but it transform the Kamelet into a route template. For example:
```
k get cm timer-source-to-log-sink-kamelet-log-sink-template -o yaml
apiVersion: v1
data:
  content: |
    - routeTemplate:
        from:
          steps:
          - to:
              parameters:
                level: '{{?level}}'
                logMask: '{{?logMask}}'
                marker: '{{?marker}}'
                multiline: '{{?multiline}}'
                showAllProperties: '{{?showAllProperties}}'
                showBody: '{{?showBody}}'
                showBodyType: '{{?showBodyType}}'
                showCachedStreams: '{{?showCachedStreams}}'
                showExchangePattern: '{{?showExchangePattern}}'
                showHeaders: '{{?showHeaders}}'
                showProperties: '{{?showProperties}}'
                showStreams: '{{?showStreams}}'
              uri: log:{{loggerName}}
          uri: kamelet:source
        id: log-sink
kind: ConfigMap
```
This is working, but I think that we need instead to deploy the Kamelet spec and let the runtime to handle such Kamelet with the mechanism expected by the framework.

Hope it clarifies.
