### ISSUE TITLE
camel-k installed with helm does not create cluster role for pipes and kameletbindings

### ISSUE THREAD

**Issue by pknetbcn** [apache/camel-k#4629]
I'm installing camel-k version 2.0.0 using helm with the value operator.global=true.

The operator is continuosly restarting, showing errors saying that the user cannot list resource "pipes" neither "kameletbindings".

If I create manually these files, the operator is maitained stable, at least without any integration yet:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-operator-custom
  labels:
    app: "camel-k"
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - camel.apache.org
    resources:
      - pipes
      - kameletbindings
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-operator-custom
  labels:
    app: "camel-k"
subjects:
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: kamelk
roleRef:
  kind: ClusterRole
  name: camel-k-operator-custom
  apiGroup: rbac.authorization.k8s.io
```
