### ISSUE TITLE
Set up same golang version for github actions

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4641]
We don't have it set in all workflows. It would be convenient to define it in each workflow for consistency.

**Comment by gansheer** [comment]
I'll take care of it.

**Comment by lburgazzoli** [comment]
the go version can be set to use the version defined in the go.mod file, like:
```yaml
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
 ```
