### ISSUE TITLE
Kamelet - Inject secret in Azure KeyVault Trait

### ISSUE THREAD

**Issue by jorgebg90** [apache/camel-k#4743]
### Requirement

As a User
I want to be able to use a configmap/secret in _azure-key-vault.client-secret_ field for Azure KeyVault trait
When I deploy a Kamelet Integration / Kamelet pipe in order to hide the real Azure Key Vault credentials.

### Problem

When I was trying to deploy my current Kamelet Pipe into our cluster through Github repository I realize that I couldn't hide the azure-key-vault.client-secret through a secret or configmap:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  namespace: default
  name: currentPipe
  annotations:
    trait.camel.apache.org/logging.level: DEBUG
    trait.camel.apache.org/azure-key-vault.enabled: "true"
    trait.camel.apache.org/azure-key-vault.tenant-id: "aaaa-bbbb-ccc-ddd-eee"
    trait.camel.apache.org/azure-key-vault.vault-name: "currentvaultName"
    trait.camel.apache.org/azure-key-vault.client-id: "azurekeyvaultClientId"
    trait.camel.apache.org/azure-key-vault.client-secret: "K8S_SECRET/CONFIGMAP"
spec:
  replicas: 1
  source:
```

### Proposal

As I was talking previously through Zulip there is a similar solution for other traits specified in this PR (thanks to @oscerd  and @squakez for this information) :

https://github.com/apache/camel-k/pull/4568
