### ISSUE TITLE
Error log traces after integration error

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4781]
When an Integration ends up in Error state, the operator provides some error log traces, likely because it keeps trying to reconcile trying to apply trait:
```
camel-k-operator-7856cb497b-smfkq camel-k-operator {"level":"info","ts":"2023-09-29T13:57:50Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"default","request-name":"test","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"test","phase-from":"Building Kit","phase-to":"Error"}
camel-k-operator-7856cb497b-smfkq camel-k-operator {"level":"error","ts":"2023-09-29T13:57:50Z","msg":"Reconciler error","controller":"integration-controller","controllerGroup":"camel.apache.org","controllerKind":"Integration","Integration":{"name":"test","namespace":"default"},"namespace":"default","name":"test","reconcileID":"e482a7a2-803d-403e-822e-72d7c627257a","error":"error during trait customization: unable to find integration container: test","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:226"}
camel-k-operator-7856cb497b-smfkq camel-k-operator {"level":"error","ts":"2023-09-29T13:57:50Z","msg":"Reconciler error","controller":"integr
...
```
Altough it's a cosmetic issue, we should get rid of it to improve the observability and the clean logging of the operator.

**Comment by gansheer** [comment]
I'll look into it if you are not already on it.

**Comment by gansheer** [comment]
From what I gathered this happens when the integration kit did not manage to build correctly and ends up in failure after 5 failed builds:
* integrationkit:
```yaml
status:
  conditions:
  - lastTransitionTime: "2023-10-02T13:40:05Z"
    lastUpdateTime: "2023-10-02T13:40:05Z"
    message: IntegrationPlatform (camel-k)
    reason: IntegrationPlatformAvailable
    status: "True"
    type: IntegrationPlatformAvailable
  digest: vU8KNPqHgejR-MytUTqoY4dbP4gi3nktmOKfeEGJdYco
  failure:
    reason: 'failure while building project: : exit status 1'
    recovery:
      attempt: 5
      attemptMax: 5
      attemptTime: "2023-10-02T13:43:32Z"
    time: "2023-10-02T13:41:17Z"
  observedGeneration: 1
  phase: Error
  platform: camel-k
  runtimeProvider: quarkus
  runtimeVersion: 3.2.0
  version: 2.1.0-SNAPSHOT
```
* integration:
```yaml
status:
  conditions:
  - firstTruthyTime: "2023-10-02T13:40:05Z"
    lastTransitionTime: "2023-10-02T13:40:05Z"
    lastUpdateTime: "2023-10-02T13:40:05Z"
    message: default/camel-k
    reason: IntegrationPlatformAvailable
    status: "True"
    type: IntegrationPlatformAvailable
  - lastTransitionTime: "2023-10-02T13:40:05Z"
    lastUpdateTime: "2023-10-02T13:43:35Z"
    message: integration kit default/kit-ckdcgdf5tdfig6lsvu30 is in state "Error"
    reason: IntegrationKitAvailable
    status: "False"
    type: IntegrationKitAvailable
  dependencies:
  - camel:timer
  - mvn:jakarta.annotation:jakarta.annotation-api:1.3.5.redhat-00002
  - mvn:org.apache.camel.k:camel-k-runtime
  - mvn:org.apache.camel.quarkus:camel-quarkus-java-joor-dsl
  digest: vjUJOZpjQiNq3c7_97pi0DdC-HixiwRz_wSyy7OIHoCE
  integrationKit:
    name: kit-ckdcgdf5tdfig6lsvu30
    namespace: default
  lastInitTimestamp: "2023-10-02T13:40:05Z"
  observedGeneration: 1
  phase: Error
  platform: camel-k
  profile: Kubernetes
  runtimeProvider: quarkus
  runtimeVersion: 3.2.0
  version: 2.1.0-SNAPSHOT
```

What I am trying to understand is how the integration's lifecycle should go on in this state:
* should we be able to identify that a kit already exists and is in error before or during this code:
https://github.com/apache/camel-k/blob/46001e85280ef904549053e2eb4fff5070dd0e00/pkg/controller/integration/monitor.go#L115-L119
* Can the integration kit in failure could end up in success ? Or would it always end up as new integration kit ?
