### ISSUE TITLE
Knative minikube service failure

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#482]
When running a route like 

```from("knative:channel/sortucase")
  .convertBodyTo(String.class)
  .to("log:info");
```

The knative service fails to deploy and describing the knative service shows this error :

```
  conditions:
  - lastTransitionTime: "2019-02-22T11:32:40Z"
    message: 'Revision "print-00001" failed with message: "Unable to fetch image \"10.100.191.95/knativetutorial/camel-k-ctx-bhntq7a6pkmls1neqo4g:8281\":
      Get https://10.100.191.95/v2/: dial tcp 10.100.191.95:443: connect: connection
      timed out".'
    reason: RevisionFailed
    severity: Error
    status: "False"
    type: ConfigurationsReady
  -
```
