### ISSUE TITLE
Ability to override resources for the quarkus-native task

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#4956]
### Requirement

As a developer, I'm trying to speed up the native build process by providing more resources to the quarkus-native build task.

### Problem

I created an Integration with the following traits:
```
  traits:
    quarkus:
      buildMode:
        - native
    builder:
      tasksRequestCPU:
      - "quarkus-native:2000m"
      tasksRequestMemory:
      - "quarkus-native:8Gi"
```
in order to provide more resources to the quarkus-native phase of the build process.

However, the build pod was still created with 1 cpu and 4Gi:

```
  - command:
    - /bin/bash
    - -c
    - cd maven && ./mvnw package -Dquarkus.package.type=native --global-settings settings.xml
    image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.0-jdk-17
    name: quarkus-native
    resources:
      requests:
        cpu: "1"
        memory: 4Gi
    volumeMounts:
    - mountPath: /builder/kit-clktoa002nnjtch78vg0
      name: camel-k-builder
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gdlpv
      readOnly: true
    workingDir: /builder/kit-clktoa002nnjtch78vg0
```

### Proposal

The code might just check if there is configuration for the quarkus-native phase for any of the cpu/memory request or limit configurations and not use the default one if found.
