### ISSUE TITLE
Fail to run route with toD

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#4972]
### What happened?

Given a route with a dynamic endpoint as `toD("{{foo.myroute.endpoint}}/test")` the camel-k-operator fails with `error during trait customization: kamelets trait configuration failed: component not found for uri \"{{foo.myroute.endpoint}}/test\"`

https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Help.20with.20.60--build-property.60/near/406416737

### Steps to reproduce

Run the route
```
- from:
    uri: "timer:test"
    steps:
      - setBody:
          simple: "{{foo.application.custom}}"
      - toD: "{{foo.myroute.endpoint}}/test"
```

given the properties file
```
foo.application.custom = my-custom-value
foo.myroute.endpoint = http://my-site.com
```
