### ISSUE TITLE
Camel-K doesn't create the Ingress resource although it is enabled in the Traits using Pipe or KameletBinding

### ISSUE THREAD

**Issue by saion-chatterjee** [apache/camel-k#5044]
### What happened?

The following Pipe creates a Service **but the ingress is not created** although it is enabled directly in the traits spec.

Nginx is annotated as the default ingressClass in the cluster.

Environment: _AWS EKS_

```
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: webhook-ingress-example
spec:
  integration:
    traits:
      ingress:
        host: example.dev.mydomain.com
        auto: True
        enabled: True
      service:
        enabled: True
        type: ClusterIP
  sink:
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: kafka-not-secured-sink
    properties:
      bootstrapServers: "kafkacluster.example.svc.cluster.local:9092"
      topic: camel-k-test
  source:
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: webhook-source
```

Actual Output:
- Pod is created and healthy
- Service is created as clusterIP
- Endpoint is created
- **Ingress is not created**

How can we create an Ingress for the webhook-source? Please advice us.

### Camel K version

2.2.0-nightly

**Comment by lburgazzoli** [comment]
you should set `auto` to `false` otherwise camel-k would try to determine if the `source` is an http endpoint, it does not automatically create an ingress for other protocols

**Comment by saion-chatterjee** [comment]
> you should set `auto` to `false` otherwise camel-k would try to determine if the `source` is an http endpoint, it does not automatically create an ingress for other protocols

Tried this but still Ingress doesn't show up. But I have an interesting finding: The same Pipe CR is able to create an Ingress **when tested inside a local Kind cluster**. In AWS EKS, this same configuration is silently failing.

I also checked the IntegrationPlatform and both my local and eks have cluster:kubernetes

**Comment by lburgazzoli** [comment]
can you provide the status of the related `Integration` resource ?

**Comment by saion-chatterjee** [comment]
> can you provide the status of the related `Integration` resource (`kubect get -o yaml integration webhook-ingress-example`) ?

@lburgazzoli Here it is. I can see a message: explicitly disabled by the user reason: masterTraitConfiguration. Could this be the issue? How can I enable it again? 

Note: I simplified the example by using a log-sink instead of kafka.

```
status:
  capabilities:
    - platform-http
  conditions:
    - firstTruthyTime: '2024-01-10T09:13:13Z'
      lastTransitionTime: '2024-01-10T09:13:13Z'
      lastUpdateTime: '2024-01-10T09:13:13Z'
      message: default/camel-k
      reason: IntegrationPlatformAvailable
      status: 'True'
      type: IntegrationPlatformAvailable
    - firstTruthyTime: '2024-01-10T09:13:13Z'
      lastTransitionTime: '2024-01-10T09:13:13Z'
      lastUpdateTime: '2024-01-10T09:13:13Z'
      message: >-
        kamelets [log-sink,webhook-source] found in
        (Kubernetes[namespace=default], Empty[]) repositories
      reason: KameletsAvailable
      status: 'True'
      type: KameletsAvailable
    - firstTruthyTime: '2024-01-10T09:13:13Z'
      lastTransitionTime: '2024-01-10T09:13:13Z'
      lastUpdateTime: '2024-01-10T09:13:13Z'
      message: explicitly disabled by the user
      reason: masterTraitConfiguration
      status: 'True'
      type: TraitInfo
    - firstTruthyTime: '2024-01-10T09:13:13Z'
      lastTransitionTime: '2024-01-10T09:13:13Z'
      lastUpdateTime: '2024-01-10T09:13:13Z'
      message: kit-cmf5bii4ev80p5ds6rg0
      reason: IntegrationKitAvailable
      status: 'True'
      type: IntegrationKitAvailable
    - firstTruthyTime: '2024-01-10T09:13:13Z'
      lastTransitionTime: '2024-01-10T09:13:13Z'
      lastUpdateTime: '2024-01-10T09:13:13Z'
      message: deployment name is webhook-ingress-example
      reason: DeploymentAvailable
      status: 'True'
      type: DeploymentAvailable
    - firstTruthyTime: '2024-01-10T09:13:13Z'
      lastTransitionTime: '2024-01-10T09:13:13Z'
      lastUpdateTime: '2024-01-10T09:13:13Z'
      message: webhook-ingress-example(http/80) -> integration(http/8080)
      reason: ServiceAvailable
      status: 'True'
      type: ServiceAvailable
    - firstTruthyTime: '2024-01-10T09:13:16Z'
      lastTransitionTime: '2024-01-10T09:13:16Z'
      lastUpdateTime: '2024-01-10T09:13:16Z'
      message: 1/1 ready replicas
      reason: DeploymentReady
      status: 'True'
      type: Ready
  dependencies:
    - camel:kamelet
    - camel:log
    - camel:platform-http
    - mvn:org.apache.camel.k:camel-k-runtime
    - mvn:org.apache.camel.quarkus:camel-quarkus-platform-http
    - mvn:org.apache.camel.quarkus:camel-quarkus-yaml-dsl
  digest: vWGa1YDRdmmh4Dk1V1wElxzAyIF87K_S_Pi3ySUqArSg
  generatedSources:
    - content: |
        - route:
            from:
              steps:
              - to: kamelet:log-sink/sink
              uri: kamelet:webhook-source/source
            id: binding
      name: camel-k-embedded-flow.yaml
    - contentKey: content
      contentRef: webhook-ingress-example-kamelet-log-sink-template
      from-kamelet: true
      language: yaml
      name: log-sink.yaml
    - contentKey: content
      contentRef: webhook-ingress-example-kamelet-webhook-source-template
      from-kamelet: true
      language: yaml
      name: webhook-source.yaml
  image: >-
    common-camel-k-registry.eventinghub.dev.railigent.com/default/camel-k-kit-cmf5bii4ev80p5ds6rg0@sha256:611bc03f05c8db8bbe29326c89643462d1269e9cade02780139ecb7772cc1d45
  integrationKit:
    name: kit-cmf5bii4ev80p5ds6rg0
    namespace: default
  lastInitTimestamp: '2024-01-10T09:13:13Z'
  observedGeneration: 1
  phase: Running
  platform: camel-k
  profile: auto
  replicas: 1
  runtimeProvider: quarkus
  runtimeVersion: 3.2.0
  selector: camel.apache.org/integration=webhook-ingress-example
  version: 2.2.0-nightly
```
