### ISSUE TITLE
Ability to set different resources for jvm and native containers when both are used in the same Integration

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5065]
### Requirement

I'm trying to reduce the memory consumption of my Integrations by using native builds and setting low values on the Container trait. However, as the native builder takes a longer time to run, I'm configuring the Quarkus trait to build the jvm pod and replace it later with the native pod.
As the Container trait configuration is used for both integrations, I have to provide more resources as required by the jvm build.

### Problem

Create a very basic intergration with the following Traits:
```
 traits:
    container:
      requestCPU: "200m"
      requestMemory: 20Mi
      limitMemory: 20Mi
    quarkus:
      buildMode:
      - jvm
      - native
```
The jvm pod will attempt to start and fail because 20MB is not enough for it, although it's enough for my native pod to start.
If I could setup different values for each container type, I would provide more memory to the jvm build during the native build time and lower memory for the native pod.

### Proposal

We might have something like this in the traits configuration:
```
 traits:
    container:
      jvm:
        requestCPU: "200m"
        requestMemory: 256Mi
        limitMemory: 256Mi
      native:
        requestCPU: "200m"
        requestMemory: 20Mi
        limitMemory: 20Mi
    quarkus:
      buildMode:
      - jvm
      - native
```
and keep the current configuration for backwards compatibility in case only one buildMode is set.
