### ISSUE TITLE
CRD's without cluster admin access / No direct network access from cluster

### ISSUE THREAD

**Issue by ColeFerrier** [apache/camel-k#512]
Related to 
https://github.com/apache/camel-k/issues/36

It would be good to have a way to setup camel-k without having cluster admin access. I need the ability to give cluster administrators what I need done at the cluster level. 

Let me know what I can do to help/test/etc.

**Comment by ColeFerrier** [comment]
Actually to pile on to this. I would like to be able to install without cluster admin access AND I need to know what if any artifacts that need to be brought from the internet. This means if I need to setup internal mirrors for various artifacts, I need a way to know about those.  I'm more then willing to help.

**Comment by nicolaferraro** [comment]
Hi @ColeFerrier, CRDs and roles need to be created by a cluster admin for Camel K to work. Fortunately, this can be done once, then you can use your standard credential for everything else. The list of resources to give to the admin for creation can be obtained from the command:

```
kamel install --cluster-setup -o yaml
```
...but you need to be connected as cluster admin to a cluster to see them, so I paste them here:

```
apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: integrationplatforms.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The IntegrationPlatform phase
      name: Phase
      type: string
    group: camel.apache.org
    names:
      kind: IntegrationPlatform
      listKind: IntegrationPlatformList
      plural: integrationplatforms
      shortNames:
      - ip
      singular: integrationplatform
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: integrationcontexts.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The IntegrationContext phase
      name: Phase
      type: string
    - JSONPath: .metadata.labels.camel\.apache\.org\/context\.type
      description: The IntegrationContext type
      name: Type
      type: string
    - JSONPath: .status.image
      description: The IntegrationContext image
      name: Image
      type: string
    group: camel.apache.org
    names:
      kind: IntegrationContext
      listKind: IntegrationContextList
      plural: integrationcontexts
      shortNames:
      - ictx
      singular: integrationcontext
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: integrations.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The Integration phase
      name: Phase
      type: string
    - JSONPath: .status.context
      description: The IntegrationContext to use
      name: Context
      type: string
    group: camel.apache.org
    names:
      kind: Integration
      listKind: IntegrationList
      plural: integrations
      shortNames:
      - it
      singular: integration
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: camelcatalogs.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .spec.version
      description: The Catalog version
      name: Version
      type: string
    group: camel.apache.org
    names:
      kind: CamelCatalog
      listKind: CamelCatalogList
      plural: camelcatalogs
      shortNames:
      - cc
      singular: camelcatalog
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app: camel-k
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
    name: camel-k:edit
  rules:
  - apiGroups:
    - camel.apache.org
    resources:
    - '*'
    verbs:
    - '*'
kind: List
metadata: {}
```

It's using java artifacts from maven central and apache servers by default. If you mean setting a maven mirror, I think @lburgazzoli has the solution (didn't find the doc).
