### ISSUE TITLE
Support for projected volumes at the Mount Trait

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5164]
### Requirement

I wish I could mount multiple config maps at the same directory. My use case is that I wish I could keep each resource file required by the Integration in its own config file and have all the files mounted at /etc/camel/resources location, regardless of where they came from.

### Problem

Keeping all files in a single config map makes editing a little bit harder, but may reach the 1MB size limit for config maps if the number of files grows.

### Proposal

We could use [projected volumes](https://kubernetes.io/docs/concepts/storage/projected-volumes/) for that;
The operator might detect config maps that are mapped to the same location and automatically use projected volumes to mount them. A configuration would exist to turn on this behavior.

**Comment by lsergio** [comment]
A scenario where this might be helpful is using multiple jsonata components in an Integration. Each one would require a template file.

**Comment by lburgazzoli** [comment]
I remember that we did try to do something similar in the past but we didn't succeed as there were some combinations not working, on top of my mind:

- knative not supporting projections
- the `${configmap|secret:name/key}` property placeholder function not working anymore

Things may have changed so it may not be an issue anymore but it would be nice to have a minimal design doc to assess the impact.

**Comment by lburgazzoli** [comment]
> A scenario where this might be helpful is using multiple jsonata components in an Integration. Each one would require a template file.

 
I see two way of addressing this issue:
- use `${configmap|secret:name/key}`
- reference the template as a classpath resource

Just for my understanding, is any of the two options potentially addressing the problem ?

**Comment by lsergio** [comment]
According https://knative.dev/docs/serving/services/storage/, projected volumes are supported in Knative.

**Comment by lburgazzoli** [comment]
Just to make ti clear, I'm not trying to push back on the implementation but I'm really curious about why the other solutions are not working since some of them were implemented for this use case :)

So I may be wrong but any config map entry, is then reachable by classpath so, in theory in your component you should be able to just use i.e. `file1.txt` (if the component has been updated to support the resource loader).

**Comment by lsergio** [comment]
@lburgazzoli Now I got your point.

I tested it like this:

Config Maps:
```
apiVersion: v1
data:
  file1.txt: "{\"name\": firstName}"
kind: ConfigMap
metadata:
  name: cm1
---
apiVersion: v1
data:
  file2.txt: "{\"name\": lastName}"
kind: ConfigMap
metadata:
  name: cm2

```
And the Integration:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: myintegration
spec:
  sources:
  - name: main.yaml
    language: yaml
    content: |-
      - from:
          uri: "rest:POST:/test"
          steps:
          - to:
              uri: "jsonata:/file1.txt?inputType=JsonString&outputType=JsonString"
          - to:
              uri: "log:info"
  traits:
    logging:
      level: DEBUG
    ingress:
      enabled: false
    knative-service:
      enabled: false
    mount:
      resources:
      - configmap:cm1
      - configmap:cm2
```
The files were still mounted at different directories:

k exec -it myintegration-74d7fdd854-cfbqw -- ls -R /etc/camel/resources
```
/etc/camel/resources:
cm1  cm2

/etc/camel/resources/cm1:
file1.txt

/etc/camel/resources/cm2:
file2.txt
```
but reading them from the classpath worked fine.

So, for components that can load classpath-based resources, this works fine.
The use case would then be components that eventually do not support so.

Thanks for the support.
