### ISSUE TITLE
Error configuring property: camel.component.test[00001]port[80]tcp.addr because cannot find component with name test[00001]port[80]tcp.

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5179]
### What happened?

I have created the following Integration:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: basic
spec:
  sources:
  - name: flow1.groovy
    content: |-
      from('quartz://flow1/trigger?cron=0+*+*+?+*+*')
         .to("https://httpbin.org/delay/2?bridgeEndpoint=true")
         .to("log:info")
```

It creates a CronJob to run every minute. 
When the Integration runs, I get the following error on its log:

```
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Error configuring property: camel.component.test[00001]port[80]tcp.addr because cannot find component with name test[00001]port[80]tcp. Make sure you have the component on the classpath
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:65)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	... 15 more
Caused by: java.lang.IllegalArgumentException: Error configuring property: camel.component.test[00001]port[80]tcp.addr because cannot find component with name test[00001]port[80]tcp. Make sure you have the component on the classpath
	at org.apache.camel.main.BaseMainSupport.lambda$doAutoConfigurationFromProperties$29(BaseMainSupport.java:1683)
	at org.apache.camel.main.MainHelper.computeProperties(MainHelper.java:407)
	at org.apache.camel.main.BaseMainSupport.doAutoConfigurationFromProperties(BaseMainSupport.java:1675)
	at org.apache.camel.main.BaseMainSupport.autoConfigurationFromProperties(BaseMainSupport.java:1638)
	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:447)
	at org.apache.camel.main.MainSupport.autoconfigure(MainSupport.java:73)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:627)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:78)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	... 16 more
```
00001 seems to be a knative revision number, so I decided to disable the knative trait:

```
  traits:
    knative:
      enabled: false
```
and the error disappeared.

As this integration did not create a Service/Knative Service, should the knative trait be activated?

This started to happen today in our cluster, so maybe it's also related to some environment configuration. If someone can provide some guidance, I would appreciate as well.

### Camel K version

2.2.0

**Comment by squakez** [comment]
Thanks for reporting. Is this happening only for cron based Integrations, or does it appear also on plain deployments?

**Comment by lsergio** [comment]
@squakez Here is an update with a few other scenarios:

**Scenario 1**
Quartz integration, Cron Trait configured with fallback:true
```
spec:
  sources:
  - name: flow1.groovy
    content: |-
      from('quartz://flow1/trigger?cron=0+*+*+?+*+*')
         .to("https://httpbin.org/delay/2?bridgeEndpoint=true")
         .to("log:info")
  traits:
    cron:
      fallback: true
```
**Results**
* Camel K created a deployment and not a CronJob (as expected)
* No Service or Knative Service/Revision was created (as expected)
* The deployment pod failed with the reported error
* Disabling the knative trait fixed the error

**Scenario 2**
Rest Integration, knatice-service trait disabled so the service is internal to the cluster only
```
spec:
  sources:
  - name: flow1.groovy
    content: |-
      from('rest:GET:/demo')
         .to("https://httpbin.org/delay/2?bridgeEndpoint=true")
         .to("log:info")
  traits:
    knative-service:
      enabled: false
```
**Results**
* Camel K created a deployment and a ClusterIP Service (as expected)
* No Knative Service/Revision was created (as expected)
* The deployment pod failed with the reported error
* Disabling the knative trait fixed the error

**Scenario 3**
Rest Integration, knatice-service trait enabled so the service is exposed with Knative
```
spec:
  sources:
  - name: flow1.groovy
    content: |-
      from('rest:GET:/demo')
         .to("https://httpbin.org/delay/2?bridgeEndpoint=true")
         .to("log:info")
  traits:
    knative-service:
      enabled: true
      minScale: 1
```
**Results**
* Camel K created a Knative Service (as expected)
* Knative created 2 services: `basic-00001` and `basic-00001-private`
* The deployment pod failed with the reported error
* Knative revision status remained with Ready = Unknown and Reason = Deploying
* Disabling the knative trait fixed the error, and it changed the number of services Knative created: now there are `basic`, `basic-0001` and `basic-00001-private` services.


So now I'm wondering if the Knative trait should play a role in scenarios where a service is not created - scenarios 1 & 2. And trying to understand why knative didn't create the 3 services in the 3rd scenario.

**Comment by lsergio** [comment]
Comparing the Knative services before and after the fix in the 3rd scenario, I see that when knative trait is enabled, the Knative Service declares the following environment variable:
```
        - name: CAMEL_KNATIVE_CONFIGURATION
          value: '{"services":[]}'
```
Per the docs, this env var is expected, but I'm not sure whether the service list should be empty.

**Comment by lsergio** [comment]
After further investigation into knative objects, I see the private endpoint was not assigned IP addresses:
```
basic-00001                                                   10.251.165.73:8012,10.251.165.73:8112   4m21s
basic-00001-private                                                                                   4m21s
```
And describing the private one shows me:
```
Name:         basic-00001-private
Namespace:    a1b2c3d4e5
Labels:       app=basic-00001
              camel.apache.org/integration=basic
              networking.internal.knative.dev/serverlessservice=basic-00001
              networking.internal.knative.dev/serviceType=Private
              serving.knative.dev/configuration=basic
              serving.knative.dev/configurationGeneration=1
              serving.knative.dev/configurationUID=4cbbd31b-a712-4e3f-a524-af181bf50662
              serving.knative.dev/revision=basic-00001
              serving.knative.dev/revisionUID=4156d7bc-7743-4ef9-a78c-6f4a57179372
              serving.knative.dev/service=basic
              serving.knative.dev/serviceUID=8ed0cca8-fe97-44c8-850e-c93e392acd49
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2024-02-26T13:49:25Z
Subsets:
  Addresses:          <none>
  NotReadyAddresses:  10.251.159.135
  Ports:
    Name             Port  Protocol
    ----             ----  --------
    http-usermetric  9091  TCP
    http             8012  TCP
    http-queueadm    8022  TCP
    http-istio       8012  TCP
    https            8112  TCP
    http-autometric  9090  TCP

Events:  <none>
```
The ip address is marked as NotReady. Looking into that...

**Comment by lsergio** [comment]
In order to perform an isolated knative test, I exported the knative service created by the integration and modified it to create a new ksvc:
- changed the image to ghcr.io/knative/helloworld-go:latest
- removed the mounted volumes
- removed the heatlh check probes
The final result:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/lastModifier: system:serviceaccount:a1b2c3d4e5:camel-k-operator
  labels:
    bindings.knative.dev/include: "true"
    camel.apache.org/generation: "1"
    camel.apache.org/integration: basic
  name: basic
  namespace: a1b2c3d4e5
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      creationTimestamp: null
      labels:
        camel.apache.org/integration: basic
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: TARGET
          value: "Go Sample v1"      
        image: ghcr.io/knative/helloworld-go:latest
        name: integration
      enableServiceLinks: false
      imagePullSecrets:
      - name: gcr-json-key
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
```

This ksvc worked all 3 services were created.
```
k get svc | grep basic
basic                                                         ClusterIP   None             <none>        80/TCP                                               4m9s
basic-00001                                                   ClusterIP   172.20.70.175    <none>        80/TCP,443/TCP                                       4m10s
basic-00001-private                                           ClusterIP   172.20.1.209     <none>        80/TCP,443/TCP,9090/TCP,9091/TCP,8022/TCP,8012/TCP   4m10s
```
Then I changed the ksvc and added a heath probe that would never succeed:
```
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 3000  
```
And now I get the same situation where the pod fails, and the basic service is not created.

So I think I can assume that the lack of one svc is actually a consequence, and not a cause of the pod failure.
