### ISSUE TITLE
Revuew integration digest computation and projection to the integration container as env var

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#5192]
### What happened?

Since an integration digest ends up begin [projected as a container env var](https://github.com/apache/camel-k/blob/9c058daa180106fb5b770558f9b553b7bfb9d2ef/pkg/trait/container.go#L181), [including the traits when computing the digest](https://github.com/apache/camel-k/blob/9c058daa180106fb5b770558f9b553b7bfb9d2ef/pkg/util/digest/digest.go#L111) has a number of side effects, as example by enabling/disabling the creation of a route or service, would lead to the container to be restarted which is not expected.

**Comment by lburgazzoli** [comment]
Triggering a reconciliation is fine, but that should not lead to a disruptive change in any resource so maybe we need two different digests or rethink how the reconciliation is re-triggered

**Comment by lburgazzoli** [comment]
If you have an integration like this one (flow omitted because it does not matter much):

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: r
spec:
  flows:
    ...
  traits:
    service:
      enabled: true
      auto: false
    ingress:
      enabled: true
      auto: false
```

And then:
1. deploy it
2. change `ingress.enable` to `false`
3. deploy it

Then what happen is that the pod is restarted

```
➜ k get pods                                   
NAME                                READY   STATUS        RESTARTS   AGE
camel-k-operator-6897f796dd-5znkm   1/1     Running       0          22m
r-677dcbf7fc-h7wx6                  0/1     Terminating   0          22s
r-6976c6b54b-8lccc                  1/1     Running       0          2s
```

Then, ignoring some of the stuffs that are changing as as side effect of pod restart (uuid, dates, etc), the only difference is in the digest:

![image](https://github.com/apache/camel-k/assets/1868933/bae6fdca-9ca6-408b-9038-22df17ba0a75)
