### ISSUE TITLE
Route parameters are ignored for `path` parameters

### ISSUE THREAD

**Issue by lordrip** [apache/camel-k#5203]
### What happened?

While testing Kaoto with CamelK in DevSpaces, I noticed that `parameters` are not honored when they are `path` parameters, making the integration fail.

Here's an example:

This works
```yaml
- route:
    from:
      uri: timer:ExampleTimer
      parameters:
        period: "1000"
      steps:
        - log:
            message: ${body}
```

Whereas this doesn't
This works
```yaml
- route:
    from:
      uri: timer
      parameters:
        period: "1000"
        timerName: ExampleTimer
      steps:
        - log:
            message: ${body}
```

The `path` parameter defined [in the catalog](https://github.com/apache/camel/blob/653b10d161e8fed1a68e6edec46621a59fa5f9f4/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/platform-http.json#L31)

### Steps to reproduce

1. Using the following route
```yaml
- route:
    from:
      uri: timer
      parameters:
        period: "1000"
        timerName: ExampleTimer
      steps:
        - log:
            message: ${body}
```
2. Deploy it to DevSpace
3. Notice the error message when deploying it
```log
error during trait customization: knative trait configuration failed: component not found for uri "timer?period=1000&timerName=ExampleTimer" in camel catalog runtime version 3.2.3'
```

### Camel K version

v2.2
