### ISSUE TITLE
Deployment Trait maxUnavailable and maxSurge default values differ from documentation and do not support % values

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5223]
### What happened?

Create an Integration and configure the Deployment trait as below:
```
traits:
    deployment:
      strategy: RollingUpdate
```
Per the docs, the default maxSurge and maxUnavailable should be 25%, but checking the Deployment we get 25, not 25%:
```
  strategy:
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
    type: RollingUpdate
```

It works, though, if we do not declare the deployment trait at all. In this case the deploment will be as below:
```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```

### Camel K version

2.2.0
