### ISSUE TITLE
List Camel's endpoint in the integrations status

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#5241]
### Requirement

List Camel's endpoint in the integrations status

### Problem

The camel-k operator can project the status of the Camel context/routes/etc to the Integration' status by scraping the health endpoint so that tools can get the status of the routes without having to interact with the running process. 

It would be nice to also have information about the endpoints registered with the Camel Context so as an example, advanced tools can draw a topology 

### Proposal

The Camel runtime could optionally expose some additional information, like those exposed by the [camel-console ](https://camel.apache.org/manual/camel-console.html) but in a production ready way (read only, minimal data). 

This production ready console Could be integrated with [Spring Boot actuators](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html) and [Quarkus management interface](https://quarkus.io/guides/management-interface-reference).

The camel-k operator could then grab such data and project it to the integration status:

```yaml
apiVersion: camel.apache.org/v2
kind: Integration
name: my-integration
spec:
  ...
status:
  endpoints:
    - url: "kafka:my-topic"
      parameters:
          broker: "my.kafka.broker.com"
    - url: "aws-s3:my-bucket"
      parameters:
          region: "eu"
```

Tools like HawtIO, OpenShift DevConsole could then be able to draw a topology of the existing integration and 3rd party systems.
