### ISSUE TITLE
Simplify Vaults addons

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5258]
# Problem

Right now we have the implementation of different vaults configuration in separate addons. We need to find a way to simplify its managment and harmonize the various parameters offered by the different providers

## Possible solution

Leveraging the draft work proposed in [1] and [2] we may simplify the management of vaults in a single trait in the following manner.

The catalog part would be like the following:
```
  capabilities:
      vault:
        hashicorp:
          runtimeProperties:
          - key: host
            value: camel.vault.hashicorp.host
          ...
        aws:
          runtimeProperties:
          - key: region
            value: camel.vault.aws.region
          ...
```
The logic on operator side would be an iteration over the required Camel properties driven by the catalog, whichever they are, making the maintenance a mere check that the given parameter exists in the catalog or not.
The user experience would be simpler as the user would be using the same trait but with a different provider every time needed. It would be something like:

```
kamel run test.yaml -t vault.aws.region=xyz ...
kamel run test.yaml -t vault.hashicorp.host=my-host ...
```

[1] https://github.com/apache/camel-k-runtime/pull/1185
[2] https://github.com/apache/camel-k/pull/5251
