### ISSUE TITLE
Could not determine source URI: cluster "camel-ai-kafka" has no listeners of type "plain"

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#5295]
### What happened?

I have a pipe to move data from a kafka topic to a vector database:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  annotations:
    trait.camel.apache.org/container.image: quay.io/megacamelus/assistant-ingestion-sink:latest
    trait.camel.apache.org/dependencies.enabled: "false"
    trait.camel.apache.org/jvm.enabled: "false"
    trait.camel.apache.org/kamelets.enabled: "false"
  name: camel-ai-ingestion-siknk
  namespace: camel-ai
spec:
  sink:
    properties:
      collection: cai
      qdrantHost: camel-ai
      qdrantPort: "6334"
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: qdrant-upsert-sink
  source:
    ref:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaTopic
      name: camel-ai-ingestion
  steps:
  - properties:
      embeddingId: camel-ai-ingestion-siknk
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: langchain-embeddings-action
 ```

And the a `Kafka`  resource as follow:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: camel-ai-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: "3.6"
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    replicas: 3
    storage:
      deleteClaim: true
      size: 10Gi
      type: persistent-claim
    version: 3.6.0
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: true
      size: 5Gi
      type: persistent-claim
status:
  clusterId: cRS2lQFkRwGaDeXtT90rWw
  conditions:
  - lastTransitionTime: "2024-03-27T08:37:54.609806285Z"
    status: "True"
    type: Ready
  kafkaVersion: 3.6.0
  listeners:
  - addresses:
    - host: camel-ai-kafka-kafka-bootstrap.camel-ai.svc
      port: 9092
    bootstrapServers: camel-ai-kafka-kafka-bootstrap.camel-ai.svc:9092
    name: plain
  - addresses:
    - host: camel-ai-kafka-kafka-bootstrap.camel-ai.svc
      port: 9093
    bootstrapServers: camel-ai-kafka-kafka-bootstrap.camel-ai.svc:9093
```

Then the pipe reports the following error:

```
Status:
  Conditions:
    Last Transition Time:  2024-03-27T12:31:56Z
    Last Update Time:      2024-03-27T12:31:56Z
    Message:               could not determine source URI: cluster "camel-ai-kafka" has no listeners of type "plain"
    Reason:                Couldn't create an Integration custom resource
    Status:                False
    Type:                  IntegrationError
```

### Camel K version

2.2.0
