### ISSUE TITLE
Annotations for dapr.io Sidecar Not Applied in Camel K Integration Deployment

### ISSUE THREAD

**Issue by venom90** [apache/camel-k#5313]
### What happened?

When deploying a Camel K integration with specified annotations for enabling and configuring the dapr.io sidecar, the annotations do not appear to be applied to the resulting pod. This issue prevents the Dapr sidecar from being correctly configured and attached to the Camel K integration pod.

**Environment**
Camel K Version: Camel K Client 2.2.0
Kubernetes Version: Kubernetes 1.29.1-do.0
Dapr Version: Runtime version: 1.13.1
Installation Method:  kamel CLI
Cluster Type: DigitalOcean Managed Kubernetes

## 1. Created a ConfigMap with the following content to specify dapr.io annotations:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: camelk-integration-config
data:
  integration.properties: |
    camel.k.pod.annotation.dapr.io/enabled=true
    camel.k.pod.annotation.dapr.io/app-id=helloapp
    camel.k.pod.annotation.dapr.io/config=tracing
```
## 3. Deployed the Camel K integration using the following command:
```bash
kamel run hello.js --config configmap:camelk-integration-config
```
## 4. Checked the deployed pod annotations using:

```bash
kubectl describe pod <pod-name>
```

### Relevant log output

```shell
{"level":"info","ts":"2024-03-31T18:55:20Z","logger":"camel-k.cmd","msg":"v1apha1.KameletBinding is deprecated, please, use v1.Pipe instead"}
```

### Camel K version

2.2.0
