### ISSUE TITLE
CLI install synthetic environment variable duplicate in operator pod container

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#5349]
### What happened?

Installing the operator with the CLI and the parameter ` --operator-env-vars=CAMEL_K_SYNTHETIC_INTEGRATIONS=true` does not always works to activate the synthetic integration support. This is because the default value (`false`) is still present in the pod's container spec.

### Steps to reproduce

Install the operator:
```
kamel install --operator-id=camel-k-synthetic-env --operator-env-vars=CAMEL_K_SYNTHETIC_INTEGRATIONS=true
```

Check the operator pod:
```yaml
spec:
  containers:
  - args:
...
    - name: CAMEL_K_SYNTHETIC_INTEGRATIONS
      value: "false"
    - name: CAMEL_K_SYNTHETIC_INTEGRATIONS
      value: "true"
    - name: KAMEL_OPERATOR_ID
      value: camel-k-synthetic-env
...
```

### Camel K version

main branch
