### ISSUE TITLE
Enhance environment trait to include values from secrets/configmaps

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5522]
We can enhance the trait to include values taken directly from secret without the need to expose them or to mount as files via `mount` trait. For example we should have something like `kamel run test.yaml -t env.vars=MY_VAR=secret:my-secret/my-value` converted in a Pod like:
```
apiVersion: v1
kind: Pod
...
spec:
  containers:
...
    env:
    - name: MY_VAR
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: my-value
```
