### ISSUE TITLE
property "type" must be provided when reading from the Broker

### ISSUE THREAD

**Issue by matzew** [apache/camel-k#5529]
### What happened?

Creating a logger-pipe that reads from the broker seems to not work:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: log-sink-pipe
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: kamelet
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
```

In theory it should create a trigger that has no filter, which is valid

### Steps to reproduce

1. create knative broker
2. create a logger like above
3. see the logs

### Relevant log output

```shell
{"level":"info","ts":"2024-05-21T09:38:00Z","logger":"camel-k.controller.pipe","msg":"Initializing Pipe","request-namespace":"default","request-name":"log-sink-pipe","api-version":"camel.apache.org/v1","kind":"Pipe","ns":"default","name":"log-sink-pipe"}
{"level":"info","ts":"2024-05-21T09:38:00Z","logger":"camel-k.controller.pipe","msg":"State transition","request-namespace":"default","request-name":"log-sink-pipe","api-version":"camel.apache.org/v1","kind":"Pipe","ns":"default","name":"log-sink-pipe","phase-from":"","phase-to":"Error"}
{"level":"info","ts":"2024-05-21T09:38:00Z","logger":"camel-k.controller.pipe","msg":"Integration error","request-namespace":"default","request-name":"log-sink-pipe","api-version":"camel.apache.org/v1","kind":"Pipe","ns":"default","name":"log-sink-pipe","reason":"Couldn't create an Integration custom resource","error-message":"could not determine source URI: property \"type\" must be provided when reading from the Broker"}
{"level":"error","ts":"2024-05-21T09:38:00Z","msg":"Reconciler error","controller":"pipe-controller","object":{"name":"log-sink-pipe","namespace":"default"},"namespace":"default","name":"log-sink-pipe","reconcileID":"76ed504b-a166-4df7-b457-360c3f606dab","error":"could not determine source URI: property \"type\" must be provided when reading from the Broker","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:226"}

```
```


### Camel K version

2.3.1
