### ISSUE TITLE
Pipe not correctly reconciled after updating it

### ISSUE THREAD

**Issue by matzew** [apache/camel-k#5531]
### What happened?

Creating a wrong, or currently not supported, `Pipe` (see #5529), and updating it (`k apply`), does not reflect in a working Pipe, even if it is correct.

Wrong (or not supported):
```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: log-sink-pipe
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: kamelet
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
```
Updated/supported:
```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: log-sink-pipe
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: kamelet
    properties:
      type: <my CE type>
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink

```

### Steps to reproduce

1. create wrong pipe
2. edit and correct it and re-apply it
3. see it is still not working
4. delete it
5. recreate it. see that it now works

### Camel K version

2.3.1
