### ISSUE TITLE
Integration reporting timeout error before the timeout expires 

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5552]
### What happened?

I have Camel-K running on an EKS cluster with autoscaling groups scaling up to 20 nodes.
At the moment this was reported, 8 nodes were running, and I created a new Integration object.

There was no room for a new pod in the running nodes, so Kubernetes spawned a new one. However, the Integration reported as Error immediately, even before the Deployment progress deadline expired.

This is the Integration report:

```
  - lastTransitionTime: "2024-05-27T17:42:16Z"
    lastUpdateTime: "2024-05-27T17:42:16Z"
    message: '0/8 nodes are available: 1 node(s) were unschedulable, 7 Insufficient
      cpu. preemption: 0/8 nodes are available: 1 Preemption is not helpful for scheduling,
      7 No preemption victims found for incoming pod..'
    reason: Error
    status: "False"
    type: Ready
```
And this is the Deployment status:
```
status:
  conditions:
  - lastTransitionTime: "2024-05-27T17:42:16Z"
    lastUpdateTime: "2024-05-27T17:42:16Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-05-27T17:42:16Z"
    lastUpdateTime: "2024-05-27T17:42:16Z"
    message: ReplicaSet "deploy-4f2a232d-fec3-42ad-b437-b5c47fcf1804-copy-5dbc986949"
      is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
```
As we can see, the deployment is still progressing.

I expected the status to be Error only after the progress deadline expired.

### Camel K version

2.2.0

**Comment by lsergio** [comment]
After the new node is created, the Integration status changes to Ready = true. The impact on my side is that the Error triggers the wrong workflow on my monitoring application.

**Comment by squakez** [comment]
I think the correct way to monitor an healthy Integration is to watch both `.status.phase` and `.conditions[READY]==true` and ideally you should include the readiness probe via health trait to make sure that the Camel context is ready. This is because you probably don't want to trust blindly Kubernetes Deployment (which you can see it's not reporting an error status) but the Camel context, which is the application one knowing if something is healthy or not via its internal mechanisms.

**Comment by lsergio** [comment]
I checked the [source code](https://github.com/apache/camel-k/blob/main/pkg/controller/integration/monitor_deployment.go#L49) and looks like the Deployment monitor is waiting for the progressdeadlineexceeded status to report an Integration error.

**Comment by lsergio** [comment]
After reading [this method](https://github.com/apache/camel-k/blob/v2.2.0/pkg/controller/integration/monitor.go#L349), I figured out what is happening:

While there's no available nodes, the integration pod status is Pending and it reports:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-05-28T12:00:15Z"
    message: '0/6 nodes are available: 6 Insufficient cpu. preemption: 0/6 nodes are
      available: 6 No preemption victims found for incoming pod..'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

The monitor detects the Unschedulable reason and sets the Error reason in the Integration.
When the new node is ready, that condition changes to:

```
  - lastProbeTime: null
    lastTransitionTime: "2024-05-28T12:01:07Z"
    status: "True"
    type: PodScheduled
```

There probably is a good reason for checking the pending Pod statuses, but shouldn't it be enough to check the Deployment status? Any issue with the pods will (or should) reflect on the Deployment status.

For my specific monitoring case, I will try and check the Deployment status. If it is still Progressing, I will ignore the Error reason.
