### ISSUE TITLE
Service/KService not created for vertx-websocket consumers

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5628]
### What happened?

I created an Integration with the following manifest:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: vertx-server
spec:
  sources:
  - name: main.groovy
    content: |-
      from("vertx-websocket:/my-websocket-path")
        .setBody().constant("Hello World");  
```
using the example provided at https://camel.apache.org/camel-quarkus/3.8.x/reference/extensions/vertx-websocket.html to expose a websocket endpoint.

When I apply the integration file, the pod is created and I can port-forward to it on port 8080.
However, no service or knative-service is created. I can see only a deployment.

Enabling either the service or knative-service traits didn't help either.

Is this expected to work out of the box?

### Camel K version

2.2.0
