### ISSUE TITLE
Add TLS configuration in the ingress trait

### ISSUE THREAD

**Issue by romain-pfund** [apache/camel-k#5635]
### Requirement

As an integration developper using camel-k, I want to user TLS on my ingresses so I can securely contact my camel-k integrations

### Problem

To fully configure TLS on an ingress, we need to set the spec.tls part (hosts and secretName).
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
But this is actually not covered by the actual ingress trait

### Proposal

Implement this configuration properties:

```
ingress.tls.hosts      |  list[string]
ingress.tls.secretName |  string
```

to set

```
apiVersion: networking.k8s.io/v1
kind: Ingress
...
spec:
  tls:
  - hosts:
      - {{ingress.tls.hosts[]}}
    secretName: {{ingress.tls.secretName}}
 ...
```
