### ISSUE TITLE
Integration status condition typo

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5706]
### What happened?

Create a Rest Integration with knative trait enabled, like below:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-381
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: rest:get:/demo
          steps:
          - setBody:
              constant: "It worked"
  traits:
    knative-service:
      minScale: 1
    camel:
      runtimeVersion: 3.8.1
```

After the integration is running, check its status:

```
kubectl get it deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-323 -oyaml
```
and look at the conditions to find:

```
  - lastTransitionTime: "2024-07-24T17:30:52Z"
    lastUpdateTime: "2024-07-24T17:30:52Z"
    message: 'controller strategy: knative-service'
    reason: DeploymentAvailable
    status: "False"
    type: DeploymentDeploymentAvailable
```
In Camel K 2.2, `type` used to be `DeploymentAvailable` only, whereas now it is `DeploymentDeploymentAvailable`.

I could not find any related change on the release notes, so I'm assuming this was not intentional. If this is by design, please just close it.

### Camel K version

2.3.3

**Comment by lsergio** [comment]
A new scenario. Now when a quartz integration is created:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: deploy-a41357e7-14c0-4a64-9933-80044f023ad3-381
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: quartz://ipaas/trigger?cron=0+*+*+?+*+*
          steps:
          - log:
              message: "It worked"
  traits:
    camel:
      runtimeVersion: 3.8.1
    cron:
      fallback: true
```
I see the conditions:

```
  - firstTruthyTime: "2024-07-24T18:42:31Z"
    lastTransitionTime: "2024-07-24T18:42:31Z"
    lastUpdateTime: "2024-07-24T18:42:31Z"
    message: deployment name is deploy-a41357e7-14c0-4a64-9933-80044f023ad3-323
    reason: DeploymentAvailable
    status: "True"
    type: DeploymentAvailable <-- DeploymentAvailable and not DeploymentDeploymentAvailable (when status is True)
  - lastTransitionTime: "2024-07-24T18:42:31Z"
    lastUpdateTime: "2024-07-24T18:42:31Z"
    message: different controller strategy used (deployment)
    reason: KnativeServiceNotAvailable
    status: "False"
    type: KnativeServiceKnativeServiceAvailable <-- KnativeService prefix duplicated
  - lastTransitionTime: "2024-07-24T18:42:31Z"
    lastUpdateTime: "2024-07-24T18:42:31Z"
    message: fallback strategy selected
    reason: CronJobNotAvailableReason
    status: "False"
    type: CronCronJobAvailable <-- Cron prefix duplicated
```
It seems like the relased Trait name is being prefixed to the type value when the status is False.
