### ISSUE TITLE
BuilderTrait nodeSelector configuration not working for jvm builds

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5838]
### What happened?

Builder trait nodeSelector configuration is not being used on jvm builders

### Steps to reproduce

- Configure the IntegrationPlatform to use the `pod` build strategy, and also to add a nodeSelector to the builder pods:
```
  spec:
    build:
      buildConfiguration:
        strategy: pod
    traits:
      builder:
        nodeSelector:
          kubernetes.io/arch: amd64
```
- Create the following Integration:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: rest
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: rest:get:/demo
          steps:
          - setBody:
              constant: "It worked"
  traits:
    knative-service:
      enabled: true
      minScale: 1
```
- Check the generated builder pod spec. There will be no nodeSelector.
- Add the quarkus trait to the Integration spec:
```
    quarkus:
      buildMode:
        - native
```
- Recreate the Integration and recheck the builder pod. Now the nodeSelector will be there

### Camel K version

2.4.0
