### ISSUE TITLE
Jolokia is failing (again)

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5855]
```
❌ TestJolokiaTrait (1m11.61s)
      jolokia_test.go:59: 
          Expected
              <*url.Error | 0xc0006ca7b0>: 
              Get "https://192.168.49.2:8443/api/v1/namespaces/test-ed93d2ad-6a83-429f-81f0-6e3ef829aa45/pods/javasfunp-6475d7b5b-v5jwp/proxy/jolokia/?timeout=30s": context deadline exceeded
              {
                  Op: "Get",
                  URL: "https://192.168.49.2:8443/api/v1/namespaces/test-ed93d2ad-6a83-429f-81f0-6e3ef829aa45/pods/javasfunp-6475d7b5b-v5jwp/proxy/jolokia/?timeout=30s",
                  Err: <context.deadlineExceededError>{},
              }
          to be nil
```

**Comment by tadayosi** [comment]
Could it relate to the recent Jolokia 2.1.x updates?

**Comment by squakez** [comment]
Thanks @tadayosi I think it does as it happened last time. However it's kind of weird, in the sense that we should be using the previous dependency released which is 2.0.2. The container spec is in fact:
```
               spec:
                containers:
                - args:
                  - -javaagent:dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar=discoveryEnabled=false,host=*,port=8778,protocol=http,useSslClientAuthentication=false
                  - -cp
                  - dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar
                  - -Xmx268M
                  - -cp
                  - ./resources:/etc/camel/application.properties:/etc/camel/resources:/etc/camel/resources.d/_configmaps:/etc/camel/resources.d/_secrets:/etc/camel/sources/Java.java:dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar:dependencies/quarkus/*
                  - io.quarkus.bootstrap.runner.QuarkusEntryPoint
                  command:
                  - java
```
so, I'd expect this to work. Or is there any reason why an older dependency won't work when a new version is over?
