### ISSUE TITLE
Camel-K creating new KnativeService instead of updating the existing one

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5874]
### What happened?

Camel-K is creating a new KnativeService instead of updating the existing one when the Integration is updated, causing some downtime.

### Steps to reproduce

- Create an Integration like the one below:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: knativetest
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: rest:get:/hello
          steps:
          - log:
              message: "hello"
  traits:
    knative-service:
      enabled: true
      minScale: 1
```
Check the created ksvc and revision objects:
```
 k get it knativetest -oyaml | grep uid
  uid: ced95979-054a-4b78-9e09-580bf1b93ecd
  
 k get ksvc knativetest -oyaml | grep uid
    uid: ced95979-054a-4b78-9e09-580bf1b93ecd <--- Integration uid
  uid: 67262fb4-7a18-42b4-9d42-c168cae60061 <- Knative Service uid


 k get revision | grep knativetest
knativetest-00001                                   knativetest                                   1            True             1                 1
```

Now update the Integraton changing the code and recheck the info;

```
 k get it knativetest -oyaml | grep uid  
  uid: ced95979-054a-4b78-9e09-580bf1b93ecd
 k get ksvc knativetest -oyaml | grep uid
    uid: ced95979-054a-4b78-9e09-580bf1b93ecd <---- Same Integration uid
  uid: 4fe4b46b-e418-4c27-875a-bcd68f49113b <--- Different Knative Service
 k get revision | grep knativetest       
knativetest-00001                                   knativetest                                   1            True             1                 1
```
As we can see, Camel-K created a new Knative Service instead of updating the existing one - updating the existing one would generate a new Revision and rollout traffic without downtime. But deleting and recreating the KService causes some downtime until the new Revision 1 is ready. 

With 2.2.0 it worked as described, updating the knative service and creating revision 2.

### Camel K version

2.4.0
