### ISSUE TITLE
pipe  and integration creation based on YAML file fails , 

### ISSUE THREAD

**Issue by pguptajsq** [apache/camel-k#5963]
### What happened?

i have this yaml  and applied , it created pipe and integration but it showing error 
```

kubectl logs pipe/test
error: no kind "Pipe" is registered for version "camel.apache.org/v1" in scheme "pkg/scheme/scheme.go:28"
```

and also Integration 
```
kubectl get it
NAME                            PHASE   READY   RUNTIME PROVIDER   RUNTIME VERSION   CATALOG VERSION   KIT                        REPLICAS
test                       Error   False   quarkus            3.15.0            3.15.0            kit-ct1up2gro8bs73dchil0   1

```

```

kind: Pipe
metadata:
  name: test
  namespace: camel-k
spec:
  sink:
    properties:
      channel: channelname
      destinationName: destinan
      password: '{{pass}}'
      queueManager: test.UAT.BSSB
      serverName: serverip
      serverPort: "1414"
      username: app
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: jms-ibm-mq-sink
  source:
    properties:
      queueNameOrArn: queue
      region: us-west-2
      accessKey: "dummy"
      secretKey: "dummy/sk45"
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: aws-sqs-source
```

Any idea what's missing here? 

Another Query how we can pass ServiceAccount to pipe yaml instead of aws accesskey and secretkey
