### ISSUE TITLE
Integration stuck at Building Kit if properties are defined, but the runtime is not

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#6006]
### What happened?

Consider the following Integration:

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: bugproperties
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: rest:get:/demo
          steps:
          - setBody:
              constant: "It worked"
  traits:
    health:
      enabled: true
    camel:
      properties:
      - hello=world
```

When I apply it to my cluster, the Integrations remains stuck at Building Kit:

```
k get it
NAME            PHASE          READY   RUNTIME PROVIDER   RUNTIME VERSION   KIT   REPLICAS
bugproperties   Building Kit           quarkus            3.2.3                   

```

If I include the runtimeVersion at the camel trait:
```
    camel:
      runtimeVersion: 3.2.3
      properties:
      - hello=world
```
or remove the trait completely, the integration build finishes successfully.

I checked the operator log and there is no error message related to the trait. Logs look good as usual.

### Camel K version

2.4.0

**Comment by squakez** [comment]
Can you verify the status of IntegrationKit and Build resources as well? I think that you have some building against the default Camel version (3.8.1 in Camel K 2.4.0) which are failing for some reason. Likely, setting the runtime version would reuse the existing Kit.

**Comment by lsergio** [comment]
@squakez sure. Here are some more details.

My Integrationplatform is setup so the default runtime is 3.2.3:

```
  traits:
    builder:
      incrementalImageBuild: true
      nodeSelector:
        kubernetes.io/arch: amd64
    camel:
      runtimeVersion: 3.2.3
    deployment:
      progressDeadlineSeconds: 600
    pull-secret:
      secretName: gcr-json-key

```

This is the status of the kit, build and Integration:
```

kubectl get it,ik,build
NAME                                         PHASE          READY   RUNTIME PROVIDER   RUNTIME VERSION   KIT   REPLICAS
integration.camel.apache.org/bugproperties   Building Kit           quarkus            3.2.3                   

NAME                                                       ALIAS   PHASE   TYPE       LAYOUT     IMAGE                                                                                                                                    ROOT
integrationkit.camel.apache.org/kit-ctil23aacioc739qcn30           Ready   platform   fast-jar   gcr.io/registry-ipaas-testing/camel-k-kit-ctil23aacioc739qcn30@sha256:da2200eb18d562ed763b8ca391e377c0be36c06d19027c0571a27585cadb486e   ***root image omitted***

NAME                                              PHASE       AGE    STARTED   DURATION         ATTEMPTS
build.camel.apache.org/kit-ctil23aacioc739qcn30   Succeeded   3m1s   3m1s      2m7.704334665s   
```

And these are the final log message from the operator:
```
{"level":"info","ts":"2024-12-20T11:14:20Z","logger":"camel-k.controller.build","msg":"Build duration 2m7.704334665s","request-namespace":"mynamespace","request-name":"bugproperties","build-attempt":0,"build-result":"Succeeded","build-duration":127.704334665,"api-version":"camel.apache.org/v1","kind":"Build","ns":"mynamespace","name":"kit-ctil23aacioc739qcn30"}
{"level":"info","ts":"2024-12-20T11:14:20Z","logger":"camel-k.controller.build","msg":"State transition","request-namespace":"mynamespace","request-name":"kit-ctil23aacioc739qcn30","api-version":"camel.apache.org/v1","kind":"Build","ns":"mynamespace","name":"kit-ctil23aacioc739qcn30","phase-from":"Running","phase-to":"Succeeded"}
{"level":"info","ts":"2024-12-20T11:14:20Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"mynamespace","request-name":"kit-ctil23aacioc739qcn30","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"mynamespace","name":"kit-ctil23aacioc739qcn30"}
{"level":"info","ts":"2024-12-20T11:14:20Z","logger":"camel-k.controller.integrationkit","msg":"State transition","request-namespace":"mynamespace","request-name":"kit-ctil23aacioc739qcn30","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"mynamespace","name":"kit-ctil23aacioc739qcn30","phase-from":"Build Running","phase-to":"Ready"}
{"level":"info","ts":"2024-12-20T11:14:20Z","logger":"camel-k","msg":"Kit kit-ctil23aacioc739qcn30 ready, notify integration: bugproperties"}
{"level":"info","ts":"2024-12-20T11:14:20Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action monitor","request-namespace":"mynamespace","request-name":"kit-ctil23aacioc739qcn30","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"mynamespace","name":"kit-ctil23aacioc739qcn30"}
```

I'll test with other default runtimes and let you know if the behavior changes.
