### ISSUE TITLE
Ingress Docs Misgenerated

### ISSUE THREAD

**Issue by cfitzw** [apache/camel-k#6028]
### What happened?

As per #5996, the documentation generated the depreciation method on the new `paths` versus the old `path`.

The PR looks correct.

### Steps to reproduce

See NEXT documentation:

https://camel.apache.org/camel-k/next/traits/ingress.html

### Relevant log output

```shell

```

**Comment by squakez** [comment]
Not sure to understand which the issue is. I can see the documentation correctly report the deprecation notice.

**Comment by squakez** [comment]
Ah, ok, I got it, it would be paths that has to be used instead of path.

**Comment by squakez** [comment]
@cfitzw can you take care of it?

**Comment by cfitzw** [comment]
I re-reviewed the PR #5996, and the only thing that stands out is:

camel-k/helm/camel-k/crds/camel-k-crds.yaml --> line 31184-3118 got repeated and could be deleted.
```
  path:
    description: |-
      To configure the path exposed by the ingress (default `/`).
      Deprecated: In favor of `paths` - left for backward compatibility.
    type: string
```

HOWEVER, when I look at `main` branch now, in this same file, I see the text is incorrectly everywhere under `paths`, which differs from PR...

Could that duplicated block have caused this, even though everything in the PR otherwise looked correct?

Please advise.
