### ISSUE TITLE
Set env var with Kamel

### ISSUE THREAD

**Issue by abouchama** [apache/camel-k#606]
Is it  possible to set env var directly from the CLI Kamel ?

**Comment by abouchama** [comment]
Many times we need to extend JAVA_OPTIONS, or to set JAVA_MAX_MEM_RATIO, NO_PROXY arguments. Those arguments are treated by the (run-java.sh) https://github.com/fabric8io-images/run-java-sh/blob/master/fish-pepper/run-java-sh/fp-files/run-java.sh#L22

**Comment by astefanutti** [comment]
I think that's possible by using a configuration of type `env` in the integration spec, e.g.:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Integration
spec:
  configuration:
  - type: env
    value: JAVA_OPTIONS=...
```

I don't think you can add it using `kamel run`, but you can `kubectl edit ...` the integration.
