### ISSUE TITLE
allow to configure default configurations on platform

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#608]
So one can configure something like:

```
apiVersion: camel.apache.org/v1alpha1
kind: IntegrationPlatform
metadata:
  name: camel-k
spec:
  ...
  configuration:
  - type: property
    value: logging.level.org.apache.camel=DEBUG
  - type: property
    value: camel.context.streamCaching=true
  - type: env
    value: JAVA_OPTIONS=...
  profile: Knative
  resources:
  ...
```
