### ISSUE TITLE
Values from file-based ConfigMaps are not available as properties with plain-quarkus

### ISSUE THREAD

**Issue by cfitzw** [apache/camel-k#6157]
### What happened?

When mounting a file-based configmap, using the `plain-quarkus` runtime, the associated values from the ConfigMap are not made available as properties.

This is only true when using the `plain-quarkus` runtime and works as expected with the default runtime as of v2.6.

### Steps to reproduce

1. Create a file-based ConfigMap
2. Pull in the ConfigMap into the integration
3. Attempt to reference a property:

```bash
# file: app.properties
my-variable=result
```

```bash
kubectl create configmap my-configmap --from-file=app.properties
```

```yaml
# camel-k: config=configmap:my-configmap

- from:
    uri: "timer:tick?period=1000"
    steps:
      - setBody:
          simple: "{{my-variable}}"
      - to: "log:info"
```

### Relevant log output

```shell

```

### Camel K version

v2.6
