### ISSUE TITLE
no matches for kind "BuildConfig" in version "build.openshift.io/v1"

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#739]
This happens after some hours past installation. Restarting the operator works.

OCP 4.1 on crc. May be a problem with service accounts?

```
camel-k-operator-cbcdd48c6-86kkg camel-k-operator {"level":"error","ts":1560325276.7602003,"logger":"camel-k.controller.integrationcontext","msg":"IntegrationContext state transition","request-namespace":"nicola","request-name":"ctx-bk0anrk29fo2j37rof10","api-version":"camel.apache.org/v1alpha1","kind":"IntegrationContext","ns":"nicola","name":"ctx-bk0anrk29fo2j37rof10","phase":"Error","error":"cannot delete build config: no matches for kind \"BuildConfig\" in version \"build.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/apache/camel-k/pkg/util/log.Logger.Error\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/util/log/log.go:70\ngithub.com/apache/camel-k/pkg/controller/integrationcontext.(*buildAction).handleBuildRunning\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/controller/integrationcontext/build.go:204\ngithub.com/apache/camel-k/pkg/controller/integrationcontext.(*buildAction).Handle\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/controller/integrationcontext/build.go:60\ngithub.com/apache/camel-k/pkg/controller/integrationcontext.(*ReconcileIntegrationContext).Reconcile\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/controller/integrationcontext/integrationcontext_controller.go:154\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

```

**Comment by abouchama** [comment]
Hi @nicolaferraro , I have the same issue on OCP 4.2.2

```
$oc get ik kit-bn5bjgmu0rc1h2blf8bg -o yaml

failure:
    reason: 'cannot delete build config: no matches for kind "BuildConfig" in version
      "build.openshift.io/v1"'
    recovery:
      attempt: 5
      attemptMax: 5
      attemptTime: "2019-11-12T13:57:34Z"
    time: "2019-11-12T13:55:17Z"
  phase: Error
  platform: camel-k
  runtimeVersion: 1.0.5
  version: 1.0.0-M3

```
In the logs of camel k operator, we have the following lines:

```
{"level":"info","ts":1573567059.6202052,"logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"knativetutorial","request-name":"kit-bn5bjgmu0rc1h2blf8bg"}
{"level":"info","ts":1573567059.620275,"logger":"camel-k.controller.build","msg":"Invoking action error","request-namespace":"knativetutorial","request-name":"kit-bn5bjgmu0rc1h2blf8bg","api-version":"camel.apache.org/v1alpha1","kind":"Build","ns":"knativetutorial","name":"kit-bn5bjgmu0rc1h2blf8bg"}
```
