### ISSUE TITLE
Moving api to v1

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#921]
As we are approaching v1.0.0 we should think about moving the camel-k API out of alpha/beta and move to v1

//cc @nicolaferraro @astefanutti

**Comment by astefanutti** [comment]
Totally makes sense.

**Comment by nicolaferraro** [comment]
We can set versions like this:
```
  versions:
    - name: v1alpha1
      served: true
      storage: false
    - name: v1
      served: true
      storage: true
```

It means that we store resources in version `v1` but also clients using `v1alpha1` will still continue to work (e.g. Knative Camel Sources and others).

This change assumes that there are no changes between `v1alpha1` and `v1`. The alternative is to adding mutating webhooks, which complicates too much the deployment.
Since we're moving from alpha to stable, I'd do minor changes without caring about conversion (mentioning possible minor changes in release notes).

I'd migrate **all** APIs to `v1` because `Integration` and `IntegrationPlatform` are pretty stable and all the others are internal APIs and people should not care a lot about their stability.

I'd do all changes after other big PRs are merged.. doing some tests now.
