### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#934]
As today we have a profile concept but it is related only to the platform , we should introduce a user profile concept as a way to share common options among integrations

something like:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: IntegrationProfile
metadata:
  name: my-profile
  labels:
    app: "camel-k"
spec:
  configuration:
    - type: "property"
      value: "my.property=my.value"
    - type: "property"
      value: "my.property=my.value"
  traits:
    container:
      configuration:
        enabled: true
  dependencies:
    - mvn:org.apache.camel.k/camel-k-runtime-main
    - mvn:org.apache.camel.k/camel-k-loader-js
```

User should be able to use it with something like:

    kamel run integration.json --integration-profile my-profile
